### ISSUE TITLE
"Mobility (MDM and MAM)" requires Global Admin role

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/memdocs#1002]
This is greyed out for a user with the role "Intune Administrator" but mentions Intune Administrator at the beginning of the page.  It would be worth calling out that modifying the "Mobility (MDM and MAM)" in Azure AD requires Global Administrator permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1e311c-c5ff-1c68-028d-e4fddda23324
* Version Independent ID: 1d2174e5-8984-8d9c-34c5-dfbcc619b410
* Content: [Set up enrollment for Windows devices by using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enroll)
* Content Source: [memdocs/intune/enrollment/windows-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
8894737

**Comment by ErikjeMS** [comment]
Repinged pm...

**Comment by joeselway** [comment]
*bump*

**Comment by lenewsad** [comment]
Hi @joeselway, @russrimm, Thank you for reaching out to the Microsoft Intune Docs team. We've been unable to resolve this issue in a timely manner and apologize for the delayed response. *Global Administrator permissions* is listed as a pre-req for enabling Windows automatic enrollment in the **Mobility (MDM and MAM)** area of Azure AD so it looks like the doc has been updated to incorporate your suggestion. Since no other doc changes are needed, we're closing this issue but feel free to comment here as necessary.
