### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ram419** [MicrosoftDocs/memdocs#1048]
[Shouldn't this cleanup be a built-in site maintenance task?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5902fbb-8ca5-6cfb-bb5e-fbbe4d68e712
* Version Independent ID: 51544ed6-18b7-d926-e45f-c817b8e26d69
* Content: [Content library cleanup tool - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool?source=docs)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/content-library-cleanup-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Ram419 for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
