### ISSUE TITLE
unclear information

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/memdocs#1053]
Its unclear for the following:
SCEP Server URLs:

If we use the Intune connector, do we still need a public URL with a publicly routable domain name, or can we place our .corp domain here?  If we have to use a routable domain the whole page is flawed and needs to be updated at the beginning that this while setup requires to be publicly accessible with publicly routable domain names.  Also if a routable domain name is still required why even have the connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c444f9-5cc4-7276-6882-d6b32ee453ea
* Version Independent ID: f1ec96ac-c890-2ed1-ede4-179de4b4e4cc
* Content: [Use SCEP certificate profiles with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep)
* Content Source: [memdocs/intune/protect/certificates-profile-scep.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-profile-scep.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@SquirrelAssassin   Thanks for the post. I checked with our engineering team on this, and they provided some clarifications which help explain why the public URL is needed. 

For the certificate requests to work, there must ben an accessible URL.  While its possible to use an on-premises SCEP endpoint,  every time a new cert is needed, or needs to be renewed, device would need to VPN in to that on-premises endpoint.  With that configuration there’s chance that due to timing that the certificate would expire before its renewed, which in turn can lead to a failure to connect to the VPN, which ends the use of the certificate, and the ease of getting a new one.   

Its highly recommended that the Server URL be a publicly accessible SCEP endpoint so that devices can get certificates from anywhere without relying on VPN.

For the connector, it's required with Microsoft CAs as there is a challenge validation for the SCEP request, regardless of whether the SCEP endpoint is internet or intranet facing.

**Comment by SquirrelAssassin** [comment]
I think what you meant to say was use an app proxy in Azure?
