### ISSUE TITLE
Languauge Settings in Autopilot Deployment Profile & Pre-Provisioning (WhiteGlove) changes in Windows 10 2004 & 20H2 - missing from documentation

### ISSUE THREAD

**Issue by simon-sayz** [MicrosoftDocs/memdocs#1075]
As per the following page - https://oofhours.com/2020/02/03/configure-language-settings-for-any-scenario/?fbclid=IwAR06KyBsCT4P4jD7ZTm7mjcl0G20gKZrP3EpmMZD_f28GaTB2frrqQ4dzHw , the process for Pre-Provisioning (WhiteGloving) devices has changed in Windows 10 Build 2004 & 20H2.

If you configure the language settings in the Autopilot profile, and the device is connected to Ethernet, all scenarios will now skip the language, locale, keyboard & **autopilot configuration page**.

you won't be able to initiate a white glove deployment as the Out Of Box Experience (OOBE) screen will automatically progress past the point where you can press the Windows key 5 times.

If you want to automatically choose a language, don't do white glove; if you want to do white glove, don't configure these.

As per the blog post, MS may try to remove this restriction in a future release (alternatively, you could choose not to make a network connection, e.g. don't connect the Ethernet cable, until after you've pressed the Windows key 5 times.)

There is no official document which explains this change of behaviour on Windows 10 2004 - 20H2, and having this on the docs page will assist people in future who are experiencing this issue (I have spent countless hours attempting to figure this out)

**Comment by ErikjeMS** [comment]
@simon-sayz What Intune article does this issue apply to?

**Comment by simon-sayz** [comment]
Hi @ErikjeMS 

This is with regards to the following document - https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-whats-new#:~:text=1903%20or%20later.-,New%20in%20Windows%2010%2C%20version%201809,button%20during%20the%20deployment%20process.

Cheers
Simon

**Comment by greg-lindsay** [comment]
Thanks, we are working on updating this.  I'll close the issue when we have completed the update.

**Comment by meisterheister** [comment]
See also my detailed issue report #1285.

**Comment by frankroj** [comment]
Thank you for the feedback @simon-sayz. I apologize for the time it took to get back to you regarding this feedback item. Since you filed this feedback item, this issue has been resolved and should work in the latest versions of Windows 10 22H2 and Windows 11 22H2. You shouldn't need to set Automatically configure keyboard to No or the language to User select for it to work. I have personally tested this configuration and can confirm I can hit the Windows key 5 times to start the pre-provision deployment when the device first boots up. If you are finding you are having the problems with older but still supported version of Windows, please let me know
