### ISSUE TITLE
Require approved client app (Conditional Access)

### ISSUE THREAD

**Issue by Coopem16** [MicrosoftDocs/memdocs#108]
I have gotten some conflicting information. Does building a LOB application with the Intune SDK allow it to work with The Conditional Access, require Approved Client App? I keep getting pointed to this Documentation:
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-approved-client-app
And told it needs to be on this list. A LOB built with the intune SDK would never be in that list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55564daa-5298-5b0b-9ff2-df25c5bbc0ea
* Version Independent ID: 26cb3db3-eba8-ab4b-bd6e-9d2487ae225d
* Content: [Prepare apps for mobile application management with Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/developer/apps-prepare-mobile-application-management#feedback)
* Content Source: [memdocs/intune/developer/apps-prepare-mobile-application-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/developer/apps-prepare-mobile-application-management.md)
* Service: **microsoft-intune**
* Sub-service: **developer**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by nandin-branchfire** [comment]
From what I understand LOB apps with the intune SDK will not work with "Require Approved Client App" since they will never be part of that list. However, per Microsoft, "Require App Protection Policy" will include LOB apps that have the intune SDK embedded. It also requires some manifest changes. I am not sure if Organistations will switch to "Require App Protection Policy"  instead of "Require Approved Client App" policy. The documentation does not make it clear that  "Require App Protection Policy"  will finally replace "Require Approved Client App" and is a more inclusive policy. I am looking for more clarity on these two conditional access policies.

**Comment by Coopem16** [comment]
@nandin-branchfire That is great. But if that is the case they need to update the documentation. 
https://docs.microsoft.com/en-us/mem/intune/developer/apps-prepare-mobile-application-management
It specifically mentions that The intune SDK supports "Require approved Client App." 
We now may have to rebuild our CA policies to include Require app protection.

**Comment by smithre4** [comment]
We updated the documentation and removed "Require approved client app". Thanks for catching this mistake.
