### ISSUE TITLE
URL Protocol

### ISSUE THREAD

**Issue by kuvinod7** [MicrosoftDocs/memdocs#1081]
[Enter feedback here]
It would be good if there are specific examples for some of the third party apps like google docs. Also a working example would also be easier.

There is no proper step by step documentation available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45847a38-a19c-f1b3-b050-6abfdc92ace7
* Version Independent ID: e69cf195-21c3-4bec-7b5d-d78808710b40
* Content: [Data transfer policy exceptions for apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies-exception)
* Content Source: [memdocs/intune/apps/app-protection-policies-exception.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies-exception.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
@kuvinod7 - Thanks for the feedback. I have put this on my list to create and add to the docs. In the mean time, if you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Because I have a work item to add a step-by-step example to the doc, I'm closing this GitHub issue. Thanks
