### ISSUE TITLE
This is very helpful, can you also include the last accessed date please? It will help us determine BHOs that haven't been used and properly decommission them e.g. Macromedia Shockwave Player.

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/memdocs#1120]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70192764-84f1-9854-1b3c-de18ffc6b39e
* Version Independent ID: 2e00a7a1-5c79-7d7b-9243-75b93184359d
* Content: [SMS_BrowserHelperObject Class - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/core/clients/client-classes/sms_browserhelperobject-client-wmi-class)
* Content Source: [memdocs/configmgr/develop/reference/core/clients/client-classes/sms_browserhelperobject-client-wmi-class.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/reference/core/clients/client-classes/sms_browserhelperobject-client-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The ConfigMgr SDK documentation hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality.

Your feedback sounds like it might be about a functional change to the product itself. If that's the case, I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by GeoSimos** [comment]
Thank you Aaron, here it is: [Extend Hardware Inventory class SMS_BrowserHelperObject to include last access date](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/42201661-extend-hardware-inventory-class-sms-browserhelpero)
Cheers!
