### ISSUE TITLE
installing the sccm client through group policy is hard

### ISSUE THREAD

**Issue by jszabo98** [MicrosoftDocs/memdocs#1125]
I think the group policy section needs more details.  Here's an example of the group policy setting 

Computer, Classic Administrative Templates (ADM), Configuration Manager
  Configure Configuration Manager Client Deployment Settings
    /mp:SMSMP01 SMSSITECODE=CODE

Since group policy software installs run when the computer boots, you'll likely need to wait for the network before starting using group policy:

Computer, System, Logon
  Always wait for the network at computer startup and logon

A great tip is to run rsop.msc and right click on the computer.  You can check the Error Information for Software Installation.  I got it from this youtube video:  https://www.youtube.com/watch?v=Jh-YTAvZSGg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aeb5c91-a34d-46e9-bcba-695f12081a28
* Version Independent ID: 69bc3a9d-9f52-6e0f-e884-69c706269999
* Content: [Deploy clients to Windows - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/deploy/deploy-clients-to-windows-computers)
* Content Source: [memdocs/configmgr/core/clients/deploy/deploy-clients-to-windows-computers.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/deploy/deploy-clients-to-windows-computers.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jszabo98, I'm sorry that you're having problems. It's been a long time since I've personally done this, but did it pretty regularly years ago. I don't think much has changed. We do link to the article that goes into more detail on how to install software via group policy. ConfigMgr just plugs into that process.

At this time I don't think we need to go into much more detail on this topic. It's not an area that we're going to invest in writing a lot of new, more prescriptive guidance.

There are a couple of other options that you might try to get more help with this topic:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
