### ISSUE TITLE
How to apply filters in Assets 

### ISSUE THREAD

**Issue by Navneet-Singh-Ghura** [MicrosoftDocs/memdocs#1131]
I do not see option to set filter for Type and Category Column 

![image](https://user-images.githubusercontent.com/64772740/102191834-f725a280-3edf-11eb-917c-ab1f53ce1c44.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a68f71de-63aa-0a66-2806-41a4eb675b79
* Version Independent ID: 85307a21-9a8f-8538-069e-f1d1ef100f10
* Content: [Assets in Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/about-assets#apps)
* Content Source: [memdocs/configmgr/desktop-analytics/about-assets.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/about-assets.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Navneet-Singh-Ghura for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by Navneet-Singh-Ghura** [comment]
I think document needs to be updated as its mentioned in this doc that we can apply filters, but there is no option for the same. 

Below snip from document which needs to be updated if we can not set filters for now. 

Use the Type and Category columns to manage these app categories:

For store apps, filter Type as Modern
For system apps, filter Category as Background process or Windows component

**Comment by aczechowski** [comment]
Ah, sorry, now I see the disconnect. Let me check with others to see if that was there at some point but is since removed.

**Comment by aczechowski** [comment]
One quick note: looks like the filters are enabled when you turn on **App version details**. Checking whether that's intentional or not.

**Comment by aczechowski** [comment]
Ok, I was making some changes in DA content today, so slipped this in. As noted above, you have to turn on app version details, then you can sort/filter on additional fields. Thanks again for the feedback!

This issue will auto close when my pull request merges. Then will go live with the next publishing cycle, which should be later this afternoon.

**Comment by Navneet-Singh-Ghura** [comment]
Great got it, I am able to apply filters now. Thanks.
