### ISSUE TITLE
Question about the specifics of assigning compliance policies

### ISSUE THREAD

**Issue by wiseleaf23** [MicrosoftDocs/memdocs#115]
At "Ways to deploy device compliance policies" (https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started#ways-to-deploy-device-compliance-policies), there is specified:

"On Windows 10 version 1803 and newer devices, it's recommended to deploy to device groups if the primary user didn't enroll the device."

Why is this? Are there any pro's/con's to assigning to a user instead of device or vice versa? By default, the only option you have in the drop down menu is "All users". Thanks in advance for elaborating :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c19b6ee-2218-cd97-96a4-2832c0302d7e
* Version Independent ID: da3ff20c-91cb-d760-708c-8e56af5d59d8
* Content: [Device compliance policies in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/device-compliance-get-started#ways-to-deploy-device-compliance-policies)
* Content Source: [memdocs/intune/protect/device-compliance-get-started.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/device-compliance-get-started.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by meisterheister** [comment]
Very good question. We are applying compliance policies to user groups and but now the device has been marked non-compliant when set another primary user after the device was enrolled. The user that this device has been enrolled with was marked non-compliant and as result the whole device is in that status. 
I guess that when assigning the policy to the device instead, it's not up to the single users.
The fact that this is relevant since Windows 1803 might be up to the fact that the "primary user" is a newer feature that was not supported on Windows versions before.

**Comment by Brenduns** [comment]
@wiseleaf23   cc @meisterheister.      Thanks for the question. The text you are asking about was added some time back to help address some *shared device* issues that were being observed. When the underlying issues were resolved in December there was no ask to docs to clean up the content. With the issues resoled, we'll be removing that text in an doc update in the next day or so, as its no longer relevant.  The text being removed is exactly the text you quoted when you opened this issue.
