### ISSUE TITLE
Install command ?

### ISSUE THREAD

**Issue by adrianplesa** [MicrosoftDocs/memdocs#1153]
The CCMSETUP is missing the AADTENANTID attribute, this will make the installation fail

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e279b-9029-d1e5-8a6c-0e93ce38ddba
* Version Independent ID: 80bc34d7-3ef7-1c4f-da41-0474b1c5f4a4
* Content: [Co-manage internet-based devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/how-to-prepare-win10)
* Content Source: [memdocs/configmgr/comanage/how-to-prepare-Win10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/how-to-prepare-Win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @adrianplesa, that parameter hasn't been a requirement since 2018, see [What's new in version 1806](https://docs.microsoft.com/mem/configmgr/core/plan-design/changes/whats-new-in-version-1806#simplified-client-bootstrap-command-line).

If you’re having problems, I suggest one of the following options to provide the best level of support:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
