### ISSUE TITLE
Question about compliance policy assignment

### ISSUE THREAD

**Issue by janeide75** [MicrosoftDocs/memdocs#1208]
I wish the documentation included some best practice or recommendations for how to assign device compliance policies. Should a policy be assigned to users or devices? 
Lets say you require the use of bitlocker. If you assign that to a user, you ensure compliance for the user no matter what device the user sign in to. If you assign the same policy to the device, you enusre compliance for any user that sign in to that device.
If the purpose of the policy is to protect user data from beeing stored on devices without encryption, the difference in assignment between users and devices may have significant impact on the outcome of the policy. If the example policy is assigned to a device, the user can still log to any other device outside the policy and by that store data on a device without bitlocker.

**Comment by Brenduns** [comment]
@janeide75  Thanks for your submission and thoughts on content. Those are great subjects, and not necessarily easily answered. Different management scenarios for different enterprise environments can benefit from different design plans – which makes this challenging. However, with that said, this isn’t the first time there have been asks to clarify or provide more insight for deploying various Intune policies to users vs devices. This general concept has been on our teams to-do list for some time though the need to keep content current to the evolving and changing product requires most of our focus.  

So that we capture this specific ask, I’ve created a tracking bug for this in my internal backlog of work. Each bit of feedback we receive adds to whole, which can help us prioritize our future work when bandwidth becomes available.  

With the internal bug for tracking this as future work, I’ll need to close this GitHub issue.  Thanks for taking the time to pass us your thoughts.
