### ISSUE TITLE
CMG Scale set setup trap

### ISSUE THREAD

**Issue by BorisKornienko** [MicrosoftDocs/memdocs#1217]
The process of CMG scale set config by the wizard has a problem. If the resource group has a different than CMG name then will be created all except scale set and, of course, CMG will state in error.
I don't know, what needs to be done either fix this in the product or mention this tip in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6481482-eaca-ebae-03fe-cb30faf35557
* Version Independent ID: a0c07347-329f-d59c-0f47-7618e7fdbb14
* Content: [Set up cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway#set-up-a-cmg)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BorisKornienko for taking the time to provide feedback on Configuration Manager! Since CMG as VM scale set is a pre-release feature, I'm confident it's a product issue. I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
