### ISSUE TITLE
Tenant Attach Prerequisties

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#1303]
[Enter feedback here]

Is the prerequisite "The Initiate Configuration Manager action permission under Remote tasks in the Microsoft Endpoint Manager admin center" still valid as I can find no way of setting this permission in the Endpoint Manager admin center. If so can we please provide instructions on where this setting is located.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@ajp999 I believe this is still a requirement since I haven't heard otherwise.  When you create a custom role in the admin console, you can see this under *the *Remote tasks** heading. 
![image](https://user-images.githubusercontent.com/33289333/107286954-1d664b00-6a16-11eb-9d99-5ba06821cf59.png)

I suspect it's already enabled on many of the built-in roles that are expected to take actions on clients. When checking a role, you'll see it listed under the same heading, like this for the School Administrator role. 
 
![image](https://user-images.githubusercontent.com/33289333/107287074-4981cc00-6a16-11eb-8667-2bc7f672ecb4.png)

I'll add a little tweak to the doc to add a little clarity on where to check this.

**Comment by mestew** [comment]
The doc should be updated in a day or so to add a link for more information about checking the permission.  Closing the issue.
