### ISSUE TITLE
Instructions on De-registering a device require revision - Motherboard/Deregister

### ISSUE THREAD

**Issue by bklotz-odu** [MicrosoftDocs/memdocs#1318]
The instructions for removing a device from InTune, Autopilot and Azure AD require revision.  

Under Deregister from Intune:

A device might be under multiple groups.  You can't remove it from the groups without going into AzureAD and looking under the device entry itself.  Either way, when you remove the device in Azure AD, it automatically removes it from the groups.

You can't delete a device without first removing it from Autopilot now.  This was a recent change in InTune/AzureAD

You can't delete a device from Azure AD through InTune, you have to do it through Azure AD.  I don't know when this change was made, but when you go into Devices in InTune, you don't have the option to remove the device from Azure AD.

We ran into an issue recently where the Azure AD entry was left behind by one of our technicians when all other steps were completed, causing me to review these instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/autopilot-mbr.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @bklotz-odu. I apologize for the long time it took to respond back to this feedback item. However, since you filed this feedback item we have done several updates to the documentation including several recent significant changes on how to specifically properly deregister a device. I am going to go ahead and close this feedback item. If you find any problems with the updated documentation or the updated documentation doesn't address your concerns, please fille a new feedback item.
