### ISSUE TITLE
Policy Error for using Company Portal on DEP without user affinity

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/memdocs#1342]
Using the example app config policy for allowing Company Portal on DEP devices without user affinity but every time the policy is pushed it gives an error "STATE Policy Error". There is no other information so I'm not sure if the policy XML is wrong or if it's something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee33d638-3024-87d5-1b02-c4568478d1ce
* Version Independent ID: fe0f2aa3-b2dc-486a-4883-9c25ee361fe8
* Content: [Add app configuration policies for managed iOS/iPadOS devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-ios#configure-the-company-portal-app-to-support-ios-and-ipados-devices-enrolled-with-automated-device-enrollment)
* Content Source: [memdocs/intune/apps/app-configuration-policies-use-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-configuration-policies-use-ios.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by MarcLaf** [comment]
Specifically I'm referring to the XML

```
<dict>
    <key>IntuneUDAUserlessDevice</key>
    <string>{{SIGNEDDEVICEID}}</string>
</dict>
```

**Comment by MarcLaf** [comment]
Any update on this?

**Comment by Erikre** [comment]
We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. If you have continue to have questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

This question is in our documentation feedback channel and it may be best to handle this question as a support request. For this reason, I'm closing this issue. However, if I'm able to find any additional information after checking with the product team, I will update the docs. Please use the above channels if you don't already have a solution.

**Comment by Erikre** [comment]
@MarcLaf - I have additional information from the product team:
This happens because unlike other app configs, this one does not apply every time the device checks in. Instead, this app config is meant to be a one-time operation to enable existing devices enrolled without user affinity to attain user affinity when a user signs in to Company Portal. This app config is removed from the policy in the background once it has successfully applied. The policy assignment will exist but it will not report "success" once the app config is removed in the background. We recommend that you unassign this policy once it has applied to the device.

I also plan to update the docs with the above information. Thanks

**Comment by MarcLaf** [comment]
Thank you for the clarification Erik, good to know I didn't make a mistake!
