### ISSUE TITLE
IKEv2 Encryption algorithms AES-128-GCM or AES-256-GCM do not apply

### ISSUE THREAD

**Issue by chris-dma** [MicrosoftDocs/memdocs#1354]
The encryption options for IKEv2 do not seem to apply properly to iOS devices. If you specify AES-128-GCM or AES-256-GCM in an Intune Configuration Profile for iOS > VPN > IKEv2 and apply it to a device (iPhone 12 iOS 14.4) then attempt to connect, a network trace on the VPN server shows that the Apple device is still offering only the default encryption algorithm AES-256 (CBC). 

This seems to be an issue with Intune itself because creating an Intune Configuration Profile using iOS > Custom and manually creating an Apple Configuration Profile for the VPN configuration specifying AES-128-GCM or AES-256-GCM does work as expected. I.e. a network trace shows that the Apple device is then offering AES-128-GCM or AES-256-GCM for the encryption algorithm. 

I know this is not a documentation issue but I have no idea how to actually bring this to Microsoft's attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4e2ec1-b0f9-aee4-e7df-eed9ab445091
* Version Independent ID: bff2d59c-7fe4-fca0-60ad-d39438fe8f27
* Content: [Configure VPN settings to iOS/iPadOS devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/configuration/vpn-settings-ios)
* Content Source: [memdocs/intune/configuration/vpn-settings-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/configuration/vpn-settings-ios.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by MandiOhlinger** [comment]
@chris-dma Thank you! Yes - this is a bug, and engineering is aware. It will be fixed in a future release; No ETA. We added a note to the article stating that it's a known issue. Hopefully, the doc changes will be live this week.

As for bringing to MSFT attention, there are two options:

1. If you want help, or possible work arounds, then opening a support case is the correct route. For more info, see [get support for Microsoft Intune](https://docs.microsoft.com/mem/get-support).
2. If you want to report it, then use [Uservoice](https://microsoftintune.uservoice.com/forums/291681-ideas).
