### ISSUE TITLE
Additional Information Requested re: Installation on Domain Controllers

### ISSUE THREAD

**Issue by joacole** [MicrosoftDocs/memdocs#1374]
Could you please add Microsoft's official recommendation about the relative safety or security exposure that installation of the Intune Connector for Active Directory poses?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9439232

**Comment by frankroj** [comment]
Thank you for the feedback @joacole. I apologize for the long time it took to respond back to this feedback item. At this time we really don't have anything additional to share regarding installing the Intune connector on a DC. The main point is that it uses the computer account of the DC to add objects to AD. Clients will also communicate with the DC to get added to AD, but this isn't anything that already happens through normal domain joins outside of the Intune connector and it uses the same ports. Basically we aren't documenting anything additional because there isn't really anything more to share. I hope this answers your question.
