### ISSUE TITLE
PowerBI Report Server - IFrame or Report Viewer Control

### ISSUE THREAD

**Issue by DavidWynnII** [MicrosoftDocs/memdocs#1376]
When using an Asp.net application, used for managing data access in a multitenant environment by rendering PowerBI Report Server reports, displaying PowerBI reports using an IFrame always requires AD authentication and will not use the Asp.net identity framework for user access.  Normally the report viewer control will handle authentication and authorization behind the scenes on the webserver when making a request to run a report on PowerBI Report Server.  However, though the report viewer control renders SSRS paginated reports, the control will not render PowerBI dashboards/reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb13fff2-41ef-fa3d-4685-7b5b17c6b2a7
* Version Independent ID: 7e541e95-40de-b779-dd3e-b03f5fb5b911
* Content: [Integrate with Power BI Report Server - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/manage/powerbi-report-server#feedback)
* Content Source: [memdocs/configmgr/core/servers/manage/powerbi-report-server.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/manage/powerbi-report-server.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavidWynnII for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
