### ISSUE TITLE
Can you add clarity...Connect Before Login

### ISSUE THREAD

**Issue by dadouginc** [MicrosoftDocs/memdocs#1449]
In the statement "can be deployed with Intune and lets the user manually establish a VPN connection from the Windows logon screen", can you add a NOTE or clarify that the connection BEFORE user login. Something like "can be deployed with Intune and lets the user manually establish a VPN connection from the Windows logon screen prior to login (aka VPN Before Login),"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57c9838-1004-157d-e0b1-363e770c7246
* Version Independent ID: 4fa6f34f-9438-9748-712c-c949eb22863d
* Content: [Windows Autopilot User-Driven Mode](https://docs.microsoft.com/en-us/mem/autopilot/user-driven)
* Content Source: [memdocs/autopilot/user-driven.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/user-driven.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @dadouginc . I apologize for the time it took to get back to you regarding this feedback item. Unfortunately I can't add such a statement because different VPN solutions may work differently. For example, some VPN solutions may automatically connect. Also, once the user logs in, they are no longer at the logon screen. The doc states they need to do it from the logon screen, and logging in would take them away from the logon screen. Stating that they need to do it before logon would be a bit redundant.
