### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by kuvinod7** [MicrosoftDocs/memdocs#1504]
[Enter feedback here]

these page really confuses. as the name suggest "Configure client authentication for cloud management gateway" - We see there are lot of other topics in the same page. It should be linked to different set of page. For setting up please document what has to be done in easy and simple way

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 487b0a14-24a7-c5dc-9350-cde232264ea0
* Version Independent ID: 61c19523-86f3-e983-6021-cd3a1267f4be
* Content: [Configure CMG client authentication - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/configure-authentication#bkmk_mphttps)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/configure-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/configure-authentication.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @kuvinod7, I'm sorry you're having trouble. I revised the CMG content in September 2020 specifically to simplify and clarify the end to end process. I suggest starting with the Overview or Plan for CMG article and then progress from there.

This article covers the three options for client auth: Azure AD, PKI, or token. And then the required MP configurations based on the client auth choice.

If you can provide some specific suggestions on how to further clarify, please let me know. Otherwise I suggest one of the following options for additional assistance:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
