### ISSUE TITLE
DEM enrollment and Conditional Access

### ISSUE THREAD

**Issue by v-rechau** [MicrosoftDocs/memdocs#1511]
I noticed that the following statement was clarified a few months ago:

- Devices are blocked for Conditional Access with the exception of Windows 10 1803 or later

Was changed to: 

+ On Windows 10 1709 and older, conditional access isn't available for Windows devices enrolled using bulk enrollment.

Now, it was my understanding that this meant that iOS, macOS, Android and Windows devices enrolled with a DEM account would be blocked from Conditional Access _unless_ it was running Windows 10 1803+

The "updated" text only mentions Windows now. Does this means that Conditional Access is not blocked for iOS/Android devices enrolled with a DEM account now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
9748872

**Comment by lenewsad** [comment]
Hi @v-rechau, thanks for reaching out to the Intune Docs team for clarification about that part in the doc. We have since updated the doc to clarify that the DEM/conditional access limitation applies to all platforms, and that's because conditional access is meant for user-targeted scenarios and DEM is device-targeted. Looks like we missed following-up with you so wanted to do that before closing this issue. 

FYI @yogkumgit
