### ISSUE TITLE
Please update Colum info of Capabilities by enrollment method 

### ISSUE THREAD

**Issue by sufuruka** [MicrosoftDocs/memdocs#1513]
Could you please modify the Colum of "Capabilities by enrollment method"?
https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-method-capab#capabilities-by-enrollment-method

Capabilities of "Device can assess resources protected by CA" describes that DEM is not supported. But DEM can use CA Win10 1803+.  So could you please modify the check mark? Or, if this capabilities means another info, please let me know. 
![image](https://user-images.githubusercontent.com/57698840/114477072-8a74a780-9c36-11eb-9bbf-9ea34aade2b8.png)

**Comment by ErikjeMS** [comment]
Investigating with PM...
9748710

**Comment by lenewsad** [comment]
Hi @sufuruka, thank you for opening this issue with the Microsoft Intune Docs team. We've made significant changes to the documentation since this issue was opened.  Now you can find information about each of the enrollment methods in [Enrollment guide: Enroll Windows client devices in Microsoft Intune](https://learn.microsoft.com/mem/intune/fundamentals/deployment-guide-enrollment-windows). You are correct that conditional access is supported when using a DEM on devices running Windows 10, 1803+, and Windows 11.  For more information about DEM, see [Add device enrollment managers](https://learn.microsoft.com/mem/intune/enrollment/device-enrollment-manager-enroll).  I am closing this issue as no further doc changes are needed.
