### ISSUE TITLE
About edundancy and load balancing support for PFX Certificate Connector

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#1524]
Please specify that the PFX Certificate Connector supports redundancy and load balancing at the same level as MICC.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1f825c-828e-39cd-6ebd-b428e18cd015
* Version Independent ID: 5d0074a0-e449-f459-f0b8-7b556ebea809
* Content: [Certificate connectors for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/certificate-connectors#pfx-certificate-connector-for-microsoft-intune)
* Content Source: [memdocs/intune/protect/certificate-connectors.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificate-connectors.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@usvjosh   Thanks for this question. I’ve worked with our product group to tease out some answers. 

The Tunnel app (and use of Microsoft Defender for Endpoint as the tunnel app, which remains in preview) don’t directly support the functions you’re asking about. However, Conditional Access does manage these behaviors for the Tunnel apps just as it would for any other app covered by a Conditional Access policy. As such, while these questions are best addressed by our Azure Active Directory teams, the following may be of use to get you pointed in the right direction: 

**MFA**: As per other apps, Conditional Access policy manages the MFA request independent of the app in the policy. If the Conditional Access policy requires MFA, then the user would be prompted to authenticate prior to Conditional Access approving the use of the tunnel. 

**Session timeout**: Session timeout is linked to the token lifetime. You would adjust the token lifetime in Azure AD to adjust the session length. 

**Re-prompt a user to authenticate after x number of days:**  Our engineering team doesn’t believe Azure AD supports this with single sign on (SSO). Instead, the silent token flow will always try to refresh the token silently instead of prompting the user for credentials.  

**User password change:** The engineer feedback is they believe that Azure AD supports revoking refresh tokens on password reset. With that set, once the active auth token expires, the user would be prompted to reauthenticate

**Comment by Brenduns** [comment]
@buhibu9  Thanks for this feedback. Our product team was able to confirm tht the redundancy is the same as for the Intune Certificate Connector. Later today, the docs will to reflect that.
