### ISSUE TITLE
Conditional Access and MFA

### ISSUE THREAD

**Issue by usvjosh** [MicrosoftDocs/memdocs#1542]
Hello, I have a few questions on the CA rules for the tunnel app.

Is it possible to prompt for MFA in the Microsoft tunnel app? 
Can a session timeout be set?
Can the user be re-prompted to authenticate every so many days?
What happens to the connection if a user were to change their password?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d63aaa4-b32f-5ac0-6fd4-85fa9322b811
* Version Independent ID: 051eeee2-4aaf-38e7-8ff6-a0624a4f6855
* Content: [Use the Microsoft Tunnel VPN gateway with Conditional Access policies - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-conditional-access)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-conditional-access.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-conditional-access.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@usvjosh   Thanks for this question. I’ve worked with our product group to tease out some answers. 

The Tunnel app (and use of Microsoft Defender for Endpoint as the tunnel app, which remains in preview) don’t directly support the functions you’re asking about. However, Conditional Access does manage these behaviors for the Tunnel apps just as it would for any other app covered by a Conditional Access policy. As such, while these questions are best addressed by our Azure Active Directory teams, the following may be of use to get you pointed in the right direction: 

**MFA**: As per other apps, Conditional Access policy manages the MFA request independent of the app in the policy. If the Conditional Access policy requires MFA, then the user would be prompted to authenticate prior to Conditional Access approving the use of the tunnel. 

**Session timeout**: Session timeout is linked to the token lifetime. You would adjust the token lifetime in Azure AD to adjust the session length. 

**Re-prompt a user to authenticate after x number of days:**  Our engineering team doesn’t believe Azure AD supports this with single sign on (SSO). Instead, the silent token flow will always try to refresh the token silently instead of prompting the user for credentials.  

**User password change:** The engineer feedback is they believe that Azure AD supports revoking refresh tokens on password reset. With that set, once the active auth token expires, the user would be prompted to reauthenticate
