### ISSUE TITLE
EHHTP how does it work and what are the benefits for no cloud attached SCCM

### ISSUE THREAD

**Issue by TonyITA** [MicrosoftDocs/memdocs#1545]
I am still very unclear as to what Enhanced HTTP will be used for.

You mention
•	Sensitive client communication
•	Securely access content from distribution points without the need for a network access account and Windows authentication

We do not have any workgroup or Azure AD-joined clients so what are the benefits \ changes for customers that only have clients on the internal network \ intranet?

We also do not use any of the features mentioned in the Features section.

So what are the benefits for us why depreciate HTTP?

If we enable EHTTP 
- What are the benefits?
- What changes – how do the internal clients communicate with management points and distribution points? – With Content access tokens?
- Must we also disable the option on the distribution points Allow clients to connect anonymously – is this a pre-requisite - if we enable EHTTP will it disable this automatically and does it disable this on the DP IIS website.
- The pre-requisites state Azure AD joined for cloud management and Windows 10 and above (we are not Azure joined with no CMG and we still have some Windows 7) – can we still enable EHTTP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac80195f-d429-0ffd-2a32-fb23e57c6697
* Version Independent ID: c4e06cf7-5c50-8fb4-d8b9-ecce874f118b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/enhanced-http)
* Content Source: [memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @TonyITA, thanks for the feedback, good questions. With the 2103 announcement of HTTP deprecation, we’re getting more questions about E-HTTP, so probably warrants some additional information. I already have plans to revise the doc soon to add some more info. Like maybe a FAQ, and most likely a diagram. I'll use this issue to track that works.

A few points to help answer your questions:
- You technically don’t need AAD onboarding to enable E-HTTP. (I just learned this yesterday!) At the time it came out and we wrote the doc, the AAD scenarios were the highlights. But you can do EHTTP without AAD. It then supports admin service and reduction of need for NAA. You only need AAD when one of the supporting features requires it. NOTE: even if you don't directly use the admin service REST API, many newer ConfigMgr features natively use it, including parts of the ConfigMgr console.
- The article is accurate in terms of the current scenarios that E-HTTP protects client communication. In other words, it’s not everything…yet. 😉 
- For an environment like yours, the main benefit is to not have pure HTTP, which is an insecure protocol. That's why we have E-HTTP and deprecated HTTP. We strive to be secure by default, and want to make it easy for you to keep your devices secure. Going full HTTPS is the most secure, but we know that it's complex for many customers. If you can't do HTTPS, then enable E-HTTP. Then you'll be able to update to future versions where HTTP is no longer supported.
- When you enable E-HTTP, the site issues certificates to each site system, so that they can support secure communication in currently supported scenarios. From a client perspective, the MP issues each client a token, which it uses to secure communication with the site systems. That behavior is OS version agnostic.
- I don't think there's any overlap between E-HTTP and the DP setting for anonymous access. But I'll look into it.

**Comment by TonyITA** [comment]
Additionally


·         For Bit Locker, we have also HTTPS-enable the IIS website on the management point that hosts the recovery service that is the MBAM virtual directory, but not the entire management point role.
Therefore, all our management points already have a PKI certificate issued from our certificate authority bound to port 443 on the management points IIS default website.

My question is what happens to the PKI certificate that we have already bound to the management points on port 443


·         Is it removed and if so will this break bit locker?  - Apparently it is not.

·         Will Enhanced HTTP be enabled if a PKI certificate is already in place?
As the SMS Role SSL Certificate will not be used.

·         I see from version 2103 BitLocker will work with Enhanced HTTP
From: https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data-transit#https-certificate-requirements


Thanks Tony

**Comment by aczechowski** [comment]
Hi @TonyITA, good question. The E-HTTP article already mentions in the note at the top of the article: 

> If you're already using PKI, the PKI cert bound in IIS will be used even if enhanced HTTP is turned on.

That applies to BitLocker as well. But worth mentioning in the BitLocker content to be explicit.
