### ISSUE TITLE
corrections: /InstallDir option and /AdminUI documentation

### ISSUE THREAD

**Issue by scottcopus** [MicrosoftDocs/memdocs#1550]
[Enter feedback here]

1. All three instances of the InstallDir option need to be prefixed with a slash (--> /InstallDir).  
Note to developers:  This option is missing from the embedded help within "prereqchk.exe"!

2. Please update the documentation for the "/AdminUI" option:
Currently reads: "Required. Verifies that the local computer meets the requirements for installing Configuration Manager."
Probably needs to read: "Required. Verifies that the local computer meets the requirements for installing ***the*** Configuration Manager ***console only.  It does not verify any server requirements***."
There are LOTS of misleading articles/blogs making users believe this checks for all requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9839439a-7e6c-1067-6004-4dbd97f90593
* Version Independent ID: f8d61a3f-a22c-caa7-c796-570f3adbd437
* Content: [Prerequisite checker - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/install/prerequisite-checker#feedback)
* Content Source: [memdocs/configmgr/core/servers/deploy/install/prerequisite-checker.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/install/prerequisite-checker.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by scottcopus** [comment]
Why was this closed? I don't see any changes to the live docs or any other feedback.

**Comment by jborsecnik** [comment]
The issue was closed automatically, apparently because of a linked PR merge. This repo may have not yet merged to live since that event. For more info, you might ask you might ask on the [Docs Support channel in Teams](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fteam%2F19%253a7ecffca1166a4a3986fed528cf0870ee%2540thread.skype%2Fconversations%3FgroupId%3Dde9ddba4-2574-4830-87ed-41668c07a1ca%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=02%7C01%7Cjuergen.thomas%40microsoft.com%7Cf41da9885021429c729108d7b10e6080%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637172547615392069&sdata=ELHpaYu%2BVyb%2FhWGncljU7iF3yHt05mkiwP5xbr48sLc%3D&reserved=0>)

See also: https://review.docs.microsoft.com/en-us/content-production-service/topics/pubdesk-documentation/pubdesk-internal/topics/ops-publishing-schedule?branch=master.

**Comment by jborsecnik** [comment]
I'm on the PR review team, and we don't normally work with issues, btw, so my info is limited.

**Comment by aczechowski** [comment]
@scottcopus sorry for not commenting sooner. Thanks for the feedback, I revised this article yesterday. Once the changes are checked in and the pull request merges, the issue closes. Our content publishes live twice a day in the morning and afternoon (Pacific time). So refresh this page in 30-40 minutes (or just round up to 11am Pacific) to see the update.

**Comment by scottcopus** [comment]
Ok gotcha, good to know. Is there a good way to make this something someone would know ahead of time? Thx!

**Comment by aczechowski** [comment]
Sometimes I'll mention it when working on an issue, obviously didn't this time 😄 It would be nice if the docs.ms platform itself would include that sort of comment, but it doesn't.

**Comment by aczechowski** [comment]
p.p.s. I refactored the article quite a bit, I don't know the last time it had any TLC. 😬 Let me know if you have any further feedback! Thanks

**Comment by scottcopus** [comment]
Looks great! Thx!
