### ISSUE TITLE
Alternative for HTTPS warning - Just make EHTTP the default

### ISSUE THREAD

**Issue by djl999** [MicrosoftDocs/memdocs#1572]
Just a suggestion, as an alternative to presenting a warning for HTTPS and potentially causing confusion, Enhanced HTTP could be enabled by default and there would be no need for warnings or prompts. There is no reason I know of that EHTTP shouldn't be enabled by default for all environments, and if the user wanted to use HTTPS they could still do so in the console after initial setup or upgrade is complete. I do not think the warnings or options for HTTPS belong in the initial setup wizard because this is not a setting to be taken lightly, but being presented these choices up front is forcing users to make a snap decision that can impact their environment without them having the chance to fully understand the consequences.

Thanks

**Comment by aczechowski** [comment]
Thanks @djl999 for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
