### ISSUE TITLE
Clarification on deprecation of Resource access policies

### ISSUE THREAD

**Issue by MrRoundRobin** [MicrosoftDocs/memdocs#1611]
Hi,

regarding this notice 
`Starting in Configuration Manager version 2103, these company resource access features of Configuration Manager and this co-management workload are deprecated. Use Microsoft Intune to deploy resource access profiles.`

May be this can be clearer. Me and my customer struggled if the removal of that feature and the corresponding removal of the co management slider just means that you can't configure the slider anymore or if it's completely not possible using co-management.

there is also a reference here https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures#deprecated-features which meight be unclear as well

what do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03000b95-a54a-d55c-6ea6-9202de578371
* Version Independent ID: 3982a621-fd4b-d20a-6e2a-d600597f0cf8
* Content: [Co-management workloads - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/workloads#resource-access-policies)
* Content Source: [memdocs/configmgr/comanage/workloads.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/workloads.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
When the feature is removed from the product (expected early 2022) then in a co-management scenario, ConfigMgr no longer supports that workload. So there's no slider that applies to that workload. To continue to manage the workload, the device needs to be co-managed, and policies applied from Intune. Co-management is a policy to the device as to which management authority controls the workload. Since ConfigMgr won't have that workload after March 2022, the only available management authority is Intune.
