### ISSUE TITLE
Downloading all languages makes this way too slow and large.

### ISSUE THREAD

**Issue by kcobbva** [MicrosoftDocs/memdocs#1626]
[Enter feedback here]
This product should respect WSUS language preferences.   "Content will be downloaded for all Microsoft 365 Apps languages", makes this download take so long to complete it's probably easier and quicker to redeploy the product rather than download.  WSUS downloads are way faster respecting options configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb3eb96d-3e56-39ac-99b8-c0c6eb01b7a6
* Version Independent ID: d9cc7d86-a4be-05bb-96b1-deac0695db44
* Content: [Synchronize Microsoft 365 Apps updates with no Internet connection - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/synchronize-office-updates-disconnected)
* Content Source: [memdocs/configmgr/sum/get-started/synchronize-office-updates-disconnected.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/get-started/synchronize-office-updates-disconnected.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @kcobbva for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
