### ISSUE TITLE
Endpoint or DeviceManagement?

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/memdocs#1631]
[Enter feedback here]
What a confusion for beginners. Instead of getting in love with it, you start to hate it. Both of these links below are the same!

https://devicemanagement.portal.azure.com/#home
https://endpoint.microsoft.com/#home

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ac7797-73f0-5b5b-f1b6-3769b7dd9882
* Version Independent ID: 86d0dee7-5bfa-2bf2-3b4c-ed0ee1379b68
* Content: [How to create deployment plans - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/create-deployment-plans)
* Content Source: [memdocs/configmgr/desktop-analytics/create-deployment-plans.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/desktop-analytics/create-deployment-plans.md)
* Product: **configuration-manager**
* Technology: **configmgr-analytics**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Anoni-Mouse, I'm sorry that you're having problems. Can you help me understand the relationship between your comment at the referenced article on [How to create deployment plans](https://docs.microsoft.com/mem/configmgr/desktop-analytics/create-deployment-plans) in Desktop Analytics? The article doesn't currently reference either of those links.

In general, those links are just aliases for the same thing, the Microsoft Endpoint Manager admin center. For example, `nslookup` for both names, and you'll see it's the same IP address with those aliases.

We have other articles that do refer to `endpoint.microsoft.com` as the link to use, but I didn't find any reference in the MEM content to the first link.

**Comment by Anoni-Mouse** [comment]
Hello
The thing is, all those names are really confusing for beginners. I'm on my first steps and viewing the documentation to get certified. Hence I consult the online docs trying to learn and get help. So I'm not familiar with the various websites. They could have the same IP as you mentioned, but that doesn't help unfortunately. A documentation should be clear and razor sharp for beginners like me. If you say, for example, open the Security and Compliance website, I expect a link for security and compliance, not just mentioning a name. Too many names and acronyms without links in most of the documentations creates frustration for beginners

Thanks
________________________________

**Comment by aczechowski** [comment]
Great to hear that you're working to learn and get certified. 😄 

Looking a little more closely, I see that the link in this article to the **Desktop Analytics portal** uses the friendly URL `https://aka.ms/desktopanalytics` which redirects to `devicemanagement.portal.azure.com` and the specific area for Desktop Analytics. Sorry for not picking that up earlier.

I think the short answer here is to not worry about the URL names, regarding your original concern for the links with different names going to the same place. We're working to consolidate functionality into the MEM admin center for the persona of an IT admin that manages devices. So it shouldn't matter to you what the URL is, as long as the link gets you to the right place based on its context. In this example, the first step to create a deployment plan is to go to the Desktop Analytics portal. That link takes you to that portal.

If that link doesn't direct you to a functional Desktop Analytics portal, then it's probably not set up for your account. The "how-to guides" are procedural articles that show you how to complete a task. Often times they are sequential, as is the case here. So you need to at least first [Set up Desktop Analytics](https://docs.microsoft.com/mem/configmgr/desktop-analytics/set-up) before you can create a deployment plan.

In general for overall learning, I suggest starting with topics towards the top of an area's table of contents instead of jumping directly into a how-to guide. These articles at the top are typically overview or introductory articles. There are sometimes also tutorials to walk through the basic scenario. Articles further down the table of contents, such as how-to guides, will assume a certain level of understanding of the topic, which should be introduced in earlier articles.

I'm going to close this issue, because I don't think there's anything actionable for change in this specific doc. Let me know if I can help clarify further.
