### ISSUE TITLE
Can we add a note that states you need to have the keyboard setting set to "No"

### ISSUE THREAD

**Issue by netlander1** [MicrosoftDocs/memdocs#1648]
Pre-provisioning will "fail" if "automatically configure keyboard" is set to "yes"

It completely skips the OOBE screen and goes directly to the windows login screen, not allowing you to press the Win Key 5 times.

It took a couple hours of searching to find this.

https://oofhours.com/2020/02/03/configure-language-settings-for-any-scenario/

Can the documentation be updated to include a screenshot of it set to "no"? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @netlander1. I apologize for the time it took to get back to you regarding this feedback item. Since you filed this feedback item, this issue has been resolved and should work in the latest versions of Windows 10 22H2 and Windows 11 22H2. You shouldn't need to set **Automatically configure keyboard** to **No** for it to work. I have personally tested this configuration and can confirm I can hit the Windows key 5 times when the device first boots up. If you are finding you are having the problems with older but still supported version of Windows, please let me know.
