### ISSUE TITLE
"Cannot find type [ExcelFormat]" error message when running Export-FirewallRules.ps1

### ISSUE THREAD

**Issue by jturgeon79** [MicrosoftDocs/memdocs#1698]
When running the Export-FirewallRules.ps1 script on a reference machine, after downloading and installing the required modules and prompting for a Profile name, the script produces the error message "Cannot find type [ExcelFormat]: verify that the assembly containing this type is loaded.", followed by the output "No commands completed".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffd4704-acbf-a7e8-073f-7b0de922dcd8
* Version Independent ID: 39cc8624-ede4-2ec9-ea79-607347e5d17d
* Content: [Endpoint security firewall rule migration tool for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-rule-tool)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-rule-tool.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-firewall-rule-tool.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jturgeon79  I’ve run this error past our engineering team for this feature and script, and this type of error isn’t known to them. Because this isn’t known, and the script has been successful without this type of error before, we’ll need to recommend you [open a support issue](https://docs.microsoft.com/mem/get-support) to investigate this, as we can’t provide troubleshooting through this doc feedback venue.

However, before opening a support issue, I suggest looking into the PowerShell version that’s in use to ensure its current. While we don’t have data on the minimum version of PowerShell for the firewall script, I offer this suggestion based on a GitHub issue for an Excel Import issue that had a similarly structured error message involving an older PowerShell version.  See this [Excel GitHub issue](https://github.com/dfinke/ImportExcel/issues/466) for this reference. It’s from 2018 and is the only instance I was able to uncover that was similar.

**Comment by Brenduns** [comment]
@jturgeon79  I've an update for you, which will be turned into content sometime soon.  The dev's kept digging and confirmed that the tool was tested on **Windows 10 1903** (and will support that and later), and with **PowerShell Version 5.1.18362.145**.   Also noted is there is an expectation in the scripts is that the **ExcelFormat** type be available in the PS environment.   Hopefully that will help you get that sorted.  If those criteria are all met, then again, support should be able to help puzzle out what's going on for your environement.

**Comment by jturgeon79** [comment]
Thanks for the updates @Brenduns. I'm running PSVersion 5.1.19041.1023 on Windows 10 21H1. I'll go ahead and submit a support request.

I've found that there was a recent commit (8 days ago) on ExportTo-ExcelFile.ps1 in Intune-PowerShell-Management... I wonder if it may be related? [https://github.com/microsoft/Intune-PowerShell-Management/tree/master/Scenario%20Modules/IntuneFirewallRulesMigration/IntuneFirewallRulesMigration/Public]

**Comment by jturgeon79** [comment]
@Brenduns, in case you or the dev's you spoke with are curious, I believe I've confirmed that problem isn't with the Intune Firewall Migration Tool scripts, per se - other than some poor error handling producing very misleading error output.

I've submitted a Premier Support case to confirm, but I believe the problem is actually related to some bad input validation logic in the Intune service itself... When adding a firewall rule in the portal, it won't accept a remote address range that uses a subnet mask of 255.255.255.100 or greater. And it just so happens that one of the firewall rules in my domain GPO that I'm trying to migrate uses a mask of 255.255.255.192.

So when I run the migration tool, it logs a BadRequest http response in C:\Windows\System32\Logs when it tries to POST to MSGraph, which then somehow results in the [ExcelFormat] type error.

Hopefully the devs can fix the data validation rules in the Intune service, so that I don't have to go through our change control process to modify the existing GPO just so that I can migrate it.
