### ISSUE TITLE
IBCM Unsupported Features

### ISSUE THREAD

**Issue by Hoorge** [MicrosoftDocs/memdocs#176]
[Enter feedback here]
"Software deployment to users. This feature relies upon the application catalog, which is deprecated."

- Software deployment to Internet based clients works and very much possible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0894e83-ae5e-960f-169c-cb5ea0e85a10
* Version Independent ID: 2a3ad459-44e9-7fe1-f2b9-a6b8ad58afa9
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/plan-internet-based-client-management)
* Content Source: [memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Hoorge, I just changed that yesterday based on #142. If you have an older version of ConfigMgr with an app catalog, then it technically could work. But since the app catalog is out of support as of version 1910, I decided to just change that statement. Note, it's specifically software deployment to *users*. Software deployment to devices will work ok. But for IBCM, user auth relies on the app catalog. If you need user-targeted apps for remote users, you need to use CMG and Azure AD.

**Comment by Hoorge** [comment]
Aaron, Thanks for the explanation. That makes sense. I don't deploy apps to users, only to devices.
