### ISSUE TITLE
CSP link destination of [Local admin account] is different

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#179]
Isn't the link destination [Accounts_LimitLocalAccountUseOfBlankPasswordsToConsoleLogonOnly] and not [Accounts_EnableAdministratorAccountStatus]?

But, [Accounts_EnableAdministratorAccountStatus] does not exist on Localpolicies Securityoptions CSP Docs, so is it necessary to create this new one?

https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2a095c-452e-c494-a013-0626b9f3728d
* Version Independent ID: a4787d69-187f-fe55-d071-3a37b9b082e9
* Content: [Protection settings for Windows 10 devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#feedback)
* Content Source: [memdocs/intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@buhibu9  Thanks for spotting a bad link. I've asked the engineering team to confirm what the setting should point to.  I suspect this is a case of the FWLINK having been edited incorrectly.  The content still lists the CSP that this link previously pointed to.   It's because the current link destination doesn't exist in the Windows CSP content that I suspect this is a modified FWLINK for the setting.  Once we have it sorted we'll get the FWLINK to point to the correct CSP, and I'll update you here.

**Comment by Brenduns** [comment]
@buhibu9 The FWLINK has been updated, back to the expected destination.

**Comment by buhibu9** [comment]
@Brenduns 
Thank you for your response.
