### ISSUE TITLE
Device evaluated as non-compliant not clear

### ISSUE THREAD

**Issue by vTa47** [MicrosoftDocs/memdocs#1799]
About this : "With this action, when the device checks-in, the device is evaluated as non-compliant immediately."
The device is evaluated as non-compliant immediately at the very first check-in in Intune or each time the device check-in (means everyday?) ?

Please specify this.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7ac08-bfd6-9560-ad25-bced9b944822
* Version Independent ID: 6b1f70f0-aed3-52ac-25eb-1de55babc9d0
* Content: [Noncompliant message and actions with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/actions-for-noncompliance)
* Content Source: [memdocs/intune/protect/actions-for-noncompliance.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/actions-for-noncompliance.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@vTa47  Thanks for the question.  Would the following revision be more clear? 

- _With this action, when the device checks-in with Intune and evaluates the policy, if it is not compliant to that policy Intune immediately marks that device as noncompliant. If the client checks-in at a later time after remediating the issues that lead to noncompliance, it status will update to its new compliance status._  

If that's more clear, I'll revise the docs, and also do a bit more work on that entire paragraph.  It's old and can be improved upon!

What is happening with the process is that the device must evalute the policy and return its status. If its not compliant, Intune marks it as such at that time - and that status remians until such time as a new evaluation runs for which the device then reports it is compliant (such as after the issue is remediated).

**Comment by vTa47** [comment]
Hi @Brenduns ,
This is now more clear yes. Thank you for your reply.
Cheers,

**Comment by Brenduns** [comment]
@vTa47  Thanks for confirming that. The documentation should recieve that update either later today, or tommorow.
