### ISSUE TITLE
What is One Level?

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/memdocs#1805]
https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client#bkmk_adquery

In the section above, 'One Level' is noted as not used in this version of Configuration Manager. Is there a specific version where this is used and what would be a scenario where this was needed? I'm guessing One Level limits the LDAP query to the base plus one level down?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb2976-54e8-e5d1-1833-bc7141836a72
* Version Independent ID: 3f006ea9-52d9-cddf-4d78-b06e7d31ea5e
* Content: [Create custom configuration items - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client)
* Content Source: [memdocs/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jpcast88, that wording has been in our content since at least 2012 R2: https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-r2/gg712331(v=technet.10)#to-create-a-setting (the formatting is messed up on that page, but you can still see the same text).

So I think it's safe to say that setting hasn't been used for a long time. If the UI is still there, then I'm ok leaving this statement. If the UI isn't there, then we could remove this line. Either way, I'm not really passionate about it. I'm going to close this issue. If you want to submit a PR to make some change, go for it! 😄
