### ISSUE TITLE
Table of settings and values with each release

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/memdocs#181]
Can you please start maintaining a table that displays the different settings and values for each release and new/removed settings, much like they do when they release new GPO security baselines? It would make it a lot easier for the customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ff4382-415c-4e80-e958-3bd77252fe2d
* Version Independent ID: 398a5b4b-e8bd-1f7d-ae30-38d812daf90d
* Content: [Intune security baselines settings for Microsoft Defender Advanced Threat Protection - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp)
* Content Source: [memdocs/intune/protect/security-baseline-settings-defender-atp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-defender-atp.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@sveinungre   Thanks for the feedback in this and related Issue.  

To understand what's changed with a new version of a baseline you already use,  please use Intune’s built-in method for identifying those differences, the **Compare Versions** action.  This is documented in the Security Baselines main article, documented but not terribly visible. That lack of visibility will soon be fixed with a content update.  

**To identify the changes in a new version of a baseline,** select the security baseline, like the ATP baseline. Next, select **Versions**. On the *Versions* pane you can then select the checkboxes for two different versions of that baseline and then use the **Compare baselines**  action at the top of the _Versions_ pane to create a download that identifies any changes.

In comparing v4 to v3, there is only one setting that’s changed. That setting is: **Block on access protection**. For this setting, the default has changed from True (**Yes**) to be False (**Not configured**).

The comparison download not only identifies changes in a settings default, but will flag when a setting has been _added_ or _removed_ from the newer version of the baseline. 

We did provide a change list for the first baseline that was released when it updated, the MDM baseline. With the Compare baselines option now available, that effort will no longer continue.
