### ISSUE TITLE
Device Template

### ISSUE THREAD

**Issue by jeffjcom** [MicrosoftDocs/memdocs#1811]
You cover setting up a user template can you please cover device too please? 

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41df2048-2b0e-4218-1fc4-d8a657f860cc
* Version Independent ID: e26c4390-87a3-7d5a-4e6f-529b4ccf8759
* Content: [Use private and public key certificates in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/certificates-pfx-configure)
* Content Source: [memdocs/intune/protect/certificates-pfx-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/certificates-pfx-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
Investigating scope of difference for configuring User vs Device templates.

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by Brenduns** [comment]
I regret that our content teams have not been able to allocate the resources to create a device template example since this issue was first raised, and I'm sorry to say we won't be able to in the foreseeable future. 

 Looking back, it seems that the user-based example was chosen originally because it supported both user and device attributes in the SAN and Subject of certificates, making it a more general or useful example than a device-based template example. Since then, we have not received enough requests or evidence of demand for the effort to produce and publish a device-based example.

After doing some more recent on-line research, I came across this blog post from _Nickolaj Andersen_ that might offer some useful guidance on configuring templates. However, as this is a third-party blog, we can’t vouch for its accuracy at this time. That said, I will note that I have found Nickolaj to be a reliable source of information.   See https://msendpointmgr.com/2018/06/21/certificate-deployment-for-mobile-devices-using-microsoft-intune-part-2-certificate-templates/
