### ISSUE TITLE
Default for "Allow biometric authentication"

### ISSUE THREAD

**Issue by qizho** [MicrosoftDocs/memdocs#1862]
Regarding this section:

>Allow biometric authentication
Enables biometric authentication, such as facial recognition or fingerprint, as an alternative to a PIN for Windows Hello for Business. Users must still configure a work PIN in case biometric authentication fails. Choose from:
Enable - Windows Hello for Business allows biometric authentication.
Not configured - Windows Hello for Business prevents biometric authentication (for all account types).
Default: Not configured

The default for PassportForWork CSP's Biometrics/UseBiometrics was changed to true. See https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp. So by default Windows devices will allow biometric authentication if nothing is configured. Does Intune specifically send down false to Biometrics/UseBiometrics if this is set to "Not configured"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb79dc64-b652-b0e4-90c8-f8789c373dd7
* Version Independent ID: 49ce0336-2eab-e3e1-57c3-e1a84e062ff2
* Content: [Windows Hello for Business settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/identity-protection-windows-settings)
* Content Source: [memdocs/intune/protect/identity-protection-windows-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/identity-protection-windows-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@qizho  Thanks for this submission.  I've contacted our engineering team and they have an active work item to investigate this. First, to confirm what is happending when Intune sends the _not cofigured_ value, and then to udpate Intune so the setting functions properly.  As details become available about the _not configured_ value, I'll update this GitHub issue.

**Comment by Brenduns** [comment]
Circling back on this old Issue.  When set to Not Configured, Intune does not actively manage the setting or send information regarding it’s configuration to a device.  How a setting behaves is then left to the underlying CSP that manages the setting on the device, or additional manage sources that might configure that setting which were previously managed by Intune policy enforcing a value of True.  

When Intune does pass (via Policy) a configuration value to a CSP on a device, such as setting/enforcing True in this case, and then that Intune Policy is changed to Not Configured or deleted so that value is no longer managed by Intune –  as long as that setting isn’t  managed/enforced by any other process, the CSP on the device would determine what happens.  

As there has been no feedback from engineering on the change of the CSP, but also no further customer sourced questions about this behavior for some time,  I'll be closing this Issue. If further questions arise, I recommend reaching out to support to force the investigation through normal support channels, which can help drive engineering review.
