### ISSUE TITLE
What takes precense

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/memdocs#190]
Hi, I migth be missing something, but does the Windows enrollement profile setting for WHfb take precece over a Identity protection device configuration profile ?
The settings under Device Configuration profile is a bit more extensive....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5659e9f-4174-c7d5-907f-5867506bdb03
* Version Independent ID: 89c121f1-d4bf-bc07-e9ab-a93ae69a0653
* Content: [Use a PIN to sign in to Windows 10 devices using Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/identity-protection-configure?source=docs)
* Content Source: [memdocs/intune/protect/identity-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/identity-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Nosferatu-Dk    The direct answer is the Identity protection settings (which are user-based) look to override the device-based settings from enrollment. We recommend using only one method or the other, and if you can, use the device-based settings from enrollment, which are tenant wide. If Tenant wide isn’t an option, use the identify protection settings which are user-based and can be targeted to individual groups. 

It turns out Windows Hello settings are a bit different than other settings that might be set through different policy types in Intune, and there are recently discovered complications with the interaction between the device and user based settings which are under review as to implication for Intune policy and use.

**Comment by Nosferatu-Dk** [comment]
@Brenduns Thanks for taking the time to reply!
