### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#1912]
What does this sentence mean: "For discovered Win32 apps, there currently is no aggregate count. This type of data can only be viewed on a per-device basis."? I can see an aggregate count against Win32 apps in the Discovered apps blade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f41921-6680-75b6-5b95-55327279861a
* Version Independent ID: a0178c17-b82b-b762-49f6-17e2abcbd775
* Content: [Discovered apps - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-discovered-apps)
* Content Source: [memdocs/intune/apps/app-discovered-apps.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-discovered-apps.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@Air-Git Thank you for your feedback. We were recently alerted to an issue whereby not all versions of applications are being reported, inconsistencies of information between Discovered apps report and Discovered apps per devices, and Discovered apps reported under devices blade differs from the actual device. Upon investigation, we discovered an issue with our data aggregation service not collecting all application information. In addition, since the data collection occurs every 7 days, feedback from admins was that they wanted to see applications from newly added devices or updated application versions.

Upcoming improvements

Intune has been working on a solution to improve the accuracy and timeliness of discovered apps. We are currently architecting a new data pipeline that will create a more efficient data flow and expect to complete the work by early next calendar year. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Air-Git Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
