### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#1973]
Why is the strange syntax required for the Autopilot group, and not a regular operator syntax? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97ce79c0-0014-f6f0-95f7-58574bfdefb3
* Version Independent ID: 40b3877e-a094-8d05-c95b-ca842c5ca8ce
* Content: [Create device groups for Windows Autopilot - Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot)
* Content Source: [memdocs/autopilot/enrollment-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @Air-Git. I apologize for the long time it took to respond back to this feedback item. We really don't go into how the product works under the hood in the docs nor why certain design choices were done. If the syntax is giving you any issues, I would advise to open a case with support or to provide feedback in the product itself (e.g. in Intune). Since there is nothing actionable from the documentation team, I am going to go ahead and close this item.
