### ISSUE TITLE
RSS Feed doesn't update

### ISSUE THREAD

**Issue by broberts-austin** [MicrosoftDocs/memdocs#1974]
We have the RSS feed tied to a couple Microsoft Teams groups, but it never updates.  And when you just look at the RSS feed in a web browser, it never shows anything.  Can this be fixed?  We have several groups that work on MDM within our organization and the RSS feed really helps.

Here is the link provided on the what's new site:  https://docs.microsoft.com/api/search/rss?search=%22What%27s+new+in+microsoft+intune%3F+-+Azure%22&locale=en-us

And our last RSS update was 7/10/2021

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d16c28db-1e8e-31fa-6127-3050a2940422
* Version Independent ID: 4cf9a244-1ae5-1637-48f7-3f503d400da6
* Content: [What's new in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new)
* Content Source: [memdocs/intune/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/whats-new.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by aczechowski** [comment]
Thanks @broberts-austin for the feedback. We use this format in a number of articles across our content, and I think we need to review it all up. The specific link on this page still includes the old "| Azure" suffix which isn't used anymore. As a short-term work around, you can try this RSS URL:

`https://docs.microsoft.com/api/search/rss?search=%22What%27s+new+in+Microsoft+Intune%22&locale=en-us&facet=products%26facet%3Dcategory&%24filter=scopes%2Fany%28t%3A+t+eq+%27Intune%27%29`

It returns five results instead of one. We'll need to investigate further on how to pair it down better.

For more background on this notification method, see [How to use the docs - Notifications](https://docs.microsoft.com/mem/use-docs#notifications).

**Comment by broberts-austin** [comment]
Thank you for the link.  I'll use that for now.

**Comment by aczechowski** [comment]
We've received other feedback on this issue. I'm making a change to remove the example and point back to [How to use the docs](https://docs.microsoft.com/mem/use-docs#notifications), which has more explanation. I'm hoping that some variation on the query string will work.

If it _still_ doesn't work, we'll just need to remove the tip to get notified. The RSS functionality comes from the docs.ms platform (we can promote the issue to that team if needed), and obviously we don't know what sort of RSS application you're using. Unfortunately docs.ms doesn't offer another option for notification. 😞
