### ISSUE TITLE
Windows Autopilot Motherboard Replacement Process Out of Date - Motherboard

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/memdocs#1989]
[Enter feedback here]

I have been informed by a major OEM that the process detailed on this page is out of date and incorrect. They are telling me that they are unable to de-register devices that they have registered themselves and are expecting the administrator's of the tenant should do this via Intune and not the MPC. In fact they do not use the MPC to register devices but instead use an OEM API.

They also advise that once the OEM replaces a motherboard they are unable to re-register the device and expect the administrator's of the tenant to do this via Intune. This is due to how OEM's register devices into the Autopilot database with just a serial number and not a hardware hash, and is why they are unable to re-register devices themselves directly into the Autopilot database.

Please can this article be reviewed and updated to align with latest Microsoft best practices for Motherboard replacement so that it is clear what OEMs can and cannot do and what activities need to be done by the Intune administrators. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c91281a-bdba-ff2d-6cb5-7ac45396397e
* Version Independent ID: 1a9e425f-7977-66be-eeb5-b41646de2d52
* Content: [Windows Autopilot motherboard replacement](https://docs.microsoft.com/en-us/mem/autopilot/autopilot-mbr)
* Content Source: [memdocs/autopilot/autopilot-mbr.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/autopilot-mbr.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @ajp999. I apologize for the long time it took to respond back to this feedback item. However, since you filed this feedback item we have done several updates to the documentation regarding motherboard replacement. There also have been several significant to Intune and Autopilot itself that addresses some of the issues with motherboard replacement. I am going to go ahead and close this feedback item. If you find any problems with the updated documentation or the updated documentation doesn't address your concerns, please fille a new feedback item.
