### ISSUE TITLE
Need to include more details on which class is in which assembly

### ISSUE THREAD

**Issue by pmgupte** [MicrosoftDocs/memdocs#199]
The page must not assume any level of prior experience with SCCM or Extension development. It should include more details - especially on classes. For example: There is no information on `OverviewControllerBase` class or `IConsoleView2` are available from which DLL/exe file. This doesn't provide good developer experience.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22935c0a-73b9-cf24-d51a-f4f6a94bcce9
* Version Independent ID: 60fac94f-a787-268f-fbf2-de1aab1d7d39
* Content: [Create a Console Custom View - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/servers/console/how-to-create-a-configuration-manager-console-custom-view#feedback)
* Content Source: [memdocs/configmgr/develop/core/servers/console/how-to-create-a-configuration-manager-console-custom-view.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/servers/console/how-to-create-a-configuration-manager-console-custom-view.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @pmgupte, thanks for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. There used to be a SDK download with samples, but that was removed due to lack of use.

The associated article, [About console views](https://docs.microsoft.com/mem/configmgr/develop/core/servers/console/about-configuration-manager-console-views) has some additional information that might be of use. 

Beyond that, I suggest one of the following options for further assistance:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to open an advisory case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue. Unfortunately it's an area that we're not able to invest in at the level that you're asking.
