### ISSUE TITLE
impossible pourquoi?

### ISSUE THREAD

**Issue by jeanmi1700** [MicrosoftDocs/memdocs#202]
j'ai fais exactement ce qui est écris, ça ne fonctionne pas, quelle alternative existe-il?
Team TIMC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b98b09-96b0-1dbe-c356-73fd8ef453a3
* Version Independent ID: 505aa23b-02db-7f45-76ea-277e0ebd520e
* Content: [Client Spy - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/support/clispy#feedback)
* Content Source: [memdocs/configmgr/core/support/clispy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/support/clispy.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jeanmi1700, I'm responding in English since this issue was filed on the en-us version of the article.

Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
@CeciAc in case any localization support is needed.
