### ISSUE TITLE
SDK Download / SDK Examples

### ISSUE THREAD

**Issue by WolfgangAndreas** [MicrosoftDocs/memdocs#2029]
Hi, i tried to find the Download for the current MECM/SCCM-SDK but had no luck.
Where can i download the current SDK or the C#-Samples mentioned here?
Even on the MECM-Media the SDK is missing.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129ccb95-8543-359b-3316-4c9d0e840f85
* Version Independent ID: 8f003a55-5c86-bc8a-1a17-0a5e8bfe5130
* Content: [SDK samples - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/understand/configuration-manager-sdk-samples)
* Content Source: [memdocs/configmgr/develop/core/understand/configuration-manager-sdk-samples.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/understand/configuration-manager-sdk-samples.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @WolfgangAndreas thanks for the feedback. That download was removed for various reasons, and as of right now there are no plans to replace it. If you think there's value in having those sort of samples available, please [file feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) from the console.

I'm actually going to use this issue to remove that article from the docs, since it's basically irrelevant now.

**Comment by aczechowski** [comment]
I made changes for this, but they'll not publish until 2111 releases.
