### ISSUE TITLE
Clarification on AOAG support for Reporting Point DB

### ISSUE THREAD

**Issue by PotentEngineer** [MicrosoftDocs/memdocs#2032]
Reference: 
https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#configuration-manager-supports-only-the-site-database-in-an-availability-group
https://twitter.com/AaronCzechowski/status/1443026082861498378

Can you clarify if AOAG is supported for the Reporting Point DB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49301fc3-9163-d533-1057-f8d994e95bbf
* Version Independent ID: 3c3fbdf1-25ec-3c5f-be4c-46983216d3b5
* Content: [Prepare to use an availability group - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database?source=docs#configuration-manager-supports-only-the-site-database-in-an-availability-group)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PotentEngineer for the feedback. I checked with the engineering team, and it's not tested thus not supported. His recollection is that there _might_ be some known issues there, but again, not tested.

Our current [high availability recommendation for reporting](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/high-availability-options#redundancy-for-important-site-system-roles) is:

> To provide redundancy for reporting on sites and clients, install multiple instances of the reporting services point.

If you think that ConfigMgr should support reporting with availability groups, please file [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback).

I'm closing this issue because the doc is currently technically accurate, so nothing actionable right now.
