### ISSUE TITLE
More concise information required

### ISSUE THREAD

**Issue by capta1n-nem0** [MicrosoftDocs/memdocs#2055]
In the doc it says 

"Once deployed, you can manage Windows devices with:

- Microsoft Intune
- Windows Update for Business
- Microsoft Endpoint Configuration Manager
- Other similar tools"

This is true, however the lack of detail is often confusing for the tens-of-thousands of customers that use other Endpoint Management Solutions. The "Other similar tools" should be replaced with something like "Other EndPoint Management tools that Support Windows Autopilot, such as Ivanti UEM (Formerly MobileIron), VMWare Workspace ONE etc."

I regularly push customers, partners and admins to this documentation page.. but the common response is "It says only Intune is supported". Which is misleading, as many other vendors (E.g. Ivanti) have invested many development hours and cycles to give their customers a great Autopilot Experience. 

More than happy to provide additional feedback.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26400deb-2700-ec72-e6f9-1de4e60f7057
* Version Independent ID: d6b1cb73-8889-44ba-6235-4081a5b7d5d7
* Content: [Overview of Windows Autopilot](https://docs.microsoft.com/en-au/mem/autopilot/windows-autopilot)
* Content Source: [memdocs/autopilot/windows-autopilot.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @capta1n-nem0. I apologize for the time it took to get back to you regarding this feedback item. We unfortunately really can't name 3rd party vendors that support Autopilot because that list is constantly changing. Such maintenance of trying to keep the list up to date with ALL vendors that support Autopilot would be pretty difficult to do, if at all possible. It would sort be like asking to list all vendors that support Windows. What I can do though is clarify the doc and say Other 3rd party tools. If you have further feedback on this, just open a new item. We are actively monitoring feedback again after a problem that it was not notifying us of feedback items. Again I apologize over this.
