### ISSUE TITLE
Does this also apply when using Autopilot Reset?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/memdocs#2083]
Can you clarify whether an Autopilot Reset will require that the Intune device record be manually deleted before the device gets back to Autopilot Self Deployment?  Since an Autopilot Reset is supposed to maintain the device's connection to Intune, I would expect it to re-use the same Intune device record.  

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df9afea7-e8c0-06d2-67c9-19730c9ecab6
* Version Independent ID: a618c754-cc22-b660-b402-45b9c5662ea6
* Content: [Troubleshoot Autopilot device import and enrollment](https://docs.microsoft.com/en-us/mem/autopilot/troubleshoot-device-enrollment)
* Content Source: [memdocs/autopilot/troubleshoot-device-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/troubleshoot-device-enrollment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @NeighborGeek. I apologize for the time it took to get back to you regarding this feedback item. No you don't delete the device record. In fact doing so would break Autopilot Reset since Autopilot Reset requires the device is a current Autopilot device in Intune. We have recently published updated new docs on Autopilot Reset:

https://learn.microsoft.com/mem/autopilot/tutorial/reset/autopilot-reset-overview
