### ISSUE TITLE
User is no longer populated, doc needs to reflect changes

### ISSUE THREAD

**Issue by di6parn** [MicrosoftDocs/memdocs#2100]
Since the 'Update to user enrollment experience in Autopilot' - see [MC288489](https://admin.microsoft.com/Adminportal/Home?source=applauncher&ref=MessageCenter/:/messages/MC288489) - the user assigned to the device is no longer populated on the Autopilot Configuration screens. The documentation should reflect this change.
This also seems to let any non-assigned user log on to the device when it has been resealed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jiorblommaert** [comment]
Those changes are described on following location: https://techcommunity.microsoft.com/t5/intune-customer-success/updates-to-the-windows-autopilot-sign-in-and-deployment/ba-p/2848452

**Comment by di6parn** [comment]
> Those changes are described on following location: https://techcommunity.microsoft.com/t5/intune-customer-success/updates-to-the-windows-autopilot-sign-in-and-deployment/ba-p/2848452

Some interesting reading on that page. Still, this needs to be updated in [the docs](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision) where it still states that _The user assigned to the device (if there is one)_ will be displayed.

**Comment by frankroj** [comment]
Thank you for the feedback @di6parn. I apologize for the time it took to get back to you regarding this feedback item. There have been several developments regarding this issue since you filed this feedback item. Primarily the feature has been added under certain circumstances as documented in the following blog post:

https://techcommunity.microsoft.com/t5/intune-customer-success/return-of-key-functionality-for-windows-autopilot-sign-in-and/ba-p/3583130

We also have an update in our FAQ:

https://learn.microsoft.com/en-us/mem/autopilot/autopilot-faq#which-manufacturers-are-enabled-for-pre-population-of-username-and-automatic-re-enrollment-of-pre-provisioning-devices--

Some of this information is also conveyed at the following link although its a bit out of date. I plan to update it within the next week:

https://learn.microsoft.com/en-us/mem/autopilot/enrollment-autopilot#assign-a-user-to-a-specific-autopilot-device

I am going to go ahead and close this item but if you have any other questions please let me know.
