### ISSUE TITLE
Documentation should inform this part is in preview and not yet rollout to all tenant

### ISSUE THREAD

**Issue by loicmitton** [MicrosoftDocs/memdocs#2185]
Helllo,

I tried to follow the guide on this page but none of the link exist on our tenant.
I think the documentation should that this feature is still in preview and not yet deploy everywhere.

Thank you,
Loïc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Microsoft Defender for Endpoint Security Configuration Management in Microsoft Endpoint manager](https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@loicmitton    It turns out that this feature is rolling out slowly over the course of a week or two, so it might be some time before its available in your Tenant. That was not originally communicated by our product group. We've updated the docs to provide visibility to this slow rollout of availability:  

- _This feature is in public preview and will roll out to tenants gradually over the next few weeks. You can confirm your tenant has received this capability when the relevant toggles show in both the Microsoft Endpoint Manager admin center and Microsoft Defender for Endpoint._
