### ISSUE TITLE
Missing 2 licensing options

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/memdocs#2195]
[Its missing licensing Options. M365 E3 + EMS E5 Or Bussines Premium as announced here - https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/introducing-microsoft-defender-for-business/ba-p/2898701#comment-on-this]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d129246-93fe-04ec-0e49-8e9ac1c910a8
* Version Independent ID: 66d3e475-e2b9-1974-f04a-2ae8b31f96bd
* Content: [Use Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection)
* Content Source: [memdocs/intune/protect/advanced-threat-protection.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/advanced-threat-protection.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Nosferatu-Dk   Thanks for the submission about the license options. You’re correct in that there are additional license options, which is why this article describes those that are listed as common options, then followed by the link to the Defender for Endpoint licensing content. Always, with product integrations, a product’s own content will be the go-to source for current details. 
We'll make a change here to avoid limitations or confusion due to untracked changes for MDE.  That change will remove the listing of MDE options in the Intune docs in deference to the MDE license page to avoid future issues regarding MDE options.
