### ISSUE TITLE
App Protection Policy Limitation or Flaw

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/memdocs#2212]
If the app protection policy says from say outlook, and you say you can only share data with other managed apps there is a flaw.  

iOS (latest version):
Open outlook -> open any email -> print it (don't actually click print) -> expand the preview of the print job -> click the share button in the lower left -> you can now save corp data anywhere you want on your managed device. 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a975327d-c170-b66d-9393-2895614c830c
* Version Independent ID: dee8adfb-6769-2842-f56b-b61b01814c2a
* Content: [Validate your app protection policy setup - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies-validate)
* Content Source: [memdocs/intune/apps/app-protection-policies-validate.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/app-protection-policies-validate.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@SquirrelAssassin Thank you for your feedback. Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closely with our support team via the need help Icon on the admin center. Based on the issue, the support team will be able to determine if this is a limitation or a bug and will be able to take this forward.

Hope this helps!

Thanks
Sri
