### ISSUE TITLE
AssignedComputerName field capability in CSV

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/memdocs#2225]
Why is there no field in the CSV for AssignedComputerName, this only appears to be a capability on the online upload.. Surely a CSV file with appended Hardware ID's is an ideal opportunity to add manually assigned computer names before the upload of the hardware ID's?!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @chiners68 for taking the time to provide feedback on Autopilot! I want to make sure it gets directly into the hands of the engineering team. I think the best process would be to submit the suggestion through [Feedback for Intune](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472).

I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time.
