### ISSUE TITLE
Attach to multiple tenants

### ISSUE THREAD

**Issue by ManuelSchenkel** [MicrosoftDocs/memdocs#2227]
Can I attach an SCCM hierarchy to multiple tenants or just one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eb4acb-7311-79d3-3daa-6f27ea42aee7
* Version Independent ID: 123f2a5c-04c1-8184-05a4-689d9c591981
* Content: [Microsoft Endpoint Manager tenant attach - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/tenant-attach/device-sync-actions#feedback)
* Content Source: [memdocs/configmgr/tenant-attach/device-sync-actions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/tenant-attach/device-sync-actions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @ManuelSchenkel, while you can do tenant attach/co-management from multiple sites to a single tenant, you can't do the other way (one site to multiple tenants).

I suggest that you file [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.
