### ISSUE TITLE
Docs are circling back to each other - no full explanation

### ISSUE THREAD

**Issue by ManfredPohlemann** [MicrosoftDocs/memdocs#225]
Hi, we want to connect our MEMCM with WSfB and found this page. It's referring to another MS Docs page for detailed explanations (Configure Azure services). The second page is circling back to this page without detailed explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 766b1855-dc0a-3664-5d0f-184a34998900
* Version Independent ID: d459b52e-76bb-1af1-6c99-4cd0b7e3f11e
* Content: [Microsoft Store apps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business#feedback)
* Content Source: [memdocs/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ManfredPohlemann, that's by design. The Configure Azure Services wizard is a common wizard used by multiple connections. So that common process is documented in the [Configure Azure Services](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/azure-services-wizard) article. So in the MSfB article, set up synchronization section, you need to start by going to that other article. When you get to the point of configuring MSfB specifically, come back to the MSfB article and continue with the [Supplemental information and configuration](https://docs.microsoft.com/mem/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business#bkmk_config) section, which is specific to MSfB.

If there's some other aspect of the two articles that you think is circular, let me know.
