### ISSUE TITLE
is this code snip-it still valid or should we be using Microsoft.ConfigurationManagement.Messaging.Messages.Server.DiscoveryDataRecordFile instead?

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/memdocs#229]
Should you be using SMSResGen.SMSResGen.1 or Microsoft.ConfigurationManagement.Messaging.Messages.Server.DiscoveryDataRecordFile instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9bcf9c-9ac1-1f22-c857-8f791ef383b8
* Version Independent ID: 94f02a8a-d06b-d445-6061-bfc791bdcb7b
* Content: [Add New Properties to an Existing Resource Type](https://docs.microsoft.com/en-us/mem/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type)
* Content Source: [memdocs/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/develop/core/servers/configure/how-to-add-new-properties-to-an-existing-resource-type.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback. The ConfigMgr SDK content hasn't changed in a long time, and it's an area in which we're not actively investing beyond basic maintenance and some new functionality. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by ameltzerMSFT** [comment]
This is an old thread but I stumbled across it.

To answer your specific question, what you want to use is up to you, but the DiscoveryDataRecordFile class is the recommended approach. It should have full functional parity with SMSResGen. It has some other advantages as well: no COM registration so it can be used right away without elevation, no x86 vs x64 considerations, easier to use APIs, integration with other aspects of the messaging SDK, fully managed code, and it's part of an SDK that's under active development so we'd consider ideas for further improvements.

SMSResGen hasn't changed since SMS 2003 and there's no plans to update or otherwise improve it.
