### ISSUE TITLE
Need this to be more informative for IT Pros to be able to understand Settings that dictate End User Experience

### ISSUE THREAD

**Issue by aamer-s** [MicrosoftDocs/memdocs#2324]
This document does a decent job in explaining various settings but fails to provide guidance most It Admins/ Device Administrators are looking for i.e. End User Experience. It will be great to have 2 or 3 examples here which show end user experience with snapshots (e.g. where users have option to postpone reboots etc.)
Most customers come from SCCM background where they are looking at getting same kind of  end user experience and controls they had with notifications and certain actions they could take for those notifications. None of this is properly drafted in this document and needs a lot of trial and error before a desired outcome is reached.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401fe085-6254-6dbb-24c6-7e6fe56d0f3a
* Version Independent ID: 774ae4fb-b28e-1fb3-46d9-5802c0e4ac6c
* Content: [Windows for Business Update settings for Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-settings#feedback)
* Content Source: [memdocs/intune/protect/windows-update-settings.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-update-settings.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@aamer-s   Thanks for this feedback. The content in this Reference area of our documentation is intended as a strict for settings that are available for various policies that otherwise would require one to troll through the UI to examine each setting and its options to understand or review what's available.   

For user guidance, we (doc writers) agree that having usage examples and scenarios would be great to add to content and is something we remain aware of as future work. While such scenario-based content is something we would like to invest in, for now it remains beyond our capacity to do. When/If we are able to deliver on that style of content, that guidance will be found in articles in our _How-To_ content area, alongside or within articles for updates like [Use Windows Updates for Business](https://docs.microsoft.com/mem/intune/protect/windows-update-for-business-configure).
