### ISSUE TITLE
Incorrect permissions documented for registering devices

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/memdocs#2388]
This statement:

`Autopilot device management requires only that you enable all permissions under Enrollment programs, except for the four token management options`

Does not appear to be correct. After substantive time attempting to create an appropriate user, I came across this blog:

https://oofhours.com/2019/08/13/creating-a-windows-autopilot-role-in-intune/

Which states: `After comparing the permissions in the built-in Policy and Profile Manager role, I first tried adding read access to the “Organization” class.  That improved things a little, but still no luck.  Next up, I tried to add read access to “Audit data.”  And that was enough.  So I guess those two are required.`

So it appears established that permissions are required beyond those documented. In my time testing this, I found the above allowed required access to the UI. This document is three years old however, and getting this working today mean providing the four permissions under "Corporate Device Identifiers". Following that change, I confirmed access via both the web UI and the `Get-WindowsAutoPilotInfo -Online` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by t-damant-83** [comment]
This doesn't appear to work anymore. Sadly.

**Comment by frankroj** [comment]
Thank you for your feedback @technion and @t-damant-83. I apologize for the long time it took to respond back to this feedback item. In the docs we only cover the out of box roles. There is an infinite amount of permissions you can combine and set to try and create custom roles so there is unfortunately no way to properly document all possible combinations. If you need additional assistance with how to set up the correct permissions for the custom role, I would recommend to open a case with support.

Since there are no additional actionable items from the doc team, I am going to go ahead and close this feedback item.
