### ISSUE TITLE
Inaccurate info in this doc - MVP Feedback

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/memdocs#2396]
1. In my testing I have found that I can only get to white glove if the deployment profile is set to "User Select" for the language. Otherwise, the language and network screens are skipped so I don't get an opportunity to press the Windows key 5 times. 
2. This section, "Additionally, any Win32 or LOB apps will be installed if they meet these two conditions:...." is no longer true since pre-assigning users to devices has been deprecated. This also means that the section " Validate the information displayed..." is also incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision?source=docs#prerequisites)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @PJMarcum. I apologize for the time it took to get back to you regarding this feedback item. Since you posted this feedback, item #1 has been fixed in the latest releases of Windows 10 22H2 and Windows 11 22H2, so it should not be a problem.

For issues #2, assigning a user to devices and assigning apps to users was never deprecated. The only thing that temporarily changed was showing the users info (name & email address) during the Autopilot deployment when a device was assigned to a user. However, even that has now been reverted in certain instances. The below blog explains more:

https://techcommunity.microsoft.com/t5/intune-customer-success/return-of-key-functionality-for-windows-autopilot-sign-in-and/ba-p/3583130

I am going to make some updates to the docs though to clarify that the note applies to apps installed during User ESP and the User flow phase.
