### ISSUE TITLE
Report problems to Microsoft

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/memdocs#244]
There's no such option in the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ace8de8-22ac-4cf3-e4b4-5ce8911a0290
* Version Independent ID: 1dfbc4d8-8d2c-fd92-f396-6615399381ee
* Content: [Get help and support in Company Portal for Windows 10](https://docs.microsoft.com/en-us/mem/intune/user-help/help-support-windows-cpapp)
* Content Source: [memdocs/intune/user-help/help-support-windows-cpapp.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/help-support-windows-cpapp.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @icelava, I'm looking into your feedback and will update you (and the docs, if needed) when I find out more info on my end. Thanks!

**Comment by lenewsad** [comment]
Hi @icelava, thanks again for sharing your experience.  I wasn't able to find out why **Help & support** would be missing from the UI. On my end, the option is available. Since I'm limited to documentation help, I want to get you to the right people if this is still a concern to you. Here are some product support channels:

- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
