### ISSUE TITLE
Inaccurate information, old user's files are accessible inside the Windows.old folder

### ISSUE THREAD

**Issue by Eurosome** [MicrosoftDocs/memdocs#2455]
Inaccurate information, old user's files are accessible inside the Windows.old/users folder.
https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@Eurosome Thank you for your feedback.  Autopilot Reset only removes data in the user profile, not across the entire drive. So if your users are saving data outside their profile it will be available in windows.old. Autopilot Reset basically only removes the user profile instead of wiping the entire OS drive. 

I assume there are no changes needed for now. If you still see the user's profile information after an autopilot reset, we might have to work with the support to identify the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@ Thank you very much for the contribution and sharing this explanation. @ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
