### ISSUE TITLE
filtering with Enrollment profile name on Windows during Autopilot enrollment is not working.

### ISSUE THREAD

**Issue by tomrydl** [MicrosoftDocs/memdocs#2474]
in this chapter https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#using-filters-with-enrollment-restriction-and-esp-policies describes that Enrollment profile name is always available during enrollment, however based on my and customer testing, it seems that is not. So then cannot be used this property (Enrollmetnprofilename) with filters for enrollment restrictions policies applied during Windows Autopilot.

**Comment by frankroj** [comment]
Thank you for your feedback @tomrydl. I apologize for the long time it took to respond back to this feedback item. However, I am not seeing the verbiage you are referring to. If you are still having issues with this doc, can you please open a new feedback item and point to the specific information on the page that you are referring to? I am going to go ahead and close this request since there is nothing actionable at this time.
