### ISSUE TITLE
Missing Information on Script Authoring

### ISSUE THREAD

**Issue by gwpelletier** [MicrosoftDocs/memdocs#2478]
There are certain rules that are not explained on this page when it comes to authoring scripts.

For example, the proper way to return a value to MEM via a PowerShell script is to utilize the pipeline or the "return" keyword.

If a script or the script host exits with a non-zero return code, then the script will be in an error condition.

If a script returns no value at all AND a remediation script is configured to run in the remediation rule, the remediation script will not run but instead the status will return "Non-Compliant"

I remember reading an old document with this, but I can't find it anymore. This would be VERY helpful for script authors new to MEM / SCCM configuration items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb2976-54e8-e5d1-1833-bc7141836a72
* Version Independent ID: 3f006ea9-52d9-cddf-4d78-b06e7d31ea5e
* Content: [Create custom configuration items - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client)
* Content Source: [memdocs/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @gwpelletier for the feedback...I'll just be honest that I don't see our team taking the time to track this down to update. We don't have a resource that's actively working in this space. So instead of just leaving the issue open, I'm going to close it. Alternatives - file product feedback that there should be better guidance on this process. If that gets a bug filed internally, I can then at least push that over to engineering/PM. Or if you learn more about this, you're always welcome to submit a contribution directly: https://docs.microsoft.com/mem/use-docs#contribute
