### ISSUE TITLE
Explain "The Windows 365 service always uses the first assigned policy to provision the Cloud PC." in more detail

### ISSUE THREAD

**Issue by robinherbert** [MicrosoftDocs/memdocs#2553]
The text "The Windows 365 service always uses the **first assigned policy** to provision the Cloud PC." needs some detailing. What is the "first assigned policy"? Is it the first policy the user gets assigned (via AAD group membership)? What if they're in multiple groups, and removed from the first one they were added to?
Would be better to have a priority order of PP - so the highest priority PP that the user is assigned to is the one that is used.
Also, some way of triggering a re-evaluation of the provisioning (if the user has a license AND has a PP, but no Cloud PC is being provisioned).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abd80489-2003-375a-c99d-77e8ef41ac9d
* Version Independent ID: 92b08902-3c5e-274f-f8ba-829194e83575
* Content: [Create provisioning policies for Windows 365](https://docs.microsoft.com/en-us/windows-365/enterprise/create-provisioning-policy)
* Content Source: [windows-365/enterprise/create-provisioning-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/main/windows-365/enterprise/create-provisioning-policy.md)
* Service: **cloudpc**
* Sub-service: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with pm
44742844

**Comment by MattShadboltMSFT** [comment]
By 'first assigned', it means the first assignment per-user. For example, if a user is in two groups - Group1 and Group2, and a provisioning policy is assigned to Group1, then a second provisioning policy is assigned to Group2, only the first provisioning policy assigned to Group1 will apply to that user. If a different user is added to Group2, then added to Group1, the first assigned policy will be that of the Group2 group, and the Group1 assignment will not apply. 

If the user is removed from a Group1, that assignment no longer exists, so they will get the Group2 assignment (once grace period, etc expires)

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
