### ISSUE TITLE
Wiping now Factory Resets....

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/memdocs#2605]
I just wiped my device, which I had done previously and it factory reset the phone. WTF? Its supposed to only wipe company data, good thing I didn't roll this out to employees yet. Why was this function changed and when?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cdcc7fd-5bd9-1645-abf4-a73d3ea7adaa
* Version Independent ID: 5022b2ba-5fb0-18ce-9079-1b65ad0b2e17
* Content: [Retire or wipe devices using Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/devices-wipe#feedback)
* Content Source: [memdocs/intune/remote-actions/devices-wipe.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/devices-wipe.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Dburke225 Thank you for your feedback. As mentioned in the document, the Wipe action restores a device to its factory default settings. The user data is kept if you choose the Retain enrollment state and user account checkbox. Otherwise, all data, apps, and settings will be removed.A wipe is useful for resetting a device before you give the device to a new user, or when the device has been lost or stolen. Be careful about selecting Wipe. Data on the device cannot be recovered.

If you'd like to see a change in the feature or design, You can provide feedback on our portal -https://feedbackportal.microsoft.com/

Hope this helps!

@yogkumgit There are no changes in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@Dburke225 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
