### ISSUE TITLE
Please Update the Configuration Settings page to include the Config Package Type option

### ISSUE THREAD

**Issue by tomsull22** [MicrosoftDocs/memdocs#2619]
The Configuration Settings Page of the Endpoint detection and response Profile creation dialog has a new configuration option called "Microsoft Defender for Endpoint client configuration package type" with 4 options, "Auto from connector", "Onboard", "Offboard", and "Configure".  The current page shows the older "Configuration Settings" page without this new option.  Please document this new configuration item and its options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@tomsull22   Hello Tom, an update is now on the way.  As it turns out, the option you've called attention to wasn't previously disclosed by our product team to the content team, and the UI has failed to describe its use. Here are the missing details.  This information will be added to this article, as well as to the [EDR profile details](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy) within a couple of days: 

**Options for Microsoft Defender for Endpoint client configuration package type:**

After you configure the [service-to-service connection](https://docs.microsoft.com/mem/intune/protect/advanced-threat-protection-configure#enable-microsoft-defender-for-endpoint-in-intune) between Intune and Microsoft Defender for Endpoint, the **Auto from connector** option becomes available for the setting _Microsoft Defender for Endpoint client configuration package type_. This option is not available until you've configured the connection.

When you select **Auto from connector**, Intune automatically gets the onboarding package (blob) from your Defender for Endpoint deployment. This replaces the need to manually configure an onboard package for this profile. There is no option to automatically configure an offboard package.
