### ISSUE TITLE
Potentially conflicting advice

### ISSUE THREAD

**Issue by crosscontrol** [MicrosoftDocs/memdocs#2639]
This site contains the following section that seems to state devices should only be registered through Endpoint Manager for testing. Additionally it states to use the Partner Center which, if I understand the wording, is going to be retired soon:

> Because Intune offers free (or inexpensive) accounts that lack robust vetting, and because 4K hardware hashes contain sensitive information that only device owners should maintain, we recommend registering devices through Microsoft Endpoint Manager via a 4K hardware hash only for testing or other limited scenarios. In most cases, you should instead use the Microsoft Partner Center for Autopilot device registration.

This seems to conflict with [this page](https://docs.microsoft.com/en-us/mem/autopilot/manual-registration) that says:

>Device profile assignment will be retired from MSfB and Partner Center in the coming months

Plus it says Intune is the:

>Microsoft recommended platform to use

Hope this helps! Maybe I’m misunderstanding something though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4a659b-65d0-26ec-c36a-9a21a72a09a8
* Version Independent ID: bff44b73-9021-6659-e212-66349c759989
* Content: [Manually register devices with Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/add-devices)
* Content Source: [memdocs/autopilot/add-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @crosscontrol. I apologize for the long time it took to respond back to this feedback item. It appears that there have been updates to the documentation since you filed this feedback item as it no longer states that device profile assignment is being retired (or was retired) from the Microsoft Partner Center. I am going to go ahead and close this feedback item, but if you find any additional issues, please open a new feedback item.
