### ISSUE TITLE
About Compliance Policy [Require encryption of data storage on device] of Hololens

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/memdocs#2695]
https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-windows#windows-holographic-for-business

There seems to be an inconsistency between the above content and the following docs.
Which is correct?

https://techcommunity.microsoft.com/t5/intune-customer-success/intune-support-tip-managing-compliance-on-hololens-2-with/ba-p/2464609
----------------------------
Require encryption of data storage on device.     Not applicable
----------------------------
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979d9182-7aa8-9a97-399b-2a495164f1a7
* Version Independent ID: b293cc1c-53ce-d06f-c991-a0f1a27214fc
* Content: [Windows compliance settings in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-windows#windows-holographic-for-business)
* Content Source: [memdocs/intune/protect/compliance-policy-create-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-create-windows.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@buhibu9   Thanks for this issue, and your question is a good one.  I've reached out to our development team on this, as they are the source of truth for the docs and what the product officially supports should problems arise.  While I don't doubt the details in the support post as to the settings working with HoloLens, it might take some time for the product team to evaluate and confirm official support for those settings that can then be translated into a content update. 

Once the product team can investigate and confirm what settings from the profiles are supported for HoloLens, I'll report back to you via this GitHub issue, and as applicable, drive a content update.  I've no  ETA for this, though I'd expect at least a week or two, if not significantly longer to suss out the current scope of supported settings.

**Comment by buhibu9** [comment]
Thank you in advace

**Comment by Brenduns** [comment]
Bumped the ask with the product team contacts. Answer still pending.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by Brenduns** [comment]
As we've been unable to obtain product team validation or ccomment, we cannot act on this issue. Consider opening a support case to seek validation of each setting's applicability to Hololense in the current environment, (possibly changed since this issue was origianlly opened against docs).  I do find it possible the blog cited is accurate, as the setting details in this article greatly predates the original guidance in this article as provided by the Intune engineering team - and the relevant CSP for this setting was never identified in the Intune UI nor to be expressed in documnetation.
