### ISSUE TITLE
Servicing channel option doesn't exist

### ISSUE THREAD

**Issue by jbclarkman** [MicrosoftDocs/memdocs#2697]
[Enter feedback here]
The "Semi-Annual Channel" Does not exist anymore in Intune for Servicing Channel.  Do you mean "Retail" instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6d726f-bd44-d168-0af5-c0fe73e06eb9
* Version Independent ID: a87f06b1-f284-42db-a5ed-2cba46bdf2b9
* Content: [Use Intune to expedite Windows quality updates](https://docs.microsoft.com/en-us/mem/intune/protect/windows-10-expedite-updates)
* Content Source: [memdocs/intune/protect/windows-10-expedite-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-10-expedite-updates.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@jbclarkman    Thanks for this feedback.  Your correct that the Semi Annual was retired, and now is identified as *Retail*.  As it happens, _Retail_ is not the expected representation and will eventually update to be _Generally Available_, which identifies non-preview/beta releases.   With this change confirmed, I have a content update on the way.  The content will reference Generally Available instead of Retail (In advance of that future change), and call out specifically that Preview, Dev, and Beta builds are not supported.   These content updates should be live in a day or so. The change from Retail has not current eta.
