### ISSUE TITLE
LoB store apps

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#2702]
I think this section, under Account Setup, is not correct:
"LoB store apps, online store apps, and offline store apps that are assigned to any of the following objects:
- All Devices
- All Users
- A user group in which the user enrolling the device is a member with installation context set to User".

I think it means any LoB store app that is installed in user context, and any online store app, regardless of how they are assigned.

Under Device Setup, there seems to be a redundancy:
"LoB store apps with installation context = Device.
Offline store and LoB store apps with installation context = Device."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @yogkumgit I reached out to the product owner's and will update when I hear back.

**Comment by lenewsad** [comment]
Hi @Air-Git, @yogkumgit, Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
