### ISSUE TITLE
Conversion of Azure Active Directory hybrid devices to autopilot devices with non-user-driven deployment-profile now possible?

### ISSUE THREAD

**Issue by scdfosbos** [MicrosoftDocs/memdocs#2732]
Hello,

in the article https://docs.microsoft.com/en-us/mem/autopilot/existing-devices a note shows that

_Windows Autopilot for existing devices only supports user-driven Azure Active Directory and Hybrid Azure AD profiles. Self-deploying and pre-provisioning profiles are not supported._

As the mentioned article is from March 2022, I would like to know if a conversion of AzureAD hybrid joined (existing) devices to AzureAD hybrid AUTOPILOT devices is know possible with a non-user-driven autopilot deployment profile?

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by msbemba** [comment]
@scdfosbos Thank you for your feedback. The Windows Autopilot for existing devices only supports user-driven Azure Active Directory and Hybrid Azure AD profiles.  I do not see it available for the non-user-driven autopilot deployment profile in the roadmap. 

However, I'd recommend you post this on our Feedback portal, so that a Product/Dev engineer will be able to provide more information on when it will be available.

main feedback portal - https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@scdfosbos Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
