### ISSUE TITLE
Source file for Task Sequence

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/memdocs#2785]
[Hello, 
For the line in the Run Command Line in a task sequence "cmd.exe /c copy Jan98.dat c:\sales\Jan98.dat" 
1. Where does the Jan98.date is located? There is no path? is it local?
2. If it is on a share \\Server\Share$ how do I get it on the local client?

Thanks,
Dom]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d2232b-5503-07b6-29fd-8afcdcea9a89
* Version Independent ID: 9621b35d-5928-2319-1048-eff6fa6a2e70
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/understand/task-sequence-steps)
* Content Source: [memdocs/configmgr/osd/understand/task-sequence-steps.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @felymich in that example, I think it would get the source file from the current working directory. Ideally you would also use the **Start in** option. Or just use an explicit path for the source file so that there's no question. So if the source file is on a network share (and the permissions are handled appropriately), then you should be able to do something like:

`copy "\\server\share\filename.dat" c:\sales\file.dat`
