### ISSUE TITLE
"Android Enterprise fully managed" does not support custom notifications.

### ISSUE THREAD

**Issue by Ikuko-Konno** [MicrosoftDocs/memdocs#2788]
"Android Enterprise personally-owned with a work profile" supports custom notifications, but currently "Android Enterprise fully managed" does not.
We would appreciate it if you could add this to your public documentation.
https://docs.microsoft.com/en-us/mem/intune/remote-actions/custom-notifications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992e6528-c0a0-5b47-3133-28b6a9086d65
* Version Independent ID: d48c3237-1ea2-a6cd-4b3a-561d4ea964c5
* Content: [Send custom notifications to users with Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/remote-actions/custom-notifications)
* Content Source: [memdocs/intune/remote-actions/custom-notifications.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/custom-notifications.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2824

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@Ikuko-Konno Thank you for your feedback. 


Based on inputs from the PM I gather that AE fully managed devices do support custom notifications. However, the notification may not have shown up because of some reliability issues with custom notifications.
This is documented here: [Send custom notifications to users with Microsoft Intune - Microsoft Intune | Microsoft Docs.](https://docs.microsoft.com/en-us/mem/intune/remote-actions/custom-notifications)

Intune, the Company Portal app, and the Microsoft Intune app, can't guarantee delivery of a custom notification. Custom notifications might show up after several hours of delay, if at all, so they shouldn't be used for urgent messages.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Ikuko-Konno Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
