### ISSUE TITLE
Prerequisites Note - Pre-provision re-enroll

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/memdocs#2789]
Regarding Prerequisites, Note 1. "You cannot automatically re-enroll a device through Windows Autopilot after an initial deployment in pre-provisioning mode."

This seems to be incorrect. It is usually possible to reset the device using Fresh Start or Wipe. Both of these actions cause the object in Intune to be deleted. I raised a Premier Support ticket to question this. They confirmed it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @Air-Git. I apologize for the amount of time it took to get back to you regarding your feedback.

At the time you provided this feedback, the Important note was correct. You couldn't re-enroll the device through Windows Autopilot after an initial deployment in pre-provisioning mode. The note went on to say that you first had to delete the Intune device record before running the Autopilot deployment. Since the two methods you mentioned - Fresh Start and Wipe - deletes the Intune device record (also as you mentioned), then it effectively meets the criteria to fix the issue as mentioned in the Important note.

However, since you provided your feedback, the behavior has been changed and you can now automatically re-enroll a device using Autopilot without first deleting the record from Intune. This is described in the following blog post:

https://techcommunity.microsoft.com/t5/intune-customer-success/return-of-key-functionality-for-windows-autopilot-sign-in-and/ba-p/3583130

For this reason, I have removed the Important note since it is no longer applicable. Thank you again for letting us know about this issue.
