### ISSUE TITLE
Web apps added but "Not applicable" for Windows devices

### ISSUE THREAD

**Issue by danthioolea** [MicrosoftDocs/memdocs#2803]
[Enter feedback here]

The documentation reads "For Windows devices, a shortcut to the web app is placed on the Start Menu."
However, when i added a web app as "Required" for a group of users, it was installed only on their iOS devices and shows up as "Not application" for Windows devices.

Can someone explain why this has happened and how can i troubleshoot it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804899ad-0aaf-4e3d-32f1-98055153a251
* Version Independent ID: 51b1dd58-5c58-c5eb-8b46-96517a339fc8
* Content: [Add web apps to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/web-app)
* Content Source: [memdocs/intune/apps/web-app.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/web-app.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by msbemba** [comment]
@danthioolea Thank you for your feedback. By default, intune creates shortcut to the web app as shown below

For iOS/iPadOS devices, a shortcut to the web app is added to the home screen. 
For Windows devices, a shortcut to the web app is placed on the Start Menu.

If you continue have this issue or if it shows as not applicable, I'd recommend you to contact Microsoft support via the need help section on the admin center, so that a support engineer can help you troubleshoot the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @danthioolea Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
