### ISSUE TITLE
Note regarding Hybrid Azure AD convert option

### ISSUE THREAD

**Issue by William-Francillette** [MicrosoftDocs/memdocs#2872]
Hi,
the note regarding convert all device targeted by this profile and Azure hybrid Azure AD devices is confusing 
`Converting all targeted devices to Autopilot isn't supported for transforming a hybrid Azure AD device into a Azure AD Autopilot device.
`
Do we need to understand it as follow:
Converting all targeted devices to Autopilot isn't supported for transforming a hybrid joined Azure AD devices to Autopilot device

or  
Converting all targeted devices to Autopilot isn't supported for transforming a hybrid joined Azure AD devices to Azure AD joined when the autopilot profile is set to join to azure AD as : Azure AD joined?
Thanks,
William
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac6aa29-d930-773f-7b54-9467aaca5378
* Version Independent ID: b89a8390-faee-2a23-e435-bf36e5597b63
* Content: [Automatic registration of existing devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/automatic-registration)
* Content Source: [memdocs/autopilot/automatic-registration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/automatic-registration.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by kvduijvenbode** [comment]
I have the same question, it's not clear for me...

**Comment by frankroj** [comment]
Thank you for the feedback @William-Francillette and @kvduijvenbode. Sorry for the delay in updating you on this feedback. The wording on this note has since been updated to make it more clear what it means. It doesn't actually convert anything. It simply registers the device as an Autopilot device so that it can use the Autopilot service. It doesn't actually do anything else with an existing device record.
