### ISSUE TITLE
MAM policy can only be applied to Android or iOS client platforms. 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/memdocs#294]
@Michal-Ziemba commented 1 hour ago
When following the tutorial cannot save the policy getting the error:
`MAM policy can only be applied to Android or iOS client platforms.`

In order to save the policy you need to set the device platform to iOS and Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Tutorial - Protect Exchange Online email on unmanaged devices - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Michal-Ziemba  I’ve reviewed the article and see that in the first procedure the second step specifies the selection of iOS as the platform for this tutorial. The other procedures in this article aren’t tied to specific platforms nor require the selection of a platform. As this is already covered in the content, I’ll be closing this issue. However, if I misunderstand, please provide more details about the missing details or incorrect information in this article and we can then take a closer look.

**Comment by Michal-Ziemba** [comment]
OK @Brenduns 
I will be more specific this time.
When you follow the section [Create an MFA policy for Modern Authentication clients](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices#create-an-mfa-policy-for-modern-authentication-clients) in point 6 b) change "_Any device_" to "_Select device platforms and checkmark the iOS and Android options_", please? 

Otherwise, if you follow the instruction and try to save the policy you will get an error:
`MAM policy can only be applied to Android or iOS client platforms.`

The same goes for the section [Create a policy for Exchange Active Sync clients](https://docs.microsoft.com/en-us/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices#create-a-policy-for-exchange-active-sync-clients), the same point.
