### ISSUE TITLE
White Glove - no longer labeled White glove in the interface

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/memdocs#2968]
The image/screenshot in the Preparation section is outdated. It is no longer called 'WHITE GLOVE' in the interface - users will not be able to find that toggle in the updated interface

https://docs.microsoft.com/en-us/mem/autopilot/pre-provision#preparation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f572e0-1bc0-6f14-7f60-989eb67fb7e7
* Version Independent ID: e4ec5b25-d9a6-d260-6cf6-ff4f3eb3ecb8
* Content: [Windows Autopilot for pre-provisioned deployment](https://docs.microsoft.com/en-us/mem/autopilot/pre-provision)
* Content Source: [memdocs/autopilot/pre-provision.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/pre-provision.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @gbms311. Yes, we are aware that many of the screenshots in the Autopilot documentation are outdated. Since the Intune interface constantly changes and evolves, it's not easy keeping screenshots up to date. There are also other problems with screenshots such as localization problems. For this reason, we have decided in general not to include screenshots in any new articles. We will also be working on the existing Autopilot docs to remove any screenshots. Our goal is to instead better explain the interface in the documentation. This will allow us to more easily update the docs as things change in Intune.
