### ISSUE TITLE
principle of least privilege

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/memdocs#2972]
There's no way that Full Control is required for autopilot to hybrid join a computer to AD. I'm still surprised that we see principal of least privilege being violated in today's world. And yet there's no "doc" from Microsoft on how to delegate the domain join privilege using the principal of least privilege.

https://docs.microsoft.com/en-us/answers/questions/764328/delegate-34domain-join-only34-permission-to-a-stan.html
Take a look at answer proposed by "GaryReynolds". This answer uses the principal of least privilege for domain-joining a computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f93dd93-e003-36fc-02d6-07166537d914
* Version Independent ID: 1b860d13-bcf5-50da-89f9-ee12ece6edb2
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-hybrid)
* Content Source: [memdocs/autopilot/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by poortom1004** [comment]
the list of properties that you need to write to are:

- displayName
- samAccountName
- userAccountControl
- dNSHostName
- servicePrincipalNames
- distinguishedName (to support renames and moves, but not needed for Autopilot)
- cn (to support renames and moves, but not needed for Autopilot)

The list of extended rights that you need are:
- Reset password (for joining to an existing object, but not needed for Autopilot)
- Validated write to dns host name
- Validated write to service principal name

**Comment by yogkumgit** [comment]
@dougeby Please help us in resolving this issue. Thanks

**Comment by frankroj** [comment]
Thank you for the feedback @poortom1004. I apologize for the long time it took to respond back to this feedback item. Although I agree with some of the points and principles you have brought up, this really is more product feedback than documentation feedback. Currently the documentation reflects what the product was spece'd to. The domain join process as handled by the Intune Connector may need special permissions that a normal user doing domain joins doesn't need. The Intune Connector also uses a Computer account instead of a User account, so again there may be differences. Ultimately though again this is a product feedback issue and not a documentation feedback issue. I would recommend filing feedback for the product where appropriate (e.g. in Intune). Since there is noting actionable from the documentation team, I am going to go ahead and close this request.
