### ISSUE TITLE
Ambiguous Description on "Update Intune Connector for Active Directory for Hybrid Azure AD joined devices"

### ISSUE THREAD

**Issue by benjaminjamesowens** [MicrosoftDocs/memdocs#3029]
In find the section relating to "Update Intune Connector for Active Directory for Hybrid Azure AD joined devices"

A few points which need clarifying:

- Does the ODJ connector need to updated for current deployments for it to continue working past September 2022
- Could you clarify why or why not the Intune Connector may or may not work for Autopilot using hybrid Azure AD deployments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92de7259-6e52-061f-f93c-396d5613f778
* Version Independent ID: ee84b9dd-4940-d5c9-a12d-dcfd705f5d60
* Content: [What's new in Autopilot](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-whats-new)
* Content Source: [memdocs/autopilot/windows-autopilot-whats-new.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-whats-new.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by benjaminjamesowens** [comment]
@aczechowski thank you. My apologies for the duplication. I was unsure if I submitted to the correct place.

**Comment by aczechowski** [comment]
Supposedly a message center post went out recently to applicable tenants with some additional information on this topic. But in response to your questions:

> Does the ODJ connector need to updated for current deployments for it to continue working past September 2022

Currently, yes.
(Personally, I'd suggest that it's a good practice to keep things like .NET up to date regardless, unless there are other dependencies with a hard version requirement.)

> Could you clarify why or why not the Intune Connector may or may not work for Autopilot using hybrid Azure AD deployments

It's ultimately due to the changes for TLS. Azure AD is taking new TLS requirements, so for the connector to support that, it requires the later .NET version.
