### ISSUE TITLE
Reports vs Monitoring

### ISSUE THREAD

**Issue by Warren-Stevens** [MicrosoftDocs/memdocs#3080]
Reports and monitoring have 2 different meanings, in this instance, there is a mention to view the reports under the Monitor section yet there is a Reports tab? 
The mentioned reports are misleading, they are views and not reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7024ad8-b24b-598c-8b16-2da8bc15e9e4
* Version Independent ID: 230e96a7-e771-e6dd-d5f4-ac8b514fb4d4
* Content: [Use Update Compliance reports for Windows Updates in Microsoft Intune - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/windows-update-compliance-reports)
* Content Source: [memdocs/intune/protect/windows-update-compliance-reports.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/windows-update-compliance-reports.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by Brenduns** [comment]
Closing this issue without further action.

Where the feedback is useful, but did not drive immeidate content change, the reporting structure for Intune has been overhualed, and this article is no longer in publication.  The reports are likley now direclty in reports.  If this issue persists, and we can improve the references of reporting _views_ vrs full fledged reports, please resubmit this request with reference to the current and recently updated reports in question.
