### ISSUE TITLE
Clarify note about Autopilot conversion

### ISSUE THREAD

**Issue by ajf8729** [MicrosoftDocs/memdocs#3082]
The following note is somewhat unclear, it reads as if you cannot assign a convert to Autopilot profile to existing hybrid AAD devices, for the goal of wiping them and running them through AAD-only Autopilot. Not sure if it's even needed to be mentioned.

"Converting all targeted devices to Autopilot isn't supported for transforming a hybrid Azure AD device into a Azure AD Autopilot device."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9c44d0-d5d9-54af-b98e-0f33e73879af
* Version Independent ID: b67acfdf-2640-9376-c588-cb251078fb91
* Content: [Configure Autopilot profiles](https://docs.microsoft.com/en-us/mem/autopilot/profiles)
* Content Source: [memdocs/autopilot/profiles.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/profiles.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ajf8729, see #2175 which was the origin of this note. That at least provides the historical context.
I'll keep this issue open for our team to review the note to see if we can clarify how it's worded.

**Comment by ajf8729** [comment]
I also found this Tech Community post that seems to agree that it should work https://techcommunity.microsoft.com/t5/microsoft-intune/auto-pilot-for-existing-windows-devices/m-p/3064194

**Comment by rudyooms84** [comment]
> I also found this Tech Community post that seems to agree that it should work https://techcommunity.microsoft.com/t5/microsoft-intune/auto-pilot-for-existing-windows-devices/m-p/3064194

Yep... written by a Microsoft guy.. so I assume he knows what he is talking about :)

**Comment by frankroj** [comment]
Thank you for the feedback @ajf8729. We recently updated the wording on this note. Please let me know if this answers your question or if you need additional clarification.

**Comment by ajf8729** [comment]
Hey Frank, I don't seem to see any changes to the wording.

**Comment by frankroj** [comment]
This is being fixed in https://github.com/MicrosoftDocs/memdocs-pr/pull/10144. We are changing the wording to:

Using the setting **Converting all targeted devices to Autopilot** doesn't automatically convert existing hybrid Azure AD device in the assigned group(s) into an Azure AD device. The option only registers the devices in the assigned group(s) for the Autopilot service.

**Comment by frankroj** [comment]
@ajf8729 sorry for the long delay. This should be fixed in multiple places in the Autopilot docs. Some customers were confusing the option where they thought it meant that a hybrid Azure AD join device would "convert" to an Azure AD join device if this option was selected. This was not the case, and the note was meant to clarify this. We have changed the wording in the note to simply say the following, and clarify that this option just simply **registers** the devices in the group for the Autopilot service and really doesn't do any type of "converting" (well I guess it does convert a non-Autopilot device to an Autopilot device). Once I get some approvals on these changes, the updates should be reflected in the docs.

**Comment by ajf8729** [comment]
That's great, thanks!

**Comment by frankroj** [comment]
Waiting on PM to approve changes and then I will sign off.
