### ISSUE TITLE
Multiple Intune connectors

### ISSUE THREAD

**Issue by ShehzadUIT** [MicrosoftDocs/memdocs#31]
This document says that you can have multiple Intune connectors configured but when i configure a 2nd Intune connector, both Intune connectors would stop working I.e. domain join the Autopilot devices in a hybrid AD join scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a94c428-95df-632b-46e8-4386ad551a03
* Version Independent ID: f23998f0-52ff-1203-1a0c-ff5c25b08c1c
* Content: [Enrollment for hybrid Azure AD-joined devices - Windows Autopilot](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-autopilot-hybrid#feedback)
* Content Source: [memdocs/intune/enrollment/windows-autopilot-hybrid.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-autopilot-hybrid.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with pm...

**Comment by ShehzadUIT** [comment]
any update?

**Comment by ErikjeMS** [comment]
@ShehzadUIT Nothing yet.

**Comment by ErikjeMS** [comment]
@ShehzadUIT The PM responded with: "That should not be an issue.  Is it possible when setting up the second connector they didn't delegate the rights properly?  If so, since the connectors don't really load balance (first one to poll wins) it is quite possible that the same connector "wins" every time."
Can you open a support ticket to get specific help on this? - [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support).
