### ISSUE TITLE
What happened to the URL - https://support.microsoft.com/en-us/help/2583929/best-practices-for-intune-software-distribution-to-windows-pc

### ISSUE THREAD

**Issue by owaisfarooqui-MEM** [MicrosoftDocs/memdocs#3110]
What happened to the URL - https://support.microsoft.com/en-us/help/2583929/best-practices-for-intune-software-distribution-to-windows-pc

This used to provide useful information about best practices for Intune software distribution on Windows but now it redirects to https://docs.microsoft.com/en-US/mem/intune/fundamentals/intune-legacy-pc-client which does not make any sense. Please fix the broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee6afb0-4bf9-137d-6bea-31f8f24e4621
* Version Independent ID: 329e2906-be94-871d-e0c8-1fc035e8c258
* Content: [Legacy Intune PC software client](https://docs.microsoft.com/en-US/mem/intune/fundamentals/intune-legacy-pc-client)
* Content Source: [memdocs/intune/fundamentals/intune-legacy-pc-client.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/intune-legacy-pc-client.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by yogkumgit** [comment]
@Smritib17 Please help us in resolving this issue. Thanks

**Comment by owaisfarooqui-MEM** [comment]
There has been no update on this issue. What is happening?

**Comment by Smritib17** [comment]
@owaisfarooqui-MEM , thanks for this feedback. I've run this past our team for a check. The original article was redirected because it was based on the legacy PC client (The PC client is no longer supported).  
Perhaps, this article might be useful: [Support Tip: Troubleshooting MSI App deployments in Microsoft Intune - Microsoft Tech Community.](https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-troubleshooting-msi-app-deployments-in-microsoft/ba-p/359125)
