### ISSUE TITLE
"then redeploy the profile"

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/memdocs#3202]
In the section ["Delete device record in Intune before reusing devices in self-deployment mode or Pre-Provisioning mode"](https://learn.microsoft.com/en-us/mem/autopilot/known-issues#delete-device-record-in-intune-before-reusing-devices-in-self-deployment-mode-or-pre-provisioning-mode) it mentions "then redeploy the profile"; but does not specify how one might do this. Typically it is advised to use a combination of tags and dynamic Azure AD groups to assign devices to Autopilot profiles, so how does one "redeploy the profile" if such a manual action is not possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2da4bbd-faa6-e6d5-07c1-946f5f7da2f5
* Version Independent ID: d1040d9e-7e73-b308-65a1-e141f07ed2dc
* Content: [Windows Autopilot known issues](https://learn.microsoft.com/en-us/mem/autopilot/known-issues)
* Content Source: [memdocs/autopilot/known-issues.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/known-issues.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @webash. I apologize for the long time it took to respond back to this feedback item. I agree that this item was not well worded. You don't redeploy an Autopilot profile. Your redeploy a device so that it reruns the Autopilot deployment. I have reworded so that it makes more sense. The changes should go live in the next day or two. If you have any additional feedback, please open a new feedback item.
