### ISSUE TITLE
PROVISIONTS - No mention of TS Deployment to "All Provisioning Devices" collection.

### ISSUE THREAD

**Issue by oingobo** [MicrosoftDocs/memdocs#3204]
[Enter feedback here]
Unless I'm mistaken, the TS we want the device to provision with must be deployed to the "All Provisioning Devices" collection.  I'm troubleshooting why in my environment the TS always fails to run during AutoPilot and found this article to be missing a critical piece.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d357b7c2-6e7c-eb8b-2912-703829a70581
* Version Independent ID: d357b7c2-6e7c-eb8b-2912-703829a70581
* Content: [How to enroll with Autopilot - Configuration Manager](https://learn.microsoft.com/en-us/mem/configmgr/comanage/autopilot-enrollment)
* Content Source: [memdocs/configmgr/comanage/autopilot-enrollment.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/comanage/autopilot-enrollment.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @gowdhamankarthikeyan
* Microsoft Alias: **gokarthi**

**Comment by frankroj** [comment]
Thank you for the feedback @oingobo. The ConfigMgr client.msi property of PROVISIONTS listed in the page is linked back to the description of this property that lists all of the instructions on how to use this property. This includes instructions regarding needing to deploy to All Provisioning Devices:

https://learn.microsoft.com/en-us/mem/configmgr/core/clients/deploy/about-client-installation-properties#provisionts

2. Deploy this task sequence to the new built-in collection, All Provisioning Devices. Note the task sequence deployment ID, for example PRI20001.

I am going to ahead and close this feedback item since there is no actionable items from the doc team at this time.
