### ISSUE TITLE
Retire applications

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#321]
Hi, this page is titled "update and retire applications....." but it doesn't mention Retiring applications in the content.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22d26803-00ca-e52a-f2f7-a4bceff7fc29
* Version Independent ID: f066363c-10f7-ed27-6a2e-c6d937a28822
* Content: [Update and retire applications - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/update-and-retire-applications)
* Content Source: [memdocs/configmgr/apps/deploy-use/update-and-retire-applications.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/update-and-retire-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PaulKlerkx, there's no action in the product to "retire" an app. That term is just used here to conceptually group the supersede and uninstall actions, which the article summarizes.

**Comment by PaulKlerkx** [comment]
I am confused by that answer.  If you right click an application in Microsoft endpoint configuration manager, you can definitely choose “Retire”. Is this page not about MECM applications?

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for correcting me! I was mistaken. You can read what we have about the "retire" action in the [management tasks for apps](https://docs.microsoft.com/mem/configmgr/apps/deploy-use/management-tasks-applications#manage-applications) article.

I'm debating the overall value of this "update-and-retire-applications" article, as it's really just an index of various actions with pointers elsewhere. So instead of adding something about "retire" to this article, I'll just remove it. I don't think it provides much value.

Thanks for the feedback, and thanks again for correcting my mistake 😄

**Comment by aczechowski** [comment]
I put in a change to remove the article and tidy up, it should publish live later today.

**Comment by PaulKlerkx** [comment]
Ok, thank you for getting back to me and the link to information about retiring applications.
