### ISSUE TITLE
Instructions "To Enable Microsoft Defender for Endpoint" is out of date

### ISSUE THREAD

**Issue by RVAHaver01** [MicrosoftDocs/memdocs#3261]
Specifically 3.a.  There is no Advanced features link in the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24fa182f-ace6-e7e2-ff98-91951be7d10e
* Version Independent ID: f1acb398-6d69-b91c-5ee0-3da3bbf7809f
* Content: [Configure Microsoft Defender for Endpoint in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-configure?source=docs)
* Content Source: [memdocs/intune/protect/advanced-threat-protection-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/advanced-threat-protection-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@RVAHaver01 Thank you for your feedback. I was able to test it in multiple tenants and the navigation instructions are accurate

![image](https://user-images.githubusercontent.com/45987684/196420195-340e78a1-4955-4735-a02f-72cee02a87e0.png)


In case you continue to have issues accessing advanced features, I'd recommend opening a support ticket via the need help section on the admin center so that our support engineer can assist in resolving this issue.

Hope this helps!

Thanks
Sri
