### ISSUE TITLE
wrong option mentioned

### ISSUE THREAD

**Issue by koenraadrens** [MicrosoftDocs/memdocs#328]
For a task sequence that installs an OS image, don't use the deployment option to Download content locally when needed by the running task sequence. When the task sequence wipes the disk before it applies the OS image, it removes the client cache. Since the content is gone, the task sequence fails.

I think it's the other option which wouldn't work for an OS Image 'Download all content locally before starting task sequece'
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85202b8-4198-2bda-e55f-48ef2db6768f
* Version Independent ID: 676fa801-586d-90d2-9c2a-2411ab35abc4
* Content: [Configure pre-cache content - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/configure-precache-content)
* Content Source: [memdocs/configmgr/osd/deploy-use/configure-precache-content.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/osd/deploy-use/configure-precache-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @koenraadrens, I provided a [detailed answer](https://github.com/MicrosoftDocs/SCCMdocs/issues/2114#issuecomment-606183160) on a similar question earlier this year.

**Comment by koenraadrens** [comment]
I still think the NOTE is wrong.

This is the note in the documentation:

For a task sequence that installs an OS image, don't use the deployment option to Download content locally when needed by the running task sequence. When the task sequence wipes the disk before it applies the OS image, it removes the client cache. Since the content is gone, the task sequence fails.

But "Download content locally when needed" is the only option available. And the note says don't use that option. I think you just need to remove the note in the documentation. It's wrong and in the latest version you can't even choose the other option anymore. 
dynas2001 said the same

**Comment by aczechowski** [comment]
I'll double-check with engineering, but I'm not aware of any recent changes that would have removed that option. As I mentioned in my other response, those options are dynamic depending upon the type of deployment.

**Comment by aczechowski** [comment]
I'm waiting to hear back from engineers, but in the meantime, look at the [Deploy task sequence](https://docs.microsoft.com/mem/configmgr/osd/deploy-use/deploy-a-task-sequence) article, and search for "deployment options." The three possible options are listed, with criteria for them to display or not. So if your task sequence is made available to PXE/boot media deployments, the second option isn’t shown. If you haven’t enabled all packages to use a package share, the third option isn’t shown. And the first option doesn't work with pre-caching, because of how the task sequence manages content and wipes the disk. That's from the doc bug that engineering filed to me last year (reference MicrosoftDocs/SCCMdocs#1338).

For example, a simple task sequence with only **Install Package** steps, deploy it as **Available**, and make available to **Only Configuration Manager clients** (which is the only option, I think because this task sequence isn't for OSD, in other words, it doesn't have a boot image associated with it), on the Distribution Points page of the wizard, these are the deployment options:

![image](https://user-images.githubusercontent.com/26784733/83777055-cf56a780-a63d-11ea-9557-594a845fd504.png)
This screenshot is with the most recent version of the product. The third option is listed because the reference package is enabled for a distribution share.

For an OSD task sequence that wipes the disk and installs the OS, if on the Deployment Settings page I make it available to **Only Configuration Manager clients**, then on the Distribution Points page, there are two options available:

![image](https://user-images.githubusercontent.com/26784733/83777856-c4504700-a63e-11ea-8f56-19f416fa01fd.png)
The third is not available because not all content in this task sequence is available on distribution shares.

If I change the deployment setting to make it available to include PXE/media, back on the Distribution Point page, there is only one deployment option:

![image](https://user-images.githubusercontent.com/26784733/83777975-ed70d780-a63e-11ea-913f-6984098b75bf.png)


So...given the multiple comments on this note over the past several months, how to best get this point across in the documentation. 😄 What if I put in a reference from this note to the list of deployment options, to further clarify the point that the deployment options are dynamic. I may even take some of the above explanation and add to the other article with the list of deployment options to help explain scenarios where they display or not. Do you think that will help clarify and tie things together?

**Comment by aczechowski** [comment]
FYI, I revised the warning in this article, and made a big updates to the [Deploy task sequence](https://docs.microsoft.com/mem/configmgr/osd/deploy-use/deploy-a-task-sequence) article section on deployment options. Thanks for the feedback, I hope this revision will help clarify for others. The changes should publish live tomorrow morning.
