### ISSUE TITLE
Outdated link(s) on "Windows Autopilot networking requirements"

### ISSUE THREAD

**Issue by pogarek** [MicrosoftDocs/memdocs#3293]
This page is not up to date.
From my investigation, https://login.live.com is not used.
The conversation starts with account.live.com (more precisely: https://account.live.com/disambiguationpage?mkt=en-US&hasngc=0&platform=Windows10&uiflavor=Win10) 

May I ask to update this page with relevant / updated endpoints, that should be unblocked in firewalls/proxies?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82c5b872-c031-9ed9-c4cc-c8a1a8e93e0a
* Version Independent ID: ac837825-11e3-cf43-7516-0d94b496a59f
* Content: [Windows Autopilot networking requirements](https://learn.microsoft.com/en-us/mem/autopilot/networking-requirements)
* Content Source: [memdocs/autopilot/networking-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/networking-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by frankroj** [comment]
Thank you for the feedback @pogarek. There are many different Autopilot scenarios and many different types of environments. The specific scenario that you tested for may have not used that URL, but there are other scenarios that may use it. For this reason we aren't removing the URL since it may be used under certain circumstances.
