### ISSUE TITLE
Configuration steps for Intune Portal is invalid due to Open SSL 1.1 requirement

### ISSUE THREAD

**Issue by johanlindfors** [MicrosoftDocs/memdocs#3328]
The solution provided in this page doesn't work since open ssl 1.1 has been deprecated but is still a requirement for the Intune portal.

/Johan

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Version Independent ID: 80924804-c247-d3bb-2245-fd3db3f3bd62
* Content: [Get the Microsoft Intune app for Linux](https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux)
* Content Source: [memdocs/intune/user-help/microsoft-intune-app-linux.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/microsoft-intune-app-linux.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @johanlindfors, thank you for reaching out to the Microsoft Intune Docs team. I am looking into your question and will follow up shortly. CC @yogkumgit

**Comment by benferse** [comment]
Hi @johanlindfors - which section are you referring to?

OpenSSL 1.1 is only a requirement for the Ubuntu 20.04 version of the Intune app, since 20.04 is an LTS release and doesn't have any plans to migrate to OpenSSL 3.0 before the support window ends (as far as I have heard). The Intune app for Ubuntu 22.04 targets OpenSSL 3.0.

**Comment by johanlindfors** [comment]
Ok, thanks for responding. I have now managed to install the Intune app on 22.04.

**Comment by UsersHaveNames** [comment]
I have a similar problem even though this is closed (hopefully It is not considered as a duplicate at this point), here:
[/MicrosoftDocs/memdocs/issues/3811](https://github.com/MicrosoftDocs/memdocs/issues/3811)

I have Ubuntu 22.04 installed as you can see in the issue that I have opened and the below fails:
`sudo apt install intune-portal`

because of:
```
intune-portal : Depends: msalsdk-dbusclient (>= 1.0) but it is not going to be installed
Depends: libssl1.1 (>= 1.1.0) but it is not installable
```

Than the below fails:
`sudo apt install msalsdk-dbusclient`

because of:
`msalsdk-dbusclient : Depends: libsdbus-c++0 (>= 0.8.3) but it is not installable`
