### ISSUE TITLE
"Convert all targeted devices to Autopilot", does it mean a reset ?

### ISSUE THREAD

**Issue by rlabinot** [MicrosoftDocs/memdocs#3383]
Hello there,

Just a question after reading the documentation about the "Convert all targeted devices to Autopilot" option when creating an autopilot profile.

I would like to know if this option will reset the existing hybrid Azure AD joined devices ? This seems not clear to me.
I want to avoid the reset of an used device.

Thank you for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9c44d0-d5d9-54af-b98e-0f33e73879af
* Version Independent ID: b67acfdf-2640-9376-c588-cb251078fb91
* Content: [Configure Autopilot profiles](https://learn.microsoft.com/en-us/mem/autopilot/profiles)
* Content Source: [memdocs/autopilot/profiles.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/profiles.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @rlabinot. We recently updated the statement in this article to better explain what this option does. The option doesn't do anything with existing devices. It just registers the device with the Autopilot service so that it has the ability to run an Autopilot deployment. It doesn't actually convert anything on the device itself. I hope this info helps.
