### ISSUE TITLE
how do i uninstall company portal on mac?

### ISSUE THREAD

**Issue by mkliu** [MicrosoftDocs/memdocs#342]
Need instructions on how do i uninstall company portal on mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515d32cb-c6b5-7487-347c-f4134291ce3d
* Version Independent ID: 1d0312aa-9068-19c4-9309-97606169ba56
* Content: [Unenroll your macOS device from Intune Company Portal](https://docs.microsoft.com/en-us/mem/intune/user-help/unenroll-your-device-from-intune-macos)
* Content Source: [memdocs/intune/user-help/unenroll-your-device-from-intune-macos.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/unenroll-your-device-from-intune-macos.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @mkliu, thank you for the idea. I'm looking into these steps for you.

**Comment by lenewsad** [comment]
Hi @mkliu, I updated the macOS enrollment article with the steps to uninstall the Company Portal app. Those changes will be live after 10 AM PST on 1/8/2021. Thanks again for your contribution to the Intune docs!

**Comment by noelesp** [comment]
@lenewsad I've followed the instructions to uninstall and those work fine. However, when I tried to re-enroll I ran into an issue where the enrollment doesn't work and the Company portal app just spins and spins. The issue is documented here --> https://www.reddit.com/r/Intune/comments/hxu47y/issue_with_macos_and_device_reenrollment/

I was finally able to re-enrolled by going into my Keychain Access search for "Company" and remove the entries for com.Microsoft.CompanyPortal.enrollment (there were 3 in my case, not sure if these entries should be deleted during the uninstallation process!)

Hope this helps someone!

Thanks,

**Comment by Aaron-Provoke** [comment]
> 
> 
> @lenewsad I've followed the instructions to uninstall and those work fine. However, when I tried to re-enroll I ran into an issue where the enrollment doesn't work and the Company portal app just spins and spins. The issue is documented here --> https://www.reddit.com/r/Intune/comments/hxu47y/issue_with_macos_and_device_reenrollment/
> 
> I was finally able to re-enrolled by going into my Keychain Access search for "Company" and remove the entries for com.Microsoft.CompanyPortal.enrollment (there were 3 in my case, not sure if these entries should be deleted during the uninstallation process!)
> 
> Hope this helps someone!
> 
> Thanks,

omg, this solved my re-enrollment problem! Removing the company entries from Key chain fixed the spinning icon in Company Portal.

**Comment by lenewsad** [comment]
Thanks @noelesp! I'm so glad that info was out there to help you. I'll take this to our product team so they're aware and see if we can get that info added to our docs ASAP.
