### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/memdocs#3444]
When I look at my available apps, I don't see Intune Enrollment, I do see Microsoft Intune, is this the same app or something different? If the same, please correct the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f28c4b3-8ccc-e353-2ead-65c4022b437a
* Version Independent ID: 643425fd-9969-6322-0735-2bffb125cefc
* Content: [Require multifactor authentication for Intune device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/multi-factor-authentication?toc=%2Fazure%2Factive-directory%2Fconditional-access%2FTOC.json)
* Content Source: [memdocs/intune/enrollment/multi-factor-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/multi-factor-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @DeanGross, thank you for reaching out to the Microsoft Intune Docs team. _Microsoft Intune_ and _Microsot Intune Enrollment_ are 2 different options. The app picker only lists a certain number of apps at a time, so that might be why the Microsoft Intune Enrollment app isn't visible right away. Use the search bar to look up Microsoft Intune Enrollment. It should come right up.   

I just added this information to the article, because I think it's helpful to know. You'll see those changes shortly.  Thanks for your contribution!
