### ISSUE TITLE
Delay in promoting a new licensed user

### ISSUE THREAD

**Issue by JonNieminen** [MicrosoftDocs/memdocs#348]
You might want to add to the documentation that a newly created/licensed user account takes approximately 30 minutes before you can promote it to a DEM account. If you try this immediately after licensing the new user you get an error saying "An error occurred. This user is not licensed Request ID: x-x-x-x".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7786d9c0-55b0-9bff-fc0a-f4ee70ee0615
* Version Independent ID: cf0c17a0-fdc7-e0af-db82-913e36d2ec7c
* Content: [Enroll devices using a device enrollment manager account - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll?source=docs)
* Content Source: [memdocs/intune/enrollment/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7402141)

**Comment by ErikjeMS** [comment]
@JonNieminen The PM tells me there can be latency, but he hasn't experienced that long of one. Can you contact support and give them your specific information to see if they can help you reduce it? Using support will also get this issue in the support documentation escalation queue if it turns out to be a recurring issue (and not an isolated one). 
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support. 
You can also use these additional channels for help:
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
