### ISSUE TITLE
Adding additional 3rd party SCEP service to Documentation 

### ISSUE THREAD

**Issue by igalfsg** [MicrosoftDocs/memdocs#3526]
Hi Brent, 

What is the process to add EZCA as a 3rd party SCEP service for intune https://docs.keytos.io/azure-pki/intune-certificate-authority/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cda83a64-56ae-a632-dc81-dfd1a03984c1
* Version Independent ID: b93da48e-4097-4c3a-f6c8-02a5c4e0a616
* Content: [Use third-party certification authorities (CA) with SCEP in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/certificate-authority-add-scep-overview)
* Content Source: [memdocs/intune/protect/certificate-authority-add-scep-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/certificate-authority-add-scep-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@igalfsg Thank you for your feedback. Since it is a 3rd party SCEP service, it needs to go through internal approval before it gets documented. I'd recommend you leave the feedback on our main feedback portal (https://feedbackportal.microsoft.com/ ) so that a dev/Product engineer will review and provide an update.

Hope this helps!

Thanks
Sri
