### ISSUE TITLE
Deploy Windows 10/11 on an existing Windows 7 or 8.1 device

### ISSUE THREAD

**Issue by mushmasha** [MicrosoftDocs/memdocs#3551]
In a table-guide with scenarios and Windows Autopilot modes in a line with  existing devices it says "Deploy Windows 10/11 on an existing Windows 7 or 8.1 device", but in the detailed article on Support for existing devices it says "Windows Autopilot for existing devices lets you reimage and provision a Windows 8.1" and there is no mention on Windows 7. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36268637-e328-8b14-60ed-3438a32a223d
* Version Independent ID: 71996105-56e3-3785-51cc-d74f2e9dd83b
* Content: [Windows Autopilot scenarios and capabilities](https://learn.microsoft.com/en-us/mem/autopilot/windows-autopilot-scenarios)
* Content Source: [memdocs/autopilot/windows-autopilot-scenarios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/windows-autopilot-scenarios.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @mushmasha. Windows 7 has been out of support for several years now. It's very possible that articles were updated to remove Windows 7 information from them and that this article was missed. It's not really relevant though since at this point, there shouldn't be any Windows 7 devices in a supported environment.

At this point, Windows 8.1 is also out of support. We plan to update this article in the future to also remove Windows 8.1 from the article and generalize the scenario more. However we also understand that some customers may still be in the process of upgrading from Windows 8.1 since it did just recently go out of support (unlike Windows 7 which has been out of support for several years.



We actually just released some updated docs on the Autopilot for existing devices scenario and you will see no mention of either Window 7 or Windows 8.1, but instead goes over the scenarios where Autopilot for existing devices can be used:

https://learn.microsoft.com/mem/autopilot/tutorial/existing-devices/existing-devices-workflow

I am going to go ahead and remove Windows 7 from this article to avoid any confusion.
