### ISSUE TITLE
no options for Chromebook

### ISSUE THREAD

**Issue by GeneralWinter101** [MicrosoftDocs/memdocs#3560]
Hi,

How can I add my organization-provided Chromebook to safe devices, so that I can sync my documents, save and print them if I need to?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfb6a39-013e-7ca3-8133-9617458ed9f2
* Version Independent ID: 35e0cece-eb65-53a8-0aed-3648ccae0e07
* Content: [What is device enrollment](https://learn.microsoft.com/en-us/mem/intune/user-help/use-managed-devices-to-get-work-done)
* Content Source: [memdocs/intune/user-help/use-managed-devices-to-get-work-done.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/user-help/use-managed-devices-to-get-work-done.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@GeneralWinter101 Thank you for your feedback. The options to enroll in Chromebooks at this point in time. You can leave your feedback on our main feedback portal ( https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472 ) so that the development or product group can provide you with timelines on when this will be available.

Hope this helps!

Thanks
Sri
