### ISSUE TITLE
Update a mobile app requires "Mobile apps/Create" if file (intunewin) has changed

### ISSUE THREAD

**Issue by BornToBeRoot** [MicrosoftDocs/memdocs#3577]
Hi,

if you want to give a user (only) the permission to update an existing application you have to give also the `Mobile apps/Create` permission. 

If the user has the following permissions:

```
Mobile apps\Read
Mobile apps\Update
Mobile apps\View reports
```

the user can change the properties of the app, but cannot upload a new file (intunewin).

It seems like the `Mobile apps/Create` is required to upload a new intunewin file. Either this is a bug and needs to be fixed or added to the documentation.... 

Also the `Mobile apps\View reports` is missing in the docs...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee559326-3f31-4a98-7399-21d571a42d9d
* Version Independent ID: 11eb7dee-44e1-d6bd-76c1-a6327199964d
* Content: [Create a custom role in Intune](https://learn.microsoft.com/en-us/mem/intune/fundamentals/create-custom-role)
* Content Source: [memdocs/intune/fundamentals/create-custom-role.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/fundamentals/create-custom-role.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@BornToBeRoot Thank you for your feedback. I shall review and update the missing information.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Please comment

**Comment by msbemba** [comment]
@BornToBeRoot Thank you for your feedback. We have added details about view reports via PR#https://github.com/MicrosoftDocs/memdocs/pull/3641

Once the author approves, the changes will be live.

Regarding the issue reported on Mobile apps/Create this sounds more like a bug on your tenant and we recommend you contact support via the need help section on the admin center, so that engineer can fix it or escalate it to the product group to be able to fix this.

Hope this helps!

Thanks
Sri

**Comment by BornToBeRoot** [comment]
@msbemba thanks!
