### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by ccall54** [MicrosoftDocs/memdocs#36]
Whenever I click to “enroll now,” the button redirects me to “choose an account” screen and the process repeats over and over again. Suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0cd5875-7172-2544-24d6-495aff701d2d
* Version Independent ID: 7c59e41f-8802-ed50-83e5-4cb21ddf593a
* Content: [Install and sign in to the Company Portal app for iOS](https://docs.microsoft.com/en-us/mem/intune/user-help/install-and-sign-in-to-the-intune-company-portal-app-ios#feedback)
* Content Source: [memdocs/intune/user-help/install-and-sign-in-to-the-intune-company-portal-app-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/install-and-sign-in-to-the-intune-company-portal-app-ios.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @ccall54! Thanks for your question and I'm sorry you're having to deal with that. It definitely sounds like something is off because when you sign in with your school or work account you should start seeing the enrollment prompts. Just to make sure you have them, here are the enrollment steps for iOS and Android. 

* [ Set up iOS devices access to your company resources](https://docs.microsoft.com/mem/intune/user-help/enroll-your-device-in-intune-ios)
* [Enroll your Android device with COmpany Portal](https://docs.microsoft.com/mem/intune/user-help/enroll-device-android-company-portal)

If the app continues to send you in a loop, then I recommend reaching out to your organization's IT or support person for help. I think reaching out to your support person is going to be the best route but here are a couple other support options for you to explore:  
  
- Post on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.   
  
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.   
  
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   
  
I'm closing this issue as there's nothing actionable for docs at this time.
