### ISSUE TITLE
Contradictory or incomplete data

### ISSUE THREAD

**Issue by Tharien** [MicrosoftDocs/memdocs#3636]
The data in the article here:
https://learn.microsoft.com/en-us/mem/autopilot/autopilot-mbr

is in contradiction to this FAQ article for Autopilot.
https://learn.microsoft.com/en-us/mem/autopilot/autopilot-faq

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1b12323-90a7-00db-16ea-8daec3a9306f
* Version Independent ID: 0c1a1865-cf35-0862-b328-02371bb30441
* Content: [Windows Autopilot FAQ](https://learn.microsoft.com/en-us/mem/autopilot/autopilot-faq)
* Content Source: [memdocs/autopilot/autopilot-faq.yml](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/autopilot-faq.yml)
* Product: **w10**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @Tharien. Can you please clarify what specifically is in contradiction. These are both long articles so narrowing down what you feel specifically is in contradiction will help us research the issue and if needed, resolve.

**Comment by frankroj** [comment]
@Tharien I am going to go ahead and close this feedback item out since there is not the required detail I need to take action. If this is still an issue, please open a new feedback item with as much detail as possible with what you feel is in contradiction, including examples of sections and text. Thank you.
