### ISSUE TITLE
Automated cellular plan update command

### ISSUE THREAD

**Issue by Sifpils** [MicrosoftDocs/memdocs#3645]
Will this command work on Shared iPad (supervised device)? Cellular is not present as an option in the Settings app for Shared iPad, but it would be interesting if we could manage it on these devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8e7fe70-e9b0-a64c-201a-33f7149bd49b
* Version Independent ID: 60585273-e6d5-24de-0d45-c29462cd6e0c
* Content: [Update cellular data plan for iOS/iPadOS devices with Microsoft Intune](https://learn.microsoft.com/en-US/mem/intune/remote-actions/update-cellular-data-plan)
* Content Source: [memdocs/intune/remote-actions/update-cellular-data-plan.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/remote-actions/update-cellular-data-plan.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @Smritib17
* Microsoft Alias: **smbhardwaj**

**Comment by msbemba** [comment]
@Sifpils Thank you for your feedback. Currently, it is not possible to manage it on Shared IPad. However, since it is in preview, I'd recommend you leave our valuable feedback on our main feedback portal - [Microsoft Intune · Community](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472), So that our dev/product engineers can review and respond.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@Sifpils Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
