### ISSUE TITLE
RHEL 9

### ISSUE THREAD

**Issue by narayankumargupta** [MicrosoftDocs/memdocs#3722]
[Is currently RHEL 9 supported ? If not, when will it be supported ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8df9199b-37e9-34d9-c440-97cf4f9ca109
* Version Independent ID: 8352cc27-2887-715e-4809-77520a5b5054
* Content: [Identify the prerequisites to install and use the Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-prerequisites)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-prerequisites.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@narayankumargupta Thank you for your feedback. Currently, it is not supported, however, you can leave your feedback on our Intune community ([Microsoft Intune · Community](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472))  so that our product or dev engineers can provide you an update.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@narayankumargupta  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
