### ISSUE TITLE
Jamf deprecating this feature

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/memdocs#3747]
Jamf say they are moving away from supporting the Cloud Connector but I can't see anything about it in the Microsoft Docs https://learn.jamf.com/bundle/jamf-pro-documentation-current/page/Conditional_Access.html

It would be useful to have a warning on this page, or even better some updated guidance on how to manage compliance in Intune now Jamf are not supporting integration

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f67001f-59b4-e47b-1704-de9ef7b7634c
* Version Independent ID: 46013e0e-5b73-1943-8ba2-37c1b6e7ab1a
* Content: [Use Intune compliance and Azure AD Conditional Access policies with Jamf Pro - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/conditional-access-assign-jamf)
* Content Source: [memdocs/intune/protect/conditional-access-assign-jamf.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/conditional-access-assign-jamf.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@thommck Thank you for your feedback. Sorry about the confusion,  I have got this clarified with the product team and Conditional Access in the Jamf message isn’t Azure AD Conditional Access. So no changes in the current integration and it will continue to work. We hope to get them to clarify as soon as possible on their end.

Hope this helps!

Thanks

Sri

**Comment by pamcdo** [comment]
Hey there,

the docs on integrating jamf with intune for compliance device support are now no longer valid. You can no longer configure the conditional access setting in jamf pro and have to do it via the device compliance option in jamf and utilize the intune device compliance partner feature (see attached image).

![Screenshot 2023-04-10 at 4 06 02 PM](https://user-images.githubusercontent.com/48225667/230988206-a23d3117-bc83-4020-81ba-dc35f2c279ed.png)

This is the new method to do it in the device compliance section: https://learn.jamf.com/en-US/bundle/jamf-pro-documentation-current/page/Device_Compliance.html

**Comment by msbemba** [comment]
@pamcdo 

The Jamf doc says that Jamf is ending support for the partner device management (PDM) flow since they recently added support for the newer partner compliance management (PCM) flow for macOS in Jamf Pro. However, since their feature that uses the PDM flow is called “Conditional Access” while their feature that uses the PCM flow is called “Device Compliance”, the message in their document is confusing. Also, the “(estimated removal date: late 2023)” is no longer accurate, 

We haven’t produced any Microsoft-side docs since we don’t have dates on deprecating anything from the Intune side, and the date for Jamf to end support for the PDM/”Conditional Access” flow is still uncertain. Once Jamf’s end-of-support date gets finalized we will update the documents.

So the Jamf Cloud Connector is not being deprecated. and the Jamf Pro Conditional Access feature is being replaced by the Jamf Pro Device Compliance feature.

Hope this helps!

Thanks
Sri
