### ISSUE TITLE
Azure Active directory Tenants - cmg applications

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#390]
Hi, not sure what part of the CMG documentation this should be, however once you configure a CMG, you have two entries under 
Administration - Cloud Services - Azure Acitve Directory Tenants - _Tenant name_ - Applications
One called ConfigMgr Client Application 
One called ConfigMgr Server Application

I would like to see more information about these entries.  
E.G. 
right clicking client doesn't appear to give any options - assuming that is appropriate...
When I right click the Server application, I get two options, what exactly do these do?  can I break anything by running them?
the options are 

- Renew Secret Key (sounds self explanatory), if I run it, do I need to modify anything else as well or does MECM make any required modifications?

- Update application settings - choosing this returns a window "This action updates the Azure AD web app with the latest configuration Manager Settings.  These settings include reading directory data and enabling an Azure AD device token.  Do you want to continue?

For this second option, I am MECM Admin, but have no access to azure side, If I run this, will it work or do I need to be MECM admin plus azure global admin..subscription admin too maybe??  could my lack of azure access cause part to be updated and part to fail causing CMG to become unusable?  When Should I use this option?

- 

(admin edit: moving article target)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639e477d-6e9d-a7b1-7978-f7d0f0283fc6
* Version Independent ID: 60b40c21-741b-42f8-a3e5-5f5a86811f59
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/azure-services-wizard)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @PaulKlerkx, those actions aren't specific to CMG, but for any Azure service connection in ConfigMgr. So the article on [Azure services](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/azure-services-wizard) is the general home for that. There's already a section there that talks about the **Renew secret key** action.

We should probably add something about the **Update application settings** action, but honestly I don't think there's much use of it. We talked about it once in [technical preview version 1905](https://docs.microsoft.com/mem/configmgr/core/get-started/2019/technical-preview-1905#bkmk_aadcollsync) as a way to refresh an existing app for new functionality. I don't think there's been an instance since in which it's been needed. It's possible you might use it in some troubleshooting circumstances. I'll double-check with engineering if I can get more details.

I'll also rehome this feedback to the Azure services article.

**Comment by aczechowski** [comment]
Thanks to @BeatrizMS2 who added a new section of the article to fix this issue.

(Internal reference MicrosoftDocs/memdocs-pr#3298)
