### ISSUE TITLE
Please specify something for LTSC

### ISSUE THREAD

**Issue by kbhalla1** [MicrosoftDocs/memdocs#3956]
This page doesn't specify whether Windows 10 Enterprise LTSC 2019 is supported or not.

However, I can see in the change logs that it is.

The problem with not specifically highlighting this is that MS support treats this as "since it's not listed, it's not supported". This is the situation we are in right now, trying to convince Support that they should not thrown out our support case just because it's not listed here explicitly.

Thank you for your time!

KB
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca6f1187-d749-6db2-d46f-1d1d60bbc289
* Version Independent ID: f8154992-4a7a-c0ff-5cd6-c691f7fa26d3
* Content: [Windows Autopilot software requirements](https://learn.microsoft.com/en-us/mem/autopilot/software-requirements#windows-10)
* Content Source: [memdocs/autopilot/software-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/software-requirements.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @kbhalla1. Support is correct when they said that LTSC isn't supported. In docs, we list what is supported, not what isn't support (with some rare exceptions). This is because the list of what isn't unsupported can literally be infinite. With versions of Windows, the list isn't quite infinite, but it's still a long list. Trying to put the versions of Windows that aren't supported would just clutter up the documentation and not make clear what is supported. As you have mentioned, going forward, you can assume that if something is not listed as supported, then its unsupported.

If you are seeing something about in change logs, then please send me the link. We most likely will change the change logs to clarify that LTSC isn't supported.

**Comment by kbhalla1** [comment]
Thanks for getting back to me @frankroj.

See this link here that clearly states in the notes that LTSC is supported.
https://github.com/MicrosoftDocs/memdocs/commit/82f906023332b6288ba3e307bc905719510de2de

**Comment by frankroj** [comment]
Thanks for getting me the link @kbhalla1. You are misinterpreting what this item is. This item really isn't a "change log" but a commit in GitHub to change something in the docs. I guess you can view it as a change log, but the change log is taking away support of LTSC, not adding it. The commit is not saying that LTSC IS supports, its saying that it WAS supported.

In this case the commit was for the following docs:

https://learn.microsoft.com/mem/autopilot/autopilot-faq
https://learn.microsoft.com/en-us/mem/autopilot/software-requirements
https://learn.microsoft.com/en-us/mem/autopilot/windows-autopilot

The red sections are what was removed, while the green sections are what was added/changed. We can clearly see that the statement about supporting LTSC was removed in the three articles. We can also see that the title of the commit is **remove LTSC support statements since this is not in the test matrix**. This change was done on Nov 12, 2021, so a year and a half ago. In other words, this change was done to specifically remove that LTSC was supported by Autopilot. For current supportability, you can't go by what the docs use to say, but what they currently say. Support requirements sometimes change as products change and mature, especially with a product like Autopilot that is constantly changing and evolving. New features may just simply not work in versions of Windows that were previously supported. You will find that all of the above 3 current docs make no mention of LTSC being supported.

Maybe it was supported in the past, but it's no longer supported. It could also be that the original docs were in error and they accidentally said it was supported when it wasn't. This commit could've been used to resolve/fix either of these two issues. I can also understand why it's not supported - Autopilot features are added and updated plus bugs are fixed via feature updates in Windows. LTSC doesn't receive feature updates - only security updates - so there is no way to update LTSC to fix issues with Autopilot or support the latest features of Autopilot. That is the drawback of using LTSC - the build remains at a constant version, but it receives no new features. That is the choices you need to make when deciding between LTSC and current branch - remain at a constant version but receive no new features, or constantly receive new features but run the risk of one of those new features affecting a business-critical system. This is why Microsoft only recommends LTSC for business-critical systems. End user devices should almost always be on current branch.

I also double checked with the Autopilot program manager and they confirmed that LTSC isn't supported.

**Comment by kbhalla1** [comment]
Thank you for your explanation. I was in fact reading the commit wrong.

I also appreciate you taking the time to explain the limitations of LTSC and how this could be counterintuitive from an Autopilot perspective. It all makes sense.

KB
