### ISSUE TITLE
Outdated Article

### ISSUE THREAD

**Issue by naumanmazhar** [MicrosoftDocs/memdocs#4010]
[Enter feedback here]
I have been working on MDE migration from ConfigMgr and GPO to Intune MDE and a lot of policies are now enhanced and update in MDE configuration but this article is still not updated. 

For Example the windows security experience settings within AV is fully available and working in MDE but this article still not updated. 
The ASR rules and ASR Exclusions are fully updated and working via MDE policy configuration but this article still not updated for ASR. 

Could you please review this article again and update with latest updates. thanks 

Regards, 
Nauman

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Version Independent ID: b166b931-f3f7-3323-7288-758cfa5934f1
* Content: [Use Intune to manage Microsoft Defender for Endpoint Security on devices not enrolled with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/mde-security-integration)
* Content Source: [memdocs/intune/protect/mde-security-integration.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/mde-security-integration.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@naumanmazhar   Thanks for the feedback. Hopefully things are falling into place this week. 
Last week the Defender for Endpoint *security settings configuration* feature received a major update detailed in the [What's New article here](https://learn.microsoft.com/mem/intune/fundamentals/whats-new#defender-for-endpoint-security-settings-management-enhancements-and-support-for-linux-and-macos-in-public-preview).  With this update, the content article has been updated and  now toggles between presenting the previous behavior and the new public preview behavior. This update has been completed with review from both the Intune and Microsoft Defender product teams.  

While the preview is refereed to as an opt-in preview, the opt-in requires enabling the use of *Preview features* from within the Microsoft 365 Defender portal – which means any tenant that already had that enabled will find they are using the new preview behavior without additional configurations. 

Of note, the Attack surface reduction policy profile of *Attack Surface Reduction Rules* is supported for both Intune and devices managed by only Defender (security settings configuration) – and this profile includes settings for *exclusions*. However, there is no profile for *ASR Exclusions* as its own ‘thing’.  For exclusions, previously undocumented but now fixed in the content is that settings for exclusions in ASR Rules profiles will not apply to devices that are only managed by Defender for Endpoint.  This is planned as future work so that those exclusions will apply.  

If you find exclusions that you set in your ASR Rules profiles are applying to devices not enrolled with Intune and only managed by Defender, please review all other sources of settings management, as they should not be enforced through these polices.  If the source isn’t found, please contact Support to have that investigated. 

As to the other noted policy/profiles: there are profiles for Antivirus policy via the *Microsoft Defender Antivirus exclusions* profile.  This profile is supported for devices managed by Intune as well as those managed only by Defender for Endpoint.  Similarly, with the new preview capabilities, *Windows Security Experience* profiles are also supported by both device management paths (Intune, and Defender only).
