### ISSUE TITLE
Untrusted Certificate when installing

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/memdocs#402]
Hi, when I create a deployment in MECM 2002, the install times out.  If I run the automatically created command line manually, I get a message "Do you want to run software from this untrusted publisher.  CN=Microsoft Corporation, O=Microsoft Corporation,L=Redmond, S=Washington, C=US and is not trusted on your system. Only run scripts from trusted publishers." .  I'm assuming this is related to the fact that the ps1 scripts are now signed.  Do I need to deploy a certificate via group policy prior to deploying edge now?  Are you able to include details on acquiring that cert on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b08c59-efa1-088a-b7d1-0e67e1f19281
* Version Independent ID: 60612563-0056-bdad-b145-c5c934c0cc1c
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/deploy-edge)
* Content Source: [memdocs/configmgr/apps/deploy-use/deploy-edge.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Hey @PaulKlerkx
I made a doc change a while ago which I believe answers this. Thanks much!

The Microsoft Edge installer and CMPivot are signed with the Microsoft Code Signing certificate. If that certificate isn't listed in the Trusted Publishers store, you'll need to add it. Otherwise, the Microsoft Edge installer and CMPivot won’t run when the PowerShell execution policy is set to AllSigned.
