### ISSUE TITLE
Option 1 needs clarification

### ISSUE THREAD

**Issue by tomattto2** [MicrosoftDocs/memdocs#4020]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

In the doc, under Option 1: Intune Company Portal there is a note that says
"These features aren't supported in Apple Setup Assistant authentication methods."

It's not clear what features its referring to.  Most of the features listed under Option 1 are also listed under Option 2(Setup Assistant with modern auth)  Could the note be removed or clarified so customers know what features from Option 1 are not supported in Option 2?  Can it be a table instead?  Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Version Independent ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Content: [Authentication methods for Apple automated device enrollment - Microsoft Intune](https://review.learn.microsoft.com/en-us/mem/intune/enrollment/automated-device-enrollment-authentication)
* Content Source: [memdocs/intune/enrollment/automated-device-enrollment-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/automated-device-enrollment-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@tomattto2  Thank you for your feedback. When you choose option 1 from the below

![image](https://github.com/MicrosoftDocs/memdocs/assets/45987684/00cb24d7-778f-42c8-9723-fd3b4f0fbf61) 

So that you can 

Use multi-factor authentication (MFA).
Prompt users to change their passwords when they first sign in.
Prompt users to reset their expired passwords during enrollment.
Register devices in Azure AD and use features available with Azure AD, such as conditional access.
Automatically install the Company Portal app during enrollment. If your company uses the Volume Purchase Program (VPP), you can automatically install Company Portal app during enrollment without user Apple IDs.
You want to lock the device until the Company Portal app installs.


**These features aren't supported when you authenticate by using Apple Setup Assistant.**

If you choose option 2, the authentication method is no longer the company portal, so it works.

Hope this helps!

Thanks
Sri

**Comment by tomattto2** [comment]
Thanks for the reply.  I still think the doc should be updated/clarified.  Because I'm still not sure exactly what features aren't supported, even after your reply.

- Matt on mobile

________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by tomattto2** [comment]
Outstanding!  Thank you so much!


-Matt
________________________________
