### ISSUE TITLE
Settings not showing 

### ISSUE THREAD

**Issue by NickBazinga** [MicrosoftDocs/memdocs#4022]
Endpoint security disk encryption policy - Configure the following settings in the BitLocker profile:

Hide prompt about third-party encryption = Yes
Allow standard users to enable encryption during Autopilot = Yes
Require Key File Creation = Allowed or Blocked
Recovery Password Creation = Allowed or Required

This settings aren't available at all or changed to something else 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by NickBazinga** [comment]
I would love to configure those settings but those settings aren't visible
at the configuration settings. Please check the configuration options for
"  * Startup Authentication Required, System Drive Recovery, or Fixed Drive
Recovery " , there is nothing with those names .

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder

**Comment by msbemba** [comment]
@NickBazinga  Thank you for your response. I can confirm that if I configure Fixed Drive Recovery, I can see all four options



![image](https://github.com/MicrosoftDocs/memdocs/assets/45987684/c1ef526b-0bf2-43f8-9494-e81f2e78b437)

![image](https://github.com/MicrosoftDocs/memdocs/assets/45987684/926b9fd2-0d54-4660-8f2c-56c9419c0066)


 If you continue to have issues, I'd recommend contacting support via the need help section so that a support engineer can assist you.

Hope this helps!

Thanks
Sri
