### ISSUE TITLE
Scope Tag Section missing

### ISSUE THREAD

**Issue by UjjwalKrBhakat** [MicrosoftDocs/memdocs#4075]
[Enter feedback here]
While going through with the Configure Autopilot profiles>
Create an Autopilot deployment profile document, I identified that some of the steps are missing, i.e. scope tags and even the screenshots are a bit older, please update the document with the latest screenshot and content.
Below screenshot for your reference:

![image](https://github.com/MicrosoftDocs/memdocs/assets/91897453/95b119e1-7628-4d00-b72e-ea328aee65ad)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9c44d0-d5d9-54af-b98e-0f33e73879af
* Version Independent ID: b67acfdf-2640-9376-c588-cb251078fb91
* Content: [Configure Autopilot profiles](https://learn.microsoft.com/en-us/mem/autopilot/profiles)
* Content Source: [memdocs/autopilot/profiles.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/autopilot/profiles.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @UjjwalKrBhakat. We are in the process of replacing some of this documentation with newer updated documentation. You can find that documentation here:

https://learn.microsoft.com/en-us/mem/autopilot/tutorial/autopilot-scenarios

In the new documentation we are avoiding using screenshots due to the constantly changing nature of Intune. In such an environment we would have to continuously update screenshots. Screenshots also can't be localized. Instead when things do change, its more of a matter of a quick text search and replace. This will also update the localized versions.

This doc will eventually be retired so there is no need to update. Just use the new documentation instead.
