### ISSUE TITLE
Option 3

### ISSUE THREAD

**Issue by gokulan-ey** [MicrosoftDocs/memdocs#4081]
[Enter feedback here]
When this option will be generally available? We are eagerly waiting for this to be GA to rollout in Production environment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Version Independent ID: 0dcb837b-adcd-ae49-8a10-1be81979f1ba
* Content: [Authentication methods for Apple automated device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/automated-device-enrollment-authentication)
* Content Source: [memdocs/intune/enrollment/automated-device-enrollment-authentication.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/automated-device-enrollment-authentication.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by msbemba** [comment]
@gokulan-ey Thank you for your feedback. We in the documentation team do not have the GA dates for this feature. I'd recommend you provide the feedback directly on our main feedback portal -[Microsoft Intune · Community](https://feedbackportal.microsoft.com/feedback/forum/ef1d6d38-fd1b-ec11-b6e7-0022481f8472) so that our dev or product engineers can answer it for you.

Hope this helps!

Thanks
Sri
