### ISSUE TITLE
"Allow users to reset device if installation error occurs"

### ISSUE THREAD

**Issue by timothy-lam** [MicrosoftDocs/memdocs#411]
for the option "Allow users to reset device if installation error occurs". if the user is not an administrator on the machine. while the "reset device" button is present, pressing it will prompt for admin credentials rendering the option pointless in most autopilot cases where the user is setting up the device themselves with no IT around. 

unless its not supposed to ask for admin credentials and its a bug or problem with my config...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ba0166-1d3c-40ca-a2f3-2954dcfe4411
* Version Independent ID: e07d50e2-7a95-868d-5800-ea548c84e884
* Content: [Set up the Enrollment Status Page - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/windows-enrollment-status?source=docs)
* Content Source: [memdocs/intune/enrollment/windows-enrollment-status.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/windows-enrollment-status.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
Investigating with PM...
(7518905)

**Comment by ErikjeMS** [comment]
@timothy-lam Here's the PM's response: It depends on where the error occurs.  If the error is during device ESP, then a reset should work fine (since OOBE runs with admin rights).  If the error is during user ESP, then it will only be possible if the user has admin rights.
If this doesn't answer your question, let me know and I'll reopen this issue.
