### ISSUE TITLE
Inconsistent licensing information

### ISSUE THREAD

**Issue by mchmav** [MicrosoftDocs/memdocs#4195]
Page suggests that Microsoft Intune Plan 1 subscription is required to use Microsoft Tunnel, however, the following page indicates that Microsoft Tunnel is only included in Microsoft Intune Plan 2 (https://www.microsoft.com/en-us/security/business/microsoft-intune-pricing). Which is it?!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8df9199b-37e9-34d9-c440-97cf4f9ca109
* Version Independent ID: 8352cc27-2887-715e-4809-77520a5b5054
* Content: [Identify the prerequisites to install and use the Microsoft Tunnel VPN solution for Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-prerequisites)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-prerequisites.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/microsoft-tunnel-prerequisites.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by msbemba** [comment]
@mchmav Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4205

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@mchmav I think the confusion is with Microsoft Tunnel and Microsoft Tunnel for Mobile Application Management (MAM). These are two different things (Well, one thing at the core, with MAM Tunnel being an add-on that requires additional licensing beyond the core Microsoft Tunnel).

Microsoft Tunnel is available via the Intune Plan 1 Subscription.
Microsoft Tunnel for MAM is an [add-on](https://learn.microsoft.com/en-us/mem/intune/fundamentals/intune-add-ons#microsoft-tunnel-for-mobile-application-management) that expands on Microsoft Tunnel, which is why it requires Intune Plan 2, in addition to having Plan 1.

Hope this helps!

Thanks
Sri

**Comment by mchmav** [comment]
Hi Sri

Thanks for the clarification which we'd also received via another channel. Our licensing documentation isn't very clear on this so perhaps this is something we can feed back to marketing?

Regards
Matt

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
