### ISSUE TITLE
Outdated video about Autopilot

### ISSUE THREAD

**Issue by anupamrulz** [MicrosoftDocs/memdocs#4222]
[Enter feedback here]
Outdated video about Autopilot
Kindly update a newer video with current look and feel of Intune

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71d61e5d-ef0c-5115-32dd-b847cd2896b8
* Version Independent ID: 71d61e5d-ef0c-5115-32dd-b847cd2896b8
* Content: [Windows Autopilot configuration requirements](https://learn.microsoft.com/en-us/autopilot/configuration-requirements)
* Content Source: [autopilot/configuration-requirements.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/configuration-requirements.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @anupamrulz. Because of the ever-changing nature of Intune and Windows, we have found that both videos and screenshots get outdated quickly. For this reason we are moving away from both videos and screenshots and going more towards detailed written instructions which can be easily updated when things change. You can find those at the following link:

https://learn.microsoft.com/en-us/autopilot/tutorial/autopilot-scenarios

There is also an updated video on the user experience for one of the scenarios at the following link:

https://learn.microsoft.com/en-us/autopilot/tutorial/user-driven/azure-ad-join-deploy-device#deploy-the-device

We are working on providing additional videos for the rest of the scenarios but it will probably be several months before they are all up.
