### ISSUE TITLE
Missing W11 22H2 Baselines - still

### ISSUE THREAD

**Issue by i-windows** [MicrosoftDocs/memdocs#4299]
[Enter feedback here]
Intune Security Baselines are still not updated, the Windows 10/11 Baseline is still from 2021, the updates have been promised for some time, but where are they? where is the W11 22H2 baseline? The document states that the existing baselines can be updated to a later version - but there are none to update too, its so frustrating

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c553157-31cf-faf9-0b4c-00f1a56f0545
* Version Independent ID: c91b6b7b-3264-f0f7-688e-baac0ce3a718
* Content: [Learn about Windows security baselines you can deploy with Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/security-baselines)
* Content Source: [memdocs/intune/protect/security-baselines.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/security-baselines.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by Brenduns** [comment]
Consulting with PM/Dev.

**Comment by Brenduns** [comment]
@i-windows  Thanks for this feedback. I've shared it with the Intune product team, and we discussed the expected schedules and timelines, and they agree: it’s been too long between updates. However, some updates, such as the Windows baseline, remain in the works. They understand the delays are not well received, and they are working on it. (Not a great message to deliver, but it’s the message I have.).  As each new baseline or update becomes available, we'll announce it in our What's New article, and update the related documentation. 

The goal is to have updates to baselines available within Intune around four to six weeks after the Group Policy version of a baeline is updated.  The GP based baselines are the source of the Intune baselines - which Intune ingests to the UI to make it easier to deploy them.

Why has it been so long?  Simply put: A change of infrastructure for devcie configuratino settings has been in progress, and is not yet complete in all areas.

The driver of these delays is the work that is ongoing to convert the underlying settings infrastructure for device configuration settings from an older framework to a newer one - so that settings and functionality can be directly tied to the CSPs on devices that the baseline manages.  You might have noticed some policies have been updating to this newer setting format that directly pulls from the CSPs they manage, as has the recently released [M365 Office Apps baseline](https://learn.microsoft.com/mem/intune/fundamentals/whats-new#new-security-baseline-for-microsoft-365-office-apps). 

Some baselines, such as the Windows baseline, have presented some harder challenges to resovle. 

However, once the framework is reworked, the dev team expects to start rolling out long over due updates, and see existing baselines update on much more regular, cadence.
