### ISSUE TITLE
Missing Section in Domain Join Profile

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/memdocs#4310]
Many of our autopiloted devices show 'Not applicable' on the Domain Join profile we created. When looking more closely at the Domain Join profile, there is a new "Applicability Rules" section. Your support page does not address this section. If I do not include any rules, does it simply skip completely, even if the device is in the assigned group? This seems to be the case. Please expand on the applicability rules with as much detail as possible. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06881bc7-a1ce-f3e8-4dcb-e1970d8134cb
* Version Independent ID: 665a4ee8-e658-3910-c535-2ab097a19a23
* Content: [Domain join profile settings for Windows 10/11 in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/configuration/domain-join-configure)
* Content Source: [memdocs/intune/configuration/domain-join-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/configuration/domain-join-configure.md)
* Service: **microsoft-intune**
* Sub-service: **configuration**
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by yogkumgit** [comment]
@MandiOhlinger Please help us in resolving this issue. Thanks

**Comment by MandiOhlinger** [comment]
@DontNeedNoGit We added the Applicability Rules step. The changes should be live later today or tomorrow. Thank you!

Also, https://learn.microsoft.com/mem/intune/configuration/device-profile-create#applicability-rules has more info on Applicability Rules.

I don't believe Applicability Rules are required. If you are seeing otherwise, then I suggest posting your issue on [Microsoft Q&A](https://docs.microsoft.com/answers/products/enterprise-mobility-security) or [opening a support case](https://learn.microsoft.com/mem/get-support).

FYI @yogkumgit
