### ISSUE TITLE
Endpoint Security disk encryption policy - not available/visible in our tennant

### ISSUE THREAD

**Issue by i-windows** [MicrosoftDocs/memdocs#4325]
[Enter feedback here]

These settings are not available in Endpoint Security disk encryption policy in our tennant

..."Endpoint security disk encryption policy - Configure the following settings in the BitLocker profile:

Hide prompt about third-party encryption = Yes
Allow standard users to enable encryption during Autopilot = Yes
Require Key File Creation = Allowed or Blocked
Recovery Password Creation = Allowed or Required"

for example - "Allow standard users to enable encryption during Autopilot = Yes" is not present, however this setting is present.

![image](https://github.com/MicrosoftDocs/memdocs/assets/6116167/9b286575-8e42-4d3a-be39-35b66f8e4907)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54cccf1d-81fd-5331-aee7-59a35b39cb15
* Version Independent ID: 81d14392-fe74-4fd9-047f-7b8292d84f0c
* Content: [Encrypt Windows devices with BitLocker in Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/encrypt-devices)
* Content Source: [memdocs/intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by i-windows** [comment]
after further research it seems like the documentation page is completely out of date, the settings and screen shots shown are no longer valid and the page needs to be rewritten with the correct configuration

**Comment by yogkumgit** [comment]
@Brenduns Please help us in resolving this issue. Thanks

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by Brenduns** [comment]
Content has updated been updated to resolve issues with guidance for silently enabling BitLocker, and to align content to the udpated setting names from BitLocker which are rendered into the Intune UI.
