### ISSUE TITLE
WinRE not enabled

### ISSUE THREAD

**Issue by jminnselset** [MicrosoftDocs/memdocs#4366]
"If [WinRE] isn't configured and enabled, an error such as Error code: ERROR_NOT_SUPPORTED (0x80070032) is reported."

Reported where? What is the end user experience - will the reset just not happen or will it fail ungracefully at some point in the process?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca1cdb90-ea7b-7178-810a-8242b88bec91
* Version Independent ID: ca1cdb90-ea7b-7178-810a-8242b88bec91
* Content: [Windows Autopilot Reset](https://learn.microsoft.com/en-us/autopilot/windows-autopilot-reset)
* Content Source: [autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/main/autopilot/windows-autopilot-reset.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @jminnselset. The error is displayed in the logs. Because the WinRE check is done before the reset ever occurs, then the end user will never seen anything. The reset just won't occur. Think of it as a prerequisite check and it won't proceed if WinRE isn't available. I will add some clarification to the docs.
