### ISSUE TITLE
incorrect targeting wording

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/memdocs#4412]
[Enter feedback here]
In Step 8 of Step 2 (Create Enrollment Profile) it states that the profile should be assigned to All Devices or a group.

This should state All Users or a group of users, as devices cannot be targeted prior to enrollment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3e7fb9-c0c2-d427-6ff0-dc790c889ca8
* Version Independent ID: 5c3e7fb9-c0c2-d427-6ff0-dc790c889ca8
* Content: [Set up web based device enrollment - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/web-based-device-enrollment-ios#step-2-create-enrollment-profile)
* Content Source: [memdocs/intune/enrollment/web-based-device-enrollment-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/web-based-device-enrollment-ios.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by msbemba** [comment]
@deanellerby Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4442

Once the author approves, the changes will be live.

Thanks
Sri
