### ISSUE TITLE
Android Compliance policy doesn't apply in full to Fully-managed devices when targeted at users instead of devices too

### ISSUE THREAD

**Issue by mcnaugha** [MicrosoftDocs/memdocs#4415]
There's an important note which says "To apply to Android Enterprise **dedicated devices**, compliance policy must target devices, not users.", however, it would seem this partially applies to Fully-managed as well. Whenever you apply an Android compliance policy to a group of users with Fully-Managed devices, critical parts of the policy are never applied, e.g. password requirements.

If the above is accurate, I recommend this note changing to advise that it can affect other modes of Android Enterprise too. It may be better to say that Android compliance policies should only be targeted at groups of devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9c611f-edcb-81fd-b76e-207dd5b3fe04
* Version Independent ID: e5998630-06e9-2051-5d40-1e1509e7fddb
* Content: [Android Enterprise compliance settings in Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/protect/compliance-policy-create-android-for-work)
* Content Source: [memdocs/intune/protect/compliance-policy-create-android-for-work.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/protect/compliance-policy-create-android-for-work.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by msbemba** [comment]
@mcnaugha Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4443

Once the author approves, the changes will be live.

Thanks
Sri
