### ISSUE TITLE
Windows version mistype?

### ISSUE THREAD

**Issue by RichardGallo-MS** [MicrosoftDocs/memdocs#4427]
In the article, it states that Windows MAM is support on "Windows 10, build 19046.3636, KB5031445" - I'm assuming that this is a typo since there is such thing as 19046. 

![image](https://github.com/MicrosoftDocs/memdocs/assets/85750944/599e2071-b428-4906-80b9-44ade0869237)

19045 is the correct version. My customer asked for a clarification on this, and I told them it was likely a typo... See the KB build information here, showing the correct version - 

[https://support.microsoft.com/en-us/topic/october-26-2023-kb5031445-os-build-19045-3636-preview-03f350cb-57f9-45e6-bfd7-438895d3c7fa](https://support.microsoft.com/en-us/topic/october-26-2023-kb5031445-os-build-19045-3636-preview-03f350cb-57f9-45e6-bfd7-438895d3c7fa)

Possible to update?

Thanks so much!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0797fdd1-9daa-722b-2a39-c3844831a664
* Version Independent ID: 0797fdd1-9daa-722b-2a39-c3844831a664
* Content: [Data protection for Windows MAM](https://learn.microsoft.com/en-us/mem/intune/apps/protect-mam-windows)
* Content Source: [memdocs/intune/apps/protect-mam-windows.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/apps/protect-mam-windows.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by msbemba** [comment]
@RichardGallo-MS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/4444

Once the author approves, the changes will be live.

Thanks
Sri
