### ISSUE TITLE
Error in Apple push certificates portal when uploading csr file IntuneCSR.csr instead of IntuneCSR.csr.txt

### ISSUE THREAD

**Issue by morrizon** [MicrosoftDocs/memdocs#4434]
The CSR downloaded it is not accepted with the current name, IntuneCSR.csr, and it is only accepted with the name IntuneCSR.csr.txt. it should be clarified in the documentation and it should be friendly if it was downloaded already with the TXT extension instead until Apple fix the issue. I could resolve the issue because I found the solution here: https://developer.apple.com/forums/thread/702446

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: babf49ae-ec79-e627-9dbf-2df2eb8909ab
* Version Independent ID: 90f3f372-9326-473e-3f82-e28e89853d49
* Content: [Get an Apple MDM Push certificate for Intune - Microsoft Intune](https://learn.microsoft.com/en-us/mem/intune/enrollment/apple-mdm-push-certificate-get)
* Content Source: [memdocs/intune/enrollment/apple-mdm-push-certificate-get.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/intune/enrollment/apple-mdm-push-certificate-get.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by yogkumgit** [comment]
Closing as per author's comment. Thanks
