### ISSUE TITLE
Missing URL for Windows Store for Business Sync

### ISSUE THREAD

**Issue by CraigTolley** [MicrosoftDocs/memdocs#471]
The following URL is required for the Windows Store for Business Sync. I can't see it on the WSfB pages either. 

* bspmts.mp.microsoft.com
* store-images.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9e88a5-bc7d-4982-4564-ceea80bde0e7
* Version Independent ID: 817824fe-5b44-ebeb-75c4-9eeb2dfa13ce
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/network/internet-endpoints#delivery-optimization)
* Content Source: [memdocs/configmgr/core/plan-design/network/internet-endpoints.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
We don't explicitly document the endpoints for the Store, but rely on the Store docs to provide the list in the linked article. Unfortunately that page isn't enabled for feedback, otherwise I would direct you there. I can try to send this feedback internally to the writer of that article, but I can't promise any result. I did find one of the endpoints you mentioned in this article: https://docs.microsoft.com/windows/privacy/manage-windows-1809-endpoints, but it's not in the version 2004 article. So it might vary by version of Windows. I suggest you also review those lists for the version of Windows 10 that you're using.
I'm going to close this issue because there's unfortunately not much more I can do to help.
