### ISSUE TITLE
SQL Servers accounts and gSMA

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/memdocs#473]
I think there is still some confusion on how to configure the SQL Server service: 
I suggest to be more explicit and clarify whether running SQL Server services under the **gMSA** is supported or not together with ConfigMgr.
I know well that we do not document what is not supported, but this could be an important information for the people in the field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142474e9-8dd5-6412-85ca-b1d2dc8c01ac
* Version Independent ID: d4de0aa7-2579-acdf-f7f5-04a39d8045d8
* Content: [Supported SQL Server versions - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/support-for-sql-server-versions#sql-server-service)
* Content Source: [memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/plan-design/configs/support-for-sql-server-versions.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @AlexCesarini, I don’t think it’s something that the engineering team tests with, but it might still work. Windows handles the authentication, so that shouldn’t have any effect on ConfigMgr or SQL. For example, if you look at the [MFA implementation](https://docs.microsoft.com/mem/configmgr/core/plan-design/hierarchy/plan-for-the-sms-provider#bkmk_auth) in ConfigMgr, it just changes the type of auth that it requires from Windows, the site doesn’t actually do any auth itself.

In this instance, I don't want to state that we don't support it, since it's untested. The best path for asking for official support of gMSA is to file an idea on UserVoice. It looks like there are already a couple of ideas to vote up:
- https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/32416375-add-support-for-msa-gmsa-for-standard-roles
- https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/37508179-suport-group-managed-service-account-gmsa-same-as
