### ISSUE TITLE
Face Unlock option is getting disabled in Android 10 Motorola Edge mobile by Intune

### ISSUE THREAD

**Issue by kuttusim** [MicrosoftDocs/memdocs#500]
We have'nt configured any policy to block face unlock, even though it is happening on some the android 10 devices. we tried both Device Administrator and Work profile

**Comment by MandiOhlinger** [comment]
@kuttusim We suggest posting this on the [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs, who are very experienced, knowledgeable, and helpful.

You can also work with the [Intune support team]((https://docs.microsoft.com/intune/get-support) to help find root cause.
