### ISSUE TITLE
Vague use of the term "Internet Endpoints"

### ISSUE THREAD

**Issue by ChrisSugdinis** [MicrosoftDocs/memdocs#504]
https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#internet-access-requirements

The doc says 

CURRENT
"If your organization restricts communication with the internet using a firewall or proxy device, you need to allow CMG connection point and service connection point to access internet endpoints". 

PROPOSED
"If your organization restricts communication with the internet using a firewall or proxy device, you need to allow the CMG connection point and the service connection point to access the CMG VM instances in Azure (internet endpoints)". 

Internet endpoints can be a misleading or vague term. Client devices are what customers think of when they see internet endpoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d4e4f7-68ed-e604-b577-2c18617d1c2e
* Version Independent ID: 1ce10bc0-2a6d-405a-a9ae-46adfaac8fe6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#bkmk_port-note2)
* Content Source: [memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ChrisSugdinis, thanks for the feedback. If you look at the linked list of [Internet access requirements](https://docs.microsoft.com/mem/configmgr/core/plan-design/network/internet-endpoints#bkmk_cloud) for cloud services, it's not just the Azure VMs. There's a management endpoint, probably blob storage, and possibly the Graph endpoint for discovery. So I think that line is somewhat purposefully vague in this context, because the specifics depend upon the customer's implementation.

@mestew and I debated this for a bit, and did some searching with other sources. We're currently thinking that we want to keep the term as-is. So I'm going to close this issue. If you're passionate about it, let me know and we can reconsider.

**Comment by ChrisSugdinis** [comment]
Hi Aaron,

Thanks for letting me know you looked at this and even went as far as to collaborate with others to get their take. I certainly don’t want to ruffle any feathers over this.

In recent years the ConfigMgr documentation has improved exponentially. Thanks to you and everyone else who has helped to make that so.


[cid:image001.jpg@01D65ABC.9B934600]

Chris Sugdinis
Sr. Premier Field Engineer
Secure Infrastructure
Mobile: +1.813.919.9881
Email: chrissu@microsoft.com<mailto:chrissu@microsoft.com>

**Comment by aczechowski** [comment]
(just made a quick edit to your comment to remove your email signature. when you reply by email it appends the whole thing. assumed you didn't want that info publicly available here :wink)

**Comment by ChrisSugdinis** [comment]
Thanks Aaron ☺
