### ISSUE TITLE
IMEI is not supported on iOS?

### ISSUE THREAD

**Issue by ra-ful** [MicrosoftDocs/memdocs#511]
This site shows IMEI is not supported on iOS for identify corporate-owned devices.

>
Platform | IMEI numbers | Serial numbers
Windows | Supported (Windows Phone) | Not supported
iOS/macOS | Not supported | Supported

https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add#identify-corporate-owned-devices-with-imei-or-serial-number

But this site shows that device can be classified as corporate device by registering with IMEI.
>Registered with a serial number or IMEI.

https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c2d91-8808-a504-da13-526b152a5cfe
* Version Independent ID: 037b60a6-d6b5-75ad-1933-39d0f7a69048
* Content: [Set enrollment restrictions in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#blocking-personal-iosipados-devices)
* Content Source: [memdocs/intune/enrollment/enrollment-restrictions-set.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/enrollment/enrollment-restrictions-set.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by ErikjeMS** [comment]
@ra-ful Not supported is correct. The docs will be corrected later today. I've pointed the table entry at the relevant Important, which states: "Some Android and iOS/iPadOS devices have multiple IMEI numbers. Intune only reads one IMEI number per enrolled device. If you import an IMEI number but it is not the IMEI inventoried by Intune, the device is classified as a personal device instead of a corporate-owned device. If you import multiple IMEI numbers for a device, uninventoried numbers display **Unknown** for enrollment status." We list iOS as not supported because of this possibility of multiple IMEIs. Thanks!
