### ISSUE TITLE
Do we still have limit for Root CA and Intermediate CA in CMG Properties?

### ISSUE THREAD

**Issue by Navneet-Singh-Ghura** [MicrosoftDocs/memdocs#536]
In version 1902 and earlier, you can only add two trusted root CAs and four intermediate (subordinate) CAs.

But in 1910 I was able to add more than 2 Root CA's and it worked. 

I think doc needs to be updated if the product has been improved.

**Comment by aczechowski** [comment]
Hi @Navneet-Singh-Ghura. This info is mentioned in two places:
- [Certificates for CMG](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway#bkmk_clientroot)
- [Set up CMG](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway#set-up-a-cmg)

The note is that in earlier versions, there is a limitation. Thus in later versions, there is _not_ a limitation. Which is why you could add more in version 1910. 😄
