### ISSUE TITLE
Section that shows "OS deployment. However, you can deploy task sequences that don't deploy an OS." 

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/memdocs#542]
This needs more detail, it states "**OS deployment. However, you can deploy task sequences that don't deploy an OS**."  but is that really accurate?

- Can you use Task sequences that aren't using boot images and are deployed with an option: Download all content locally before starting task sequence?

- Can you use Task sequences that aren't using boot images with either download option

- Can you use do Windows 10 in-place upgrade task sequence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0894e83-ae5e-960f-169c-cb5ea0e85a10
* Version Independent ID: 2a3ad459-44e9-7fe1-f2b9-a6b8ad58afa9
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/clients/manage/plan-internet-based-client-management)
* Content Source: [memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/clients/manage/plan-internet-based-client-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavidHBaur for the feedback. Internet-based client management (IBCM) has been around for many years, and has never supported OS deployment. The caveat as noted is that you could use a task sequence to deploy an app or run a script or something of the sort. The deployment options shouldn't matter with IBCM, since the client is talking directly to internet-based site systems. And ultimately those statements come down to what's tested - I'm sure we haven't done further testing with IBCM with newer features like in-place upgrade. I think it's unlikely that IBCM will ever support newer features. Using CMG is the solution for that support.
