### ISSUE TITLE
"Send preview email" not documented

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#548]
The "Send preview email" button on the compliance Notifications page is not documented, what email addresses will receive this preview email?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e7ac08-bfd6-9560-ad25-bced9b944822
* Version Independent ID: 6b1f70f0-aed3-52ac-25eb-1de55babc9d0
* Content: [Noncompliant message and actions with Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/actions-for-noncompliance)
* Content Source: [memdocs/intune/protect/actions-for-noncompliance.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/actions-for-noncompliance.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@Martony78  Thanks for the question. We'll be revising the content later today to fix this. The email is sent to the account your logged into Intune with at the time you click on _Send preview email_.

**Comment by rasldasl** [comment]
What permissions are required to send preview? My Intune Administrator account does not have email so I logged in with another account that has email and fewer permissions in Intune. I'm not receiving the preview emails.

**Comment by Brenduns** [comment]
@rasldasl   Thanks for this question. Can you confirm if the account you logged into has a license for Intune, and if it's E3 or other?

**Comment by rasldasl** [comment]
Yes, both accounts have an Intune license. We did some more testing and it seems you need Intune Administrator or Global Administrator to create the email templates and also to test. There is just no error when testing with insufficient rights.

We are attempting a workaround to add the admin account’s email address to my standard account.

Sent from my iPhone

On Sep 16, 2020, at 2:43 PM, Brent Dunsire <notifications@github.com> wrote:

﻿

@rasldasl<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasldasl&data=02%7C01%7C%7C8f4c2c74ad0848c44f3e08d85a78d01c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637358822210037349&sdata=Efbk8DpvOynWvxiO1Nipx0Fj7oPkG63wK98QKMNnlQo%3D&reserved=0> Thanks for this question. Can you confirm if the account you logged into has a license for Intune, and if it's E3 or other?

**Comment by Brenduns** [comment]
@rasldasl  Our engineering team has confirmed the following roles have permissions to send the preview email: _Azure AD Global Administrator_,  Intune _Administrator_ (Intune Azure AD Intune Service Administrator), and the Intune Pol_icy and Profile Manager_. 

I’ll be submitting an update to add this information to the article.

**Comment by rasldasl** [comment]
Brent -

This was the answer I needed to get this working. The first two roles are Azure roles but I was able to add the Intune Policy and Profile Manager role to my ID that has email.

Thanks so much!

Robert Stein

Sent from my iPhone

On Sep 21, 2020, at 1:02 PM, Brent Dunsire <notifications@github.com> wrote:

﻿

@rasldasl<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasldasl&data=02%7C01%7C%7C14c2dcd9903e4230194908d85e58895c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637363081632455818&sdata=3w5a%2BEuUpdWL6ViwU%2FHCvtNvFGNdUFlxuBpsLGjOkGU%3D&reserved=0> Our engineering team has confirmed the following roles have permissions to send the preview email: Azure AD Global Administrator, Intune Administrator (Intune Azure AD Intune Service Administrator), and the Intune Pol_icy and Profile Manager_.

I’ll be submitting an update to add this information to the article.

**Comment by rasldasl** [comment]
Have these permissions changed in 2107? I lost the ability to see the notifications when signed in as Policy and Profile Manager.

**Comment by Brenduns** [comment]
@rasldasl  Hello Robert,  I'm not aware of any work/changes in this feature area for 2107. I just forwarded this question to our engineering team to see if they are aware of any changes that didn't reach content. Once I hear back, I'll update you.  I will be out as of Friday evening however for a week... So I hope to hear back right away.

**Comment by Brenduns** [comment]
@rasldasl  Hello, I've heard back and recent work, per 2107,  should not have affected the Policy and Profile Manager role. Unfortunately, we can't provide troubleshooting via this doc feedback venue for this so if after reviewing or testing an accounts RBAC permissions and assigned roles, you find its still not able to function as expected, I suggest contacting [Support ](https://docs.microsoft.com/mem/get-support)for a deeper look. I wish I had something more to offer for this.

**Comment by rasldasl** [comment]
Brent -

Thanks so much for checking into it. If I can’t figure it out I’ll open a support case.

Enjoy your time off.

Robert

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rasldasl** [comment]
RBAC was my issue. I did not realize that the Default scope tag only included items with no other scope tags.

Sent from my iPhone

On Aug 6, 2021, at 4:47 PM, Brent Dunsire ***@***.***> wrote:

﻿

@rasldasl<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasldasl&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361505230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WxaT5sdZsu%2Bjnx7ZsoVyaiK99C4d38K3s8gInhld%2BgM%3D&reserved=0> Hello, I've heard back and recent work, per 2107, should not have affected the Policy and Profile Manager role. Unfortunately, we can't provide troubleshooting via this doc feedback venue for this so if after reviewing or testing an accounts RBAC permissions and assigned roles, you find its still not able to function as expected, I suggest contacting Support <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fmem%2Fget-support&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361515188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yg58nUkpZ%2FVs1rqURMJ6Xhl001HZUKqBsp9oHZIMpLY%3D&reserved=0> for a deeper look. I wish I had something more to offer for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmemdocs%2Fissues%2F548%23issuecomment-894535452&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361515188%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UzMiBBOAHAqtkQ%2FZa1%2BI20HfcUbdqvu6nzzdk0faTgM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJGHLJ6U464RSFD2QNQI2ZLT3RJ6HANCNFSM4PGS3MNQ&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361525142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yisswjhckLKtJelVaItYN5uiCtP21m75fvqUGK5VMgM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361535103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O6ElNL1yYReWgE7L122UY1zEVOdjsWIX6RSgOAEVdSU%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C8a35a16294c047e9371608d95923c162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638832361535103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a0kcUNi3BvpeXWY8Fs17brtr%2FhVk5kj5HPbZxAmWBYc%3D&reserved=0>.
