### ISSUE TITLE
Updates Needed

### ISSUE THREAD

**Issue by JD-TB** [MicrosoftDocs/memdocs#575]
Hey,

The instructions here are out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ef909-c4fb-f052-9d2e-c794efc9efd7
* Version Independent ID: 655e8b80-0471-5789-8bf1-20403390c012
* Content: [Remotely administer devices in Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support)
* Content Source: [memdocs/intune/remote-actions/teamviewer-support.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/remote-actions/teamviewer-support.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by MandiOhlinger** [comment]
@JD-TB Thank you. It seems they were updated since you opened this GitHub issue. I did clean up the article a bit. Changes should be live later today.

For UI changes, it'd be great if you created a pull request (PR) with your recommended changes. We review every PR before it gets published. Sometimes the UI changes faster than we can keep up. So, we'd love the help. 

Thanks again.
