### ISSUE TITLE
ADR for SCEP

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/memdocs#609]
The article states "The SCEP and Windows Defender Antivirus Updates template provides common settings to use when you deploy Endpoint Protection definition updates."
However, that template includes the classifications of "Critical Updates" and "Definition Updates" only. However, some Defender updates are under the "Updates" classification.
Thanks!
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e981baa4-b42b-c9e3-b7ed-d6d72c1265f8
* Version Independent ID: a4ac5770-f3a2-79db-3c96-88cb15d4840c
* Content: [Prerequisites for software updates - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/sum/plan-design/prerequisites-for-software-updates#BKMK_wsus2012)
* Content Source: [memdocs/configmgr/sum/plan-design/prerequisites-for-software-updates.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/sum/plan-design/prerequisites-for-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @matziq for taking the time to provide feedback on Configuration Manager! I think the change is more important to make to the template itself, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) See the [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) section in our docs. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'll also add a note to this article.
