### ISSUE TITLE
Intune policy to enable local autopilot reset is called "general/Autopilot Reset" instead of "general/Automatic Redeployment" - Reset

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/memdocs#621]
The instructions say:

```
MDM provider

When using Intune, you can create a new device configuration profile, specifying "Windows 10 or later" for the platform, "Device restrictions" for the profile type, and "General" for the settings category. The Automatic Redeployment setting should be set to Allow. Deploy this setting to all devices where a local reset should be permitted.

```

In my Intune, this is called "Autopilot Reset":
![image](https://user-images.githubusercontent.com/20435853/90134522-96d7f600-dd71-11ea-95d7-1a4252a87ff2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @w0ut0 . I apologize for the time it took to get back to you regarding this feedback item. It appears that since you filled out this feedback item the docs were properly updated to say Autopilot Reset instead of Automatic Redeployment. I am going to go ahead and close this item out but if you have any other questions, please feel free to open a new feedback item.
