### ISSUE TITLE
Article refers to copy CCMSETUP command line parameters from Enablement - it's not there (in 2002)

### ISSUE THREAD

**Issue by aglego** [MicrosoftDocs/memdocs#635]
The article makes a couple of references to copying CCMSETUP command line parameters from the Enablement property page for the Co-Management object (either at creation time or looking at its properties post co-management setup). I don't see the command line parameters listed on that Enablement property page or anywhere else. The screen shot of the enablement page in the article doesn't show it either. It looks as if I'm supposed to include a GUID of some sort as part of the path (for the /MP parameter), but I have no idea where to get that GUID.
![3555750-co-management-onboarding-enablement](https://user-images.githubusercontent.com/31051372/90355980-89569080-e03d-11ea-94ff-98d29cd4a266.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01fcdfb-06ea-51c1-890c-5ccf63ae8f36
* Version Independent ID: d7766b63-8462-c281-d74b-8e2c5fae6103
* Content: [Tutorial: Enable co-management for internet devices - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/comanage/tutorial-co-manage-new-devices)
* Content Source: [memdocs/configmgr/comanage/tutorial-co-manage-new-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/comanage/tutorial-co-manage-new-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @aglego, you should see it on the **Enablement** tab of the properties page after you setup co-management. I don't think it shows on the wizard page, so I'll revise the page to not reference that. You can also see more information about this command line in the following articles:

- https://docs.microsoft.com/mem/configmgr/comanage/how-to-prepare-win10#install-the-configuration-manager-client
- https://docs.microsoft.com/mem/configmgr/core/clients/deploy/about-client-installation-properties#ccmhostname (this article includes a sample PowerShell command that you can run on a client to get that GUID)

**Comment by aglego** [comment]
Hi Aaron. I didn’t see it on the properties post-setup either. I’m wondering if this got removed with 2002?

Thanks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aczechowski** [comment]
Nope, it's still there. 😄 I double-checked with the feature team to make sure! If you follow through this tutorial, it has you set up a cloud management gateway (CMG) among other prerequisites for this internet-based scenario. If the site doesn't have a CMG or other internet-based device prerequisites, then it doesn't show the command line, since you can't use it without those prerequisites. That's definitely something that we need to explicitly add in a few spots to be more clear. It's implied, but a good tip to add.

If you have those prerequisites in your site but still aren't seeing it, then best to seek a better option for support:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aglego** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aczechowski** [comment]
I made a change for this issue, adding a tip to four separate articles that reference it. This issue will auto close when my change merges, and then will go live with the next daily publishing process, which should be later today.
