### ISSUE TITLE
No Company Portal folder on Android Fully Managed Devices

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/memdocs#755]
There is no com.microsoft.windowsintune.companyportal folder on Android Enterprise Fully Managed devices since the Intune app is used, not the company portal one.
I tried to find the log files under "Phone\Android\data\com.microsoft.intune\files" but is empty, even when verbose logging is enabled.
I also tried to send the log by email but there is no attached file...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 426365c8-4113-b445-7ecd-ab2117bcf52a
* Version Independent ID: cbec76e3-b29d-7fb6-b724-ca8b8b29a954
* Content: [Upload and email logs using a USB cable](https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-using-cable-android)
* Content Source: [memdocs/intune/user-help/send-logs-to-your-it-admin-using-cable-android.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/user-help/send-logs-to-your-it-admin-using-cable-android.md)
* Service: **microsoft-intune**
* Sub-service: **end-user**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Thanks for reaching out to the Intune documentation team. We haven't been able to find an answer for this issue yet but are tracking it internally because others have reported the same experience. If you're still seeking clarification, please try one of these support channels: 

**Device users:**

* Contact the IT support person at your work or school for help.

**IT administrators:**

* Open a support ticket by following the steps here: [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support)  

* Post on [Microsoft Q & A](https://docs.microsoft.com/answers/products/?WT.mc_id=msdnredirect-web-msdn).

* Browse the old [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/home?forum=microsoftintuneprod). The site was recently replaced with Microsoft Q & A but still shows the old posts from our community MVPs who are very experienced, knowledgeable, and helpful.

* Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
