### ISSUE TITLE
Intune settings for the iOS/iPadOS Classroom app documentation is out of date

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/memdocs#796]
It seems to me that a lot of this information is out of date and a complete overhaul is needed.

Some examples:
> 1. Sign in to Intune.

The URL points to the old Intune portal/URL.
> 2. On the Intune pane, choose Device configuration.

Device configuration is renamed.
> 3. On the Create profile pane, enter a Name and Description for the iOS/iPadOS education profile.

I'm in an EDU tenant, but I can't see no "education profile" to create.

Therefor, it seems to me that this whole doc needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc0159d-5a5e-ea2c-042d-bd5ead842d0b
* Version Independent ID: 83266995-5234-3b09-784d-75bb1844e5f3
* Content: [Intune settings for the iOS/iPadOS Classroom app - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/education-settings-configure-ios)
* Content Source: [memdocs/intune/fundamentals/education-settings-configure-ios.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/education-settings-configure-ios.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by lenewsad** [comment]
Hi @p0shkar, thank you for your feedback. This article details an obsolete feature in Intune. However, we still provide support to those tenants who had education profiles set up prior to the deprecation. So that's why this article still exists. We included a banner at the top of the page that explains who the article is for to try to clear up confusion. 

I'm closing this issue as there isn't any updates to be made to this article at this time. Thank you!
