### ISSUE TITLE
Hello for Business part of MDM Security Baseline does not exist

### ISSUE THREAD

**Issue by JankeSkanke** [MicrosoftDocs/memdocs#798]
**Windows Hello for Business**
Block Windows Hello for Business
This setting has been removed from the baseline (Aug 2020) but the docs says it is. Customer had set this setting and now suddenly all users got prompted for WHFB enrollment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0f4d5d-fdd1-22e7-6372-9916b199209f
* Version Independent ID: caeb9f8b-30ad-7f02-4740-56522b2f9b1b
* Content: [Intune security baselines settings for Windows 10 MDM - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-mdm-all?pivots=mdm-sept-2020)
* Content Source: [memdocs/intune/protect/security-baseline-settings-mdm-all.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/security-baseline-settings-mdm-all.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@JankeSkanke  Thanks for the feedback here. The content has received an update (which will be live later today) which removes the Windows Hello section from the August 2020 baseline.  The August 2020 baseline also dropped the _Above Lock_ section.  

Because of the behavior you've described, I've passed your post on to our product team. When a baseline no longer manages a setting (such as when you update a baseline from one version to the latest, and a host of settings are no longer included in the newer version), those removed settings should remain set on devices per their last configuration. They shouldn't be reset or changed when no longer managed by a baseline. The are instead, no longer enforced.  When no longer enforced by a baseline, something else can actively change them. If you are seeing something that suggests that application of the updated baseline which doesn't manage those settings has caused a change in device behavior, that could be worth contacting support to investigate further. ,That isn't expected, and just yesterday [details around the change of baseline version](https://docs.microsoft.com/en-us/mem/intune/protect/security-baselines#change-the-baseline-version-for-a-profile) were revised in docs to help make the baseline version update expectations more clear.
