### ISSUE TITLE
Prerequisites to follow installation guide not being mentioned

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/memdocs#813]
"mst-readiness account" tool seems to need "jq" to run. This is at least not part of an Ubuntu 20.04 server basic installation.

You might want to add the requirement to install:
sudo apt install jq

Also "mst-CA-readiness.ps1" will only run with "Set-ExecutionPolicy -executionPolicy Unrestricted", because it is not signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebaa15c-1e00-c075-eff2-79d4c10ba6af
* Version Independent ID: c9dfee71-1c01-4318-725c-b4bb97052efb
* Content: [Use the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-overview)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-overview.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-overview.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@pmeuser  Thanks for the feedback Peter, I've consolidated the answer here from your related feedback via https://github.com/MicrosoftDocs/memdocs/issues/812.

- In the section for the readiness tool, **jq** is already listed as a requirement. This isn't a general prerequisite as its specific to this tool. Due to what appears to be command-line variance in different versions of Linux, we’ve not included those command-lines to install *jq*, at least during the preview of the Tunnel. Instead, we'll leave  that to the Linux documentation for each Linux version. 
- While in preview, Safari domains aren’t supported. Support is expected to be added in a future update. When that support is added, content will be revised. 
- For the _mst-CA-readiness.ps1_ script, your correct that its not signed and the command **Set-ExecutionPolicy -executionPolicy Unrestricted** can be required to enable use of the script. 

  I've submitted an edit that adds a caution note to the content (live later this afternoon). The note reflects the need to reduce PowerShell security to enable use of the script.  Fortunately, this is a temporary issue for the current preview for Microsoft Tunnel. A signed version of the script will become available with a future update removing the need to set execution policy to _unrestricted_. When that changes, the caution note will be removed.
