### ISSUE TITLE
Setting doesn't exist - Reset

### ISSUE THREAD

**Issue by ezapper2** [MicrosoftDocs/memdocs#815]
Can't find this setting in Intune according to article.
https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset 

Platform = Windows 10 or later
Profile type = Device restrictions
Category = General
Automatic Redeployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by ezapper2** [comment]
Platform = Windows 10 or later
Profile type = Device restrictions
Category = General
Automatic Redeployment

**Comment by greg-lindsay** [comment]
"The Autopilot Reset option will not be enabled in Microsoft Intune for devices not running Windows 10 build 17672 or higher."

Can you verify the build #?

**Comment by frankroj** [comment]
Thank you for the feedback @ezapper2. I apologize for the time it took to get back to you regarding this feedback item. It appears that since you filled out this feedback item the docs were properly updated to say Autopilot Reset instead of Automatic Redeployment. I am going to go ahead and close this item out but if you have any other questions, please feel free to open a new feedback item.
