### ISSUE TITLE
Merge settings in firewall policy don't work as documented

### ISSUE THREAD

**Issue by nahoyen** [MicrosoftDocs/memdocs#840]
[Enter feedback here]
Hello,

I have tested this and had confirmation from my Microsoft colleagues and the chapter "Firewall rule mergers and policy conflicts" is not working as documented. 
Is it stated that the merging rules only apply when there is a conflict with another Firewall rule in the local store. 
Actually when merging rules are applied and set on block" the complete local store is disabled.

Thanks for your help,
Yohan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d33743f-adf4-680b-483a-b83a625774f0
* Version Independent ID: 4b822bef-289f-77dd-8c50-fd20fdbb5f00
* Content: [Manage firewall settings with endpoint security policies in Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security-firewall-policy#firewall-rule-mergers-and-policy-conflicts)
* Content Source: [memdocs/intune/protect/endpoint-security-firewall-policy.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/endpoint-security-firewall-policy.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@nahoyen  Thanks for the feedback. I do think this overall section could use some clean up to make it more clear.  Based on your comments, I think your reading into the docs something that isn’t there, especially when referencing the *local store* (I might misunderstand your intent for local store).  Regardless of what might be my missing your intent, its clear that the content needs some help, so that is under progress for publication in a future update. 

Here is another way to describe the behavior, which might help get us on the same page: 

**Microsoft Defender Firewall rule** policies – Conflicts for *Microsoft Defender Firewall rules* are noted to have the following behavior:  
- *Microsoft Defender Firewall rule* merge isn’t based on what’s on a device already, but on what policies are configured in Intune and will be applied to a device. 
- When these rules merge on a device, that is the result of Intune sending down each rule without comparing each rule entry with the others from other _rules_ profiles.  Then, on the device, those separate rules are combined into a superset of *rules*. Thus, it is on the device that *Microsoft Defender Firewall rules* can result in a conflict. This behavior is per the example that used two profiles that each configured *Teams* in a different way. 

**Microsoft Defender Firewall** policies – In contrast to the *Microsoft Defender Firewall rule*, conflicts for settings in this type of profile are noted to *not be sent down to the device at all*. The conflict is determined by Intune based on an evaluation of all the current Intune polices that apply to the device - excluding settings and rules from a *Microsoft Defender Firewall rule* profile . When settings from different policies/profiles are found to be in conflict, Intune puts a hold on sending that conflicted setting to the device. The result is that the setting configuration that was on the device remains in place.  What’s on the device is unknown/not evaluated as part of the policy conflict determination process. 
- These conflicts must be resolved in policy/profile configurations before settings with conflicts are sent down to the device.
- Until the conflict is resolved, and the setting sent to the device, the devices current (or last) configuration will remain in place. Later, that setting can be overridden when all Intune policies that manage the setting are configured to agree, or at least not contradict each other. At that time, Intune can send down the setting configuration to manage the setting on the device.
