### ISSUE TITLE
Blog attaching

### ISSUE THREAD

**Issue by felizondojr** [MicrosoftDocs/memdocs#878]
[Enter feedback here]
Would like to see a Blog section so blogs such as https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/trying-out-autopilot-hybrid-join-over-vpn-in-your-azure-lab/ba-p/1606723 can be easily discovered and shared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b57c9838-1004-157d-e0b1-363e770c7246
* Version Independent ID: 4fa6f34f-9438-9748-712c-c949eb22863d
* Content: [Windows Autopilot User-Driven Mode](https://docs.microsoft.com/en-us/mem/autopilot/user-driven?source=docs#user-driven-mode-for-hybrid-azure-active-directory-join-with-vpn-support)
* Content Source: [memdocs/autopilot/user-driven.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/user-driven.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Many articles have a "Related topics" section which is better than a blogs section because all related topics are not always in blogs.  The links added here would need to be approved and kept up to date, which is possible using the external author editing capability in GitHub. For example, if someone posted a non-Microsoft blog link this would need to be unapproved because we are not supposed to link to external blogs.

I'll add a "Related topics" section to this article so that it can be edited, and I'll add the link above.  Thanks!
