### ISSUE TITLE
Some remarks on "Policy sets known issues"

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/memdocs#917]
Hi,

Some comments on the "Policy sets known issues" section

When I create a policy set, I can also select MSI line of business apps (single file MSI) - does that mean it is supported, or shouldn't we use it since it's not supported.

What is meant with the statement: "Setting a policy set assignment of All Users to Autopilot Profile is unsupported." Do you perhaps mean that you cannot add an Autopilot profile to a policy set which you target to users?

About the following statement: Restrictions and ESP do not support virtual group assignments. - What are virtual group assignments? as far as I know we only have Assigned Groups/Dynamic Device and Dynamic User groups.. never heard of the concept of virtual group. Later in the article I see All Users and All Devices referenced as virtual groups.. 

About the following statement: Restrictions and ESP do not strictly support exclusion group assignments. - What does that mean exactly, do they support it, or don't they support it ? So if I create a policy group, which I assign to all devices but exclude for dynamic device group A, and includes device type restrictions and ESP config still be applicable for group A then?

Does the fact that the following two statements are under "Policy set known issues" mean that its' an issue? or will it never be supported:

a) Restrictions and ESP use priority-based conflict resolution. Restrictions and ESP might not be applied to the same users as the rest of a policy set's payloads if the Restrictions and ESP are also targeted by a higher priority Restrictions and ESP.
b) The default Restrictions and ESP cannot be added to a policy set.

Seems like this will never be possible at all, therefore it's a restriction and not an issue

About: MAM policy types that do not support policy sets include the following: MAM WIP (Windows) targeted managed app protection. With this you probably mean WIP - WE? correct?

Is it possible to rephrase the following sentence to something everyone understands: "If a policy is added to a policy set that is deployed to a group, the group would show as directly assigned in in the workload, not "assigned via the policy set". As a result of this, MAM does not process group assignment deletions coming from policy sets." ?

Might also be nice if these issues can get fixed and the functionality can come out of preview. Hopefully also Microsoft will decide to replace the security baselines functionality with pre-created policy sets so that this functionality is uniform again.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9efa1fad-ddb2-4f04-dc17-ddc7872df0d4
* Version Independent ID: 9be69699-ffb0-9fb3-ff1e-d1a4a9209589
* Content: [Policy sets - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/fundamentals/policy-sets#policy-sets-known-issues)
* Content Source: [memdocs/intune/fundamentals/policy-sets.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/fundamentals/policy-sets.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by Erikre** [comment]
Thanks for the feedback. I've created a internal work item to track this GitHub issue. If you have additional questions related to this issue, we want to make sure your questions get to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

We have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Please use the above channels if you don't already have a solution. Because I'm tracking any doc updates based on an internal work item, I'm closing this GitHub issue.
