### ISSUE TITLE
Need to add a question about migration of existing servers to Azure

### ISSUE THREAD

**Issue by Roblarson** [MicrosoftDocs/memdocs#933]
[Enter feedback here]

Customers are migrating out of their datacenters and using tools such as Azure Migrate to accomplish that. You should add a question about if Azure Migrate is supported to move existing SCCM servers or if they should be creating new servers as part of the architecture. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c839c644-12fe-b28c-f269-d833f1d8532b
* Version Independent ID: 2c974db5-592d-0736-e211-dcb762f3527c
* Content: [Configuration Manager on Azure - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/understand/configuration-manager-on-azure)
* Content Source: [memdocs/configmgr/core/understand/configuration-manager-on-azure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/understand/configuration-manager-on-azure.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Roblarson for the feedback. We haven't tested it, but it may just work. Similar to other P2V/V2V technologies, it should be transparent to apps like ConfigMgr. But since we haven't tested it, we can doc a statement either way.

If you'd like the product to officially support it, please file a UserVoice idea.
