### ISSUE TITLE
Installer fails to authenticate with MFA

### ISSUE THREAD

**Issue by marknettle** [MicrosoftDocs/memdocs#937]
When running the `mstunnel-setup` script, at step 6 you are required to authenticate to Intune with a device login. This fails if your account requires Multi-Factor Authentication. This is something which should be fixed in the product, but I couldn't find a github repository for the tunnel to raise it as an issue. So at least if this documentation indicated that you must disable MFA for this step it would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4538f49d-8c19-9227-0acf-77bef7f8d4a8
* Version Independent ID: 1b1b2c40-1fd8-3909-37ae-05ab0d27efb5
* Content: [Install and configure the Microsoft Tunnel VPN solution for Microsoft Intune - Azure](https://docs.microsoft.com/en-us/mem/intune/protect/microsoft-tunnel-configure)
* Content Source: [memdocs/intune/protect/microsoft-tunnel-configure.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/microsoft-tunnel-configure.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@marknettle  Hello Mark, I regret its taken this long to get you an answer for this. However, I've consulted with the PM for this feature area, and what you describe, a failure due to multi-factor authentication, isn't expected. 

If that is still occurring, the recommendation is to contact support so that can be investigated. Any findings would be relayed back to engineering (if they are not involved along the way) and to docs should content need revision. See [Get support](https://docs.microsoft.com/en-us/mem/get-support).  Unfortunately, we aren't able to to provide troubleshooting assistance via this docs feedback venue.
