### ISSUE TITLE
Confused by "Your work profile is synchronized, so you can resume working right away."

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/memdocs#957]
The first paragraph of this article states: "Your work profile is synchronized, so you can resume working right away."

Further along in the article, it states: "Because the Autopilot for existing devices task sequence completes while in Windows PE, User State Migration Toolkit (USMT) data migration isn't supported as there is no way to restore the user state into the new OS. Also, the User State Migration Toolkit (USMT) does not support Azure AD-joined devices."

I am unclear on what is being referred to as the "work profile". Is that the user profile (boy, I wished we chose a term other than 'profile' for distinct AutoPilot configurations)? Some explanation of what the "work profile" is and how it is being retained would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb0ab9e-0902-8c43-5cb9-8ade31c88f5f
* Version Independent ID: d30aebff-dc9c-bcd9-2ffd-c7158da55026
* Content: [Windows Autopilot Deployment for existing devices](https://docs.microsoft.com/en-us/mem/autopilot/existing-devices)
* Content Source: [memdocs/autopilot/existing-devices.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @adamgourd for the feedback. I'm removing the references to USMT, as the current task sequence template doesn't include those steps. So that will help a bit to avoid that confusion. I'm also adding a reference to OneDrive for Business known folder redirect, which is what that first sentence is referring to. I'll clarify. The changes won't go live for a couple of weeks, as it's dependent on another release.
