### ISSUE TITLE
Slight naming change

### ISSUE THREAD

**Issue by contactbrenton** [MicrosoftDocs/memdocs#972]
Automatic Redeployment = Allow. Deploy this setting to all devices where a local reset should be permitted.

Should now read Autopilot Reset
![image](https://user-images.githubusercontent.com/41414737/98185566-facd1d80-1f60-11eb-8b02-aae04e3a7015.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8411fd84-8a1d-28e6-1535-30143be7ede2
* Version Independent ID: 4e5ecbe1-aa9b-cfa0-7b67-1ac1dcb0c465
* Content: [Windows Autopilot Reset](https://docs.microsoft.com/en-us/mem/autopilot/windows-autopilot-reset)
* Content Source: [memdocs/autopilot/windows-autopilot-reset.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/autopilot/windows-autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by frankroj** [comment]
Thank you for the feedback @contactbrenton. I apologize for the time it took to get back to you regarding this feedback item. I am not finding the item you mention in the doc so I have to assume the doc has been updated since you filed this feedback item. If you are finding it hasn't, please file a new feedback item. We are now actively monitoring feedback after an internal process wasn't properly notifying us of feedback items. Again I apologize for the delay.
